Repository deepmodeling/abacus-develop, pull requests merged in 2022-11, with the labels that each got.

#1492 Perf: optimize omp critical sections
  source/module_gint/gint.cpp
Labels: OpenMP

#1491 Feat: NPT ensemble
  source/input.cpp
  source/module_md/MD_func.cpp
  source/module_md/MSST.cpp
  source/module_md/Nose_Hoover.cpp
  source/module_md/Nose_Hoover.h
  source/module_md/mdrun.cpp
  source/module_md/test/FIRE_test.cpp
  source/module_md/test/Langevin_test.cpp
  source/module_md/test/NVT_NHC_test.cpp
  source/module_md/test/verlet_test.cpp
  source/module_md/verlet.cpp
  source/src_io/print_info.cpp
  source/src_io/write_input.cpp
  tests/integrate/420_LJ_MD_NPT_iso/INPUT
  tests/integrate/420_LJ_MD_NPT_iso/STRU
  tests/integrate/420_LJ_MD_NPT_iso/jd
  tests/integrate/420_LJ_MD_NPT_iso/result.ref
  tests/integrate/CASES
Labels: Feature

#1514 Fix: read SPIN_CHG twice in lcao relax when init_chg == file
  source/module_cell/unitcell.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt/operator.h
Labels: Bug
