Repository deepmodeling/abacus-develop, pull requests merged in 2022-05, with the labels that each got.

#906 test(Parallel): add UT of `split_diag_world` and `split_grid_world`
  source/src_parallel/test/CMakeLists.txt
  source/src_parallel/test/parallel_global_test.cpp
  source/src_parallel/test/parallel_global_test.sh
Labels: Test

#927 feature : Dipole correction
  docs/input-main.md
  source/Makefile.Objects
  source/input.cpp
  source/input.h
  source/input_conv.cpp
  source/module_surchem/CMakeLists.txt
  source/module_surchem/efield.cpp
  source/module_surchem/efield.h
  source/src_io/write_input.cpp
  source/src_io/write_pot.cpp
  source/src_lcao/FORCE_STRESS.cpp
  source/src_pw/CMakeLists.txt
  source/src_pw/Makefile.Objects
  source/src_pw/efield.cpp
  source/src_pw/efield.h
  source/src_pw/energy.cpp
  source/src_pw/forces.cpp
  source/src_pw/potential.cpp
  tests/integrate/112_PW_dipole/INPUT
  tests/integrate/112_PW_dipole/KPT
  tests/integrate/112_PW_dipole/README
  tests/integrate/112_PW_dipole/STRU
  tests/integrate/112_PW_dipole/jd
  tests/integrate/112_PW_dipole/result.ref
  tests/integrate/112_PW_efield/INPUT
  tests/integrate/112_PW_efield/KPT
  tests/integrate/112_PW_efield/README
  tests/integrate/112_PW_efield/STRU
  tests/integrate/112_PW_efield/jd
  tests/integrate/112_PW_efield/result.ref
  tests/integrate/CASES
Labels: Feature

#941 Build(docker): add an image for running.
  .github/workflows/devcontainer.yml
  .github/workflows/image.yml
  Dockerfile
Labels: Software Engineering

#966 fix : fix md bug when cal_stress=0
  source/module_md/FIRE.cpp
  source/module_md/FIRE.h
  source/module_md/Langevin.cpp
  source/module_md/Langevin.h
  source/module_md/MD_func.cpp
  source/module_md/MSST.cpp
  source/module_md/MSST.h
  source/module_md/NVE.cpp
  source/module_md/NVE.h
  source/module_md/NVT_ADS.cpp
  source/module_md/NVT_ADS.h
  source/module_md/NVT_NHC.cpp
  source/module_md/NVT_NHC.h
  source/module_md/run_md_classic.cpp
  source/module_md/test/MD_func_test.cpp
  source/module_md/test/setcell.h
  source/module_md/verlet.cpp
  source/module_md/verlet.h
  source/src_lcao/run_md_lcao.cpp
  source/src_pw/run_md_pw.cpp
Labels: Bug
