Repository deepmodeling/abacus-develop, pull requests merged in 2022-06, with the labels that each got.

#990 Feature: detect omp threads automatically.
  source/src_parallel/parallel_global.cpp
Labels: OpenMP

#1005 fix: force can only be computed once in lcao MD/relax
  source/module_esolver/esolver_ks_lcao.cpp
Labels: Bug

#1026 fix: fix unstable UTs of MD
  source/module_md/test/FIRE_test.cpp
  source/module_md/test/LJ_pot_test.cpp
  source/module_md/test/Langevin_test.cpp
  source/module_md/test/MSST_test.cpp
  source/module_md/test/NVE_test.cpp
  source/module_md/test/NVT_ADS_test.cpp
  source/module_md/test/NVT_NHC_test.cpp
Labels: Bug

#1028 Enabling the stress label for DeePKS
  source/module_deepks/LCAO_deepks.cpp
  source/module_deepks/LCAO_deepks.h
  source/module_deepks/LCAO_deepks_io.cpp
  source/module_deepks/LCAO_deepks_pdm.cpp
  source/module_deepks/LCAO_deepks_torch.cpp
  source/module_deepks/test/LCAO_deepks_test.cpp
  source/src_lcao/FORCE_STRESS.cpp
Labels: Feature
