Repository deepmodeling/abacus-develop, pull requests merged in 2023-03, with the labels that each got.

#1985 Test:UnitTest for Vector2Ptr_v3double
  source/module_base/test/global_function_test.cpp
Labels: Test

#1965 CI: add Makefile + intel building test
  .github/workflows/build_test_cmake.yml
  .github/workflows/build_test_makefile.yml
  docs/advanced/install.md
  source/Makefile
  source/Makefile.vars
  source/module_hamilt_pw/hamilt_pwdft/Makefile
  source/module_pw/test/Makefile
  source/module_pw/test/test_gnu.sh
  source/module_pw/test/test_intel.sh
  tools/SIAB/SimulatedAnnealing/backup_old_version/1_Source/Makefile
  tools/SIAB/SimulatedAnnealing/source/Makefile
  tools/SIAB/SimulatedAnnealing/source/Makefile_hanhai20_hpcx2.9_intel2019
Labels: Test

#1977 test(vdw): add UT of module_vdw
  source/module_hamilt_general/module_vdw/CMakeLists.txt
  source/module_hamilt_general/module_vdw/test/CMakeLists.txt
  source/module_hamilt_general/module_vdw/test/c6.txt
  source/module_hamilt_general/module_vdw/test/r0.txt
  source/module_hamilt_general/module_vdw/test/vdw_test.cpp
Labels: Test

#1986 Test: add UT for hsolver_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.h
  source/module_hamilt_pw/hamilt_pwdft/wf_atomic.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_hsolver/test/test_hsolver_pw.cpp
Labels: Test

#1991 fix: reduce memory when doing postprocess of sdft
  source/module_esolver/esolver_sdft_pw.cpp
Labels: Bug

#1980 Test : add UT for v_xc
  source/module_cell/module_symmetry/test/symmetry_test.cpp
  source/module_elecstate/potentials/pot_xc.cpp
  source/module_hamilt_general/module_xc/test/CMakeLists.txt
  source/module_hamilt_general/module_xc/test/test_xc.cpp
  source/module_hamilt_general/module_xc/test/test_xc1.cpp
  source/module_hamilt_general/module_xc/test/test_xc2.cpp
  source/module_hamilt_general/module_xc/test/test_xc3.cpp
  source/module_hamilt_general/module_xc/test/test_xc4.cpp
  source/module_hamilt_general/module_xc/test/test_xc5.cpp
  source/module_hamilt_general/module_xc/test/xc3_mock.h
  source/module_hamilt_general/module_xc/xc_functional.cpp
  source/module_hamilt_general/module_xc/xc_functional.h
  source/module_hamilt_general/module_xc/xc_functional_vxc.cpp
  source/module_hamilt_general/module_xc/xc_functional_wrapper_xc.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_cc.cpp
Labels: Test

#1982 Refactor: control components written in MD_dump
  docs/advanced/input_files/input-main.md
  docs/advanced/md.md
  examples/fixed_occupations/INPUT
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/write_input.cpp
  source/module_md/MD_func.cpp
  source/module_md/MD_func.h
  source/module_md/run_md.cpp
  source/module_md/test/MD_func_test.cpp
  source/module_md/test/setcell.h
Labels: Refactor

#1984 Fix : bug of electric field in tddft
  source/module_elecstate/potentials/H_TDDFT_pw.cpp
  source/module_elecstate/potentials/H_TDDFT_pw.h
  source/module_io/dipole_io.h
  source/module_io/write_dipole.cpp
  tests/integrate/601_NO_TDDFT_H2_len_trape/result.ref
Labels: Bug

#1904 Symmetry: debug and new features
  source/Makefile.Objects
  source/module_cell/klist.cpp
  source/module_cell/klist.h
  source/module_cell/module_symmetry/symm_other.cpp
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_cell/module_symmetry/symmetry.h
  source/module_cell/module_symmetry/symmetry_basic.cpp
  source/module_cell/module_symmetry/symmetry_basic.h
  source/module_cell/module_symmetry/test/symmetry_test.cpp
  source/module_cell/test/klist_test.cpp
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/module_charge/symmetry_rho.cpp
  source/module_elecstate/module_charge/symmetry_rho.h
  source/module_elecstate/module_charge/symmetry_rhog.cpp
  source/module_elecstate/test/CMakeLists.txt
  source/module_elecstate/test/updaterhok_pw_test.h
  source/module_esolver/Makefile.Objects
  source/module_hamilt_pw/hamilt_pwdft/parallel_grid.h
  source/module_pw/pw_basis.cpp
  source/module_pw/pw_basis.h
  tests/integrate/101_PW_15_lowz/result.ref
  tests/integrate/101_PW_15_pseudopots_LibxcLDA/result.ref
  tests/integrate/107_PW_outWfcPw/result.ref
  tests/integrate/107_PW_outWfcR/result.ref
  tests/integrate/108_PW_RE/result.ref
  tests/integrate/110_PW_SY/result.ref
  tests/integrate/111_PW_S2_elec_add/result.ref
  tests/integrate/111_PW_elec_add/result.ref
  tests/integrate/121_PW_KPAR/result.ref
  tests/integrate/184_PW_BNDKPAR_SDFT_ALL/result.ref
  tests/integrate/184_PW_BNDKPAR_SDFT_MALL/result.ref
  tests/integrate/201_NO_15_pseudopots/result.ref
  tests/integrate/201_NO_KP_15_CF_CS_Si/result.ref
  tests/integrate/203_NO_bspline/result.ref
  tests/integrate/205_NO_FD_smearing/result.ref
  tests/integrate/205_NO_GA_smearing/result.ref
  tests/integrate/205_NO_MV_smearing/result.ref
  tests/integrate/211_NO_S2_elec_add/result.ref
  tests/integrate/211_NO_elec_add/result.ref
  tests/integrate/301_NO_GO_15_CF_CS/result.ref
  tests/integrate/304_NO_GO_FM/result.ref
  tests/integrate/304_NO_GO_ocp/result.ref
  tests/integrate/308_NO_GO_CF_RE/result.ref
  tests/integrate/308_NO_GO_RE_MB/result.ref
  tests/integrate/601_NO_TDDFT_CO/result.ref
  tests/integrate/601_NO_TDDFT_CO_occ/result.ref
Labels: Feature

#2013 Fix: memory leak in destructor of Operator
  source/module_hamilt_general/operator.cpp
Labels: Bug

#2012 Refactor: rename some MD input parameters
  docs/advanced/input_files/input-main.md
  docs/advanced/md.md
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/test/INPUT
  source/module_io/test/input_test.cpp
  source/module_io/write_input.cpp
  source/module_md/MD_func.cpp
  source/module_md/test/setcell.h
Labels: Refactor

#2028 Fix: bug caused by all atoms fixed in md
  source/module_md/MD_func.cpp
Labels: Bug

#2076 Feature: add macro definition __DEBUG for test-only message
  CMakeLists.txt
  source/module_base/tool_title.h
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_gint/gint_gamma_vl.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_io/input_conv.cpp
Labels: Feature
