Repository deepmodeling/abacus-develop, pull requests merged in 2023-04, with the labels that each got.

#2171 Perf: optimize rhog_symmetry
  source/module_cell/module_symmetry/symmetry.cpp
Labels: Efficiency

#2196 Test:UnitTest for BLOCK_TASK_DIST_1D
  source/module_base/test/tool_threading_test.cpp
Labels: Test

#2131 Feature: calculate asynchronous overlap matrix for Hefei-NAMD
  docs/advanced/input_files/input-main.md
  examples/hefei-namd/INPUT
  examples/hefei-namd/README
  source/module_basis/module_ao/ORB_gen_tables.cpp
  source/module_basis/module_ao/ORB_gen_tables.h
  source/module_elecstate/elecstate.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_gen_fixedH.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_gen_fixedH.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nnr.cpp
  source/module_hsolver/hsolver_lcao.cpp
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/test/input_test.cpp
  source/module_io/test/support/INPUT
  source/module_io/write_HS.cpp
  source/module_io/write_HS.h
  source/module_io/write_input.cpp
Labels: Feature

#2197 Feature: enable iso NPT for md_prec_level=1
  source/module_cell/unitcell.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/input.cpp
  source/module_md/Nose_Hoover.cpp
  tests/integrate/120_PW_KP_MD_MSST_level2/INPUT
  tests/integrate/120_PW_KP_MD_MSST_level2/KPT
  tests/integrate/120_PW_KP_MD_MSST_level2/STRU
  tests/integrate/120_PW_KP_MD_MSST_level2/jd
  tests/integrate/120_PW_KP_MD_MSST_level2/result.ref
  tests/integrate/120_PW_KP_MD_NPT/INPUT
  tests/integrate/120_PW_KP_MD_NPT/KPT
  tests/integrate/120_PW_KP_MD_NPT/STRU
  tests/integrate/120_PW_KP_MD_NPT/jd
  tests/integrate/120_PW_KP_MD_NPT/result.ref
  tests/integrate/120_PW_KP_MD_NVT/INPUT
  tests/integrate/120_PW_KP_MD_NVT/KPT
  tests/integrate/120_PW_KP_MD_NVT/STRU
  tests/integrate/120_PW_KP_MD_NVT/jd
  tests/integrate/120_PW_KP_MD_NVT/result.ref
  tests/integrate/CASES
Labels: Feature

#2205 Build: enable icpx in Makefile build test & enable libxc in dynamic test
  .github/workflows/build_test_makefile.yml
  .github/workflows/dynamic.yml
Labels: Software Engineering

#2242 Fix: wrong rho in charge_extra.cpp
  source/module_elecstate/module_charge/charge.cpp
  source/module_elecstate/module_charge/charge.h
  source/module_elecstate/module_charge/charge_extra.cpp
Labels: Bug

#2203 Refactor: Use a unified function to output charge density and potential in real space.
  docs/advanced/elec_properties/potential.md
  docs/advanced/input_files/input-main.md
  examples/electrostatic_potential/README
  source/Makefile.Objects
  source/module_elecstate/potentials/potential_new.h
  source/module_elecstate/potentials/write_pot.cpp
  source/module_elecstate/test/CMakeLists.txt
  source/module_esolver/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/CMakeLists.txt
  source/module_io/cube_io.h
  source/module_io/read_cube.cpp
  source/module_io/read_rho.cpp
  source/module_io/test_serial/CMakeLists.txt
  source/module_io/write_cube.cpp
  source/module_io/write_rho.cpp
  tests/integrate/201_NO_15_f_pseudopots/refElecStaticPot
  tests/integrate/201_NO_15_f_pseudopots/refElecStaticPot.cube
  tests/integrate/201_NO_15_f_pseudopots/refElecStaticPot_AVE
  tests/integrate/201_NO_15_f_pseudopots/result.ref
  tests/integrate/tools/catch_properties.sh
  tools/average_pot/README
  tools/average_pot/aveElecStatPot.py
Labels: Refactor

#2322 Refactor: format all files in relax_old
  .clang-format
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_driver.h
  source/module_relax/relax_old/bfgs_basic.cpp
  source/module_relax/relax_old/bfgs_basic.h
  source/module_relax/relax_old/ions_move_basic.cpp
  source/module_relax/relax_old/ions_move_basic.h
  source/module_relax/relax_old/ions_move_bfgs.cpp
  source/module_relax/relax_old/ions_move_bfgs.h
  source/module_relax/relax_old/ions_move_cg.cpp
  source/module_relax/relax_old/ions_move_cg.h
  source/module_relax/relax_old/ions_move_methods.cpp
  source/module_relax/relax_old/ions_move_methods.h
  source/module_relax/relax_old/ions_move_sd.cpp
  source/module_relax/relax_old/ions_move_sd.h
  source/module_relax/relax_old/lattice_change_basic.h
  source/module_relax/relax_old/lattice_change_cg.cpp
  source/module_relax/relax_old/lattice_change_cg.h
  source/module_relax/relax_old/lattice_change_methods.cpp
  source/module_relax/relax_old/lattice_change_methods.h
  source/module_relax/relax_old/relax_old.cpp
  source/module_relax/relax_old/relax_old.h
Labels: Refactor

#2313 Refactor: rename files in module_md
  source/Makefile.Objects
  source/module_esolver/Makefile.Objects
  source/module_esolver/esolver.cpp
  source/module_io/input.h
  source/module_io/input_conv.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_md/CMakeLists.txt
  source/module_md/fire.cpp
  source/module_md/fire.h
  source/module_md/langevin.cpp
  source/module_md/langevin.h
  source/module_md/md_base.cpp
  source/module_md/md_base.h
  source/module_md/md_func.cpp
  source/module_md/md_func.h
  source/module_md/md_para.h
  source/module_md/msst.cpp
  source/module_md/msst.h
  source/module_md/nhchain.cpp
  source/module_md/nhchain.h
  source/module_md/run_md.cpp
  source/module_md/run_md.h
  source/module_md/test/CMakeLists.txt
  source/module_md/test/fire_test.cpp
  source/module_md/test/langevin_test.cpp
  source/module_md/test/lj_pot_test.cpp
  source/module_md/test/md_func_test.cpp
  source/module_md/test/msst_test.cpp
  source/module_md/test/nhchain_test.cpp
  source/module_md/verlet.cpp
  source/module_md/verlet.h
Labels: Refactor

#2315 Docs: add docs related to FIRE method
  docs/advanced/input_files/input-main.md
  docs/advanced/md.md
  examples/md/README
  examples/md/lcao_gammaonly_Sn64/README
Labels: Documentation

#2335 Refactor: delete GlobalC in module_relax/relax_old
  source/module_io/input_conv.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/test/input_conv_test.cpp
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_old/bfgs_basic.cpp
  source/module_relax/relax_old/bfgs_basic.h
  source/module_relax/relax_old/ions_move_basic.cpp
  source/module_relax/relax_old/ions_move_basic.h
  source/module_relax/relax_old/ions_move_bfgs.cpp
  source/module_relax/relax_old/ions_move_bfgs.h
  source/module_relax/relax_old/ions_move_cg.cpp
  source/module_relax/relax_old/ions_move_cg.h
  source/module_relax/relax_old/ions_move_methods.cpp
  source/module_relax/relax_old/ions_move_methods.h
  source/module_relax/relax_old/ions_move_sd.cpp
  source/module_relax/relax_old/ions_move_sd.h
  source/module_relax/relax_old/lattice_change_basic.cpp
  source/module_relax/relax_old/lattice_change_basic.h
  source/module_relax/relax_old/lattice_change_cg.cpp
  source/module_relax/relax_old/lattice_change_cg.h
  source/module_relax/relax_old/lattice_change_methods.cpp
  source/module_relax/relax_old/lattice_change_methods.h
  source/module_relax/relax_old/relax_old.cpp
  source/module_relax/relax_old/relax_old.h
Labels: Refactor

#2354 Feature: Implement Luo-Karasiev-Trickey (LKT) KEDF for OFDFT.
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_base/global_variable.cpp
  source/module_base/global_variable.h
  source/module_esolver/Makefile.Objects
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_hamilt_pw/hamilt_ofdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_ofdft/kedf_lkt.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_lkt.h
  source/module_hamilt_pw/hamilt_ofdft/kedf_tf.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_tf.h
  source/module_hamilt_pw/hamilt_ofdft/kedf_vw.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_vw.h
  source/module_hamilt_pw/hamilt_ofdft/kedf_wt.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_wt.h
  source/module_hamilt_pw/hamilt_ofdft/of_stress_pw.cpp
  source/module_hamilt_pw/hamilt_ofdft/of_stress_pw.h
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/input_conv.cpp
  source/module_io/test/input_conv_test.cpp
  source/module_io/test/input_test.cpp
  source/module_io/test/input_test_para.cpp
  source/module_io/test/write_input_test.cpp
  source/module_io/write_input.cpp
  tests/integrate/902_OF_KE_LKT/INPUT
  tests/integrate/902_OF_KE_LKT/KPT
  tests/integrate/902_OF_KE_LKT/STRU
  tests/integrate/902_OF_KE_LKT/jd
  tests/integrate/902_OF_KE_LKT/result.ref
  tests/integrate/CASES
Labels: Feature
