Repository deepmodeling/abacus-develop, pull requests merged in 2024-12, with the labels that each got.

#5653 Refactor: format wf_atomic files
  source/module_psi/wavefunc.cpp
  source/module_psi/wf_atomic.cpp
  source/module_psi/wf_atomic.h
Labels: Refactor

#5642 Refactor: replaced the original atomlink data structure with the Standard Template Library
  source/Makefile.Objects
  source/module_cell/module_neighbor/CMakeLists.txt
  source/module_cell/module_neighbor/sltk_adjacent_set.cpp
  source/module_cell/module_neighbor/sltk_adjacent_set.h
  source/module_cell/module_neighbor/sltk_atom.cpp
  source/module_cell/module_neighbor/sltk_atom.h
  source/module_cell/module_neighbor/sltk_atom_arrange.cpp
  source/module_cell/module_neighbor/sltk_atom_input.cpp
  source/module_cell/module_neighbor/sltk_atom_input.h
  source/module_cell/module_neighbor/sltk_grid.cpp
  source/module_cell/module_neighbor/sltk_grid.h
  source/module_cell/module_neighbor/sltk_grid_driver.cpp
  source/module_cell/module_neighbor/sltk_grid_driver.h
  source/module_cell/module_neighbor/test/CMakeLists.txt
  source/module_cell/module_neighbor/test/sltk_adjacent_set_test.cpp
  source/module_cell/module_neighbor/test/sltk_atom_input_test.cpp
  source/module_cell/module_neighbor/test/sltk_atom_test.cpp
  source/module_cell/module_neighbor/test/sltk_grid_test.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_io/cal_r_overlap_R.cpp
  source/module_io/to_wannier90_lcao.cpp
  source/module_md/test/CMakeLists.txt
Labels: Refactor

#5657 Refactor:Remove GloblaC::ucell in module_hsolver
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_lcaopw.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/test/test_hsolver_pw.cpp
Labels: The Absolute Zero

#5664 Refactor: remove GlobalC::Grid_D in hamilt_lcao
  source/module_cell/module_neighbor/sltk_grid.h
  source/module_cell/module_neighbor/sltk_grid_driver.h
  source/module_esolver/cell_dependency.h
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/record_adj.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/record_adj.h
Labels: The Absolute Zero

#5668 Refactor:Remove GlobalC::ucell in module_relax
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_new/relax.cpp
  source/module_relax/relax_new/relax.h
  source/module_relax/relax_new/test/relax_test.cpp
Labels: The Absolute Zero, GeometryRelaxation

#5658 Refactor:Remove GlobalC::ucell in module_pwdft
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/test/elecstate_pw_test.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_pw/hamilt_ofdft/of_stress_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VL_in_pw.h
  source/module_hamilt_pw/hamilt_pwdft/VNL_grad_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.h
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/hamilt_lcaopw.h
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/ekinetic_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/force_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/meta_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/vnl_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/wf_op.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/nonlocal_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/velocity_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_ewa.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_gga.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_har.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_loc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_mgga.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.h
  source/module_hamilt_pw/hamilt_stodft/sto_forces.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.h
  source/module_hamilt_pw/hamilt_stodft/sto_stress_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/test/test_hamilt_sto.cpp
  source/module_hamilt_pw/hamilt_stodft/test/test_sto_tool.cpp
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/diago_bpcg_test.cpp
  source/module_hsolver/test/diago_cg_float_test.cpp
  source/module_hsolver/test/diago_cg_test.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/diago_mock.h
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: The Absolute Zero

#5673 Refactor: Remove the functions about pseudopotential from Unitcell.
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/read_cell_pseudopots.cpp
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_para.cpp
  source/module_cell/test/unitcell_test_readpp.cpp
  source/module_cell/test_pw/CMakeLists.txt
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/read_pseudo.cpp
  source/module_elecstate/read_pseudo.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_gets.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp
  source/module_hamilt_lcao/module_deepks/test/Makefile
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_io/test/write_orb_info_test.cpp
  source/module_md/test/CMakeLists.txt
Labels: The Absolute Zero

#5656 Update bfgs.cpp
  source/module_relax/relax_old/bfgs.cpp
Labels: Refactor

#5683 Fix: init_mixing before `beforescf`
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  tests/integrate/384_NO_GO_S1_HSE_loop0_PU/result.ref
Labels: Bugs

#5654 Fix the overwriting between xc kernel components
  source/module_lr/potentials/xc_kernel.cpp
  tests/integrate/291_NO_KP_LR/result.ref
  tests/integrate/391_NO_GO_LR/result.ref
  tests/integrate/393_NO_GO_ULR_HF/INPUT
  tests/integrate/393_NO_GO_ULR_HF/result.ref
Labels: Refactor

#5625 refactor: move parallel_2d to module_base
  CMakeLists.txt
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_base/parallel_2d.cpp
  source/module_base/parallel_2d.h
  source/module_base/test_parallel/CMakeLists.txt
  source/module_base/test_parallel/parallel_2d_test.cpp
  source/module_base/test_parallel/parallel_2d_test.sh
  source/module_basis/module_ao/CMakeLists.txt
  source/module_basis/module_ao/parallel_orbitals.h
  source/module_basis/module_ao/test/CMakeLists.txt
  source/module_elecstate/module_dm/test/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/CMakeLists.txt
  source/module_hamilt_lcao/module_deltaspin/test/CMakeLists.txt
  source/module_hamilt_lcao/module_hcontainer/test/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/test/CMakeLists.txt
  source/module_hsolver/parallel_k2d.h
  source/module_hsolver/test/CMakeLists.txt
  source/module_io/io_dmk.cpp
  source/module_io/io_dmk.h
  source/module_io/read_wfc_lcao.h
  source/module_io/test/CMakeLists.txt
  source/module_io/test/io_dmk_test.cpp
  source/module_io/test/read_wfc_nao_test.cpp
  source/module_io/test/support/SPIN1_DM
  source/module_io/test/support/WFC_NAO_GAMMA2.txt
  source/module_io/test_serial/CMakeLists.txt
  source/module_io/test_serial/io_dmk_test.cpp
  source/module_io/write_wfc_nao.cpp
  source/module_lr/AX/AX.h
  source/module_lr/AX/test/CMakeLists.txt
  source/module_lr/dm_trans/dm_trans.h
  source/module_lr/dm_trans/test/CMakeLists.txt
  source/module_lr/utils/lr_util.h
  source/module_lr/utils/test/CMakeLists.txt
  source/module_rdmft/rdmft.h
  source/module_rdmft/rdmft_tools.h
  source/module_ri/module_exx_symmetry/test/CMakeLists.txt
Labels: Refactor

#5694 Refactor: Remove `cal_nelec` and `cal_nbands` from `unitcell.cpp`.
  source/Makefile.Objects
  source/module_cell/cal_atoms_info.h
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/unitcell_test_readpp.cpp
  source/module_cell/test_pw/CMakeLists.txt
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/cal_nelec_nband.cpp
  source/module_elecstate/cal_nelec_nband.h
  source/module_elecstate/read_pseudo.cpp
  source/module_elecstate/read_pseudo.h
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_md/test/CMakeLists.txt
Labels: The Absolute Zero

#5692 Refacor: change the order of k-point parallel and band parallel.
  source/module_base/global_variable.h
  source/module_base/parallel_comm.cpp
  source/module_base/parallel_comm.h
  source/module_base/parallel_global.cpp
  source/module_base/parallel_global.h
  source/module_base/test_parallel/parallel_global_test.cpp
  source/module_elecstate/module_charge/charge_mpi.cpp
  source/module_elecstate/test_mpi/charge_mpi_test.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_wf.cpp
Labels: Refactor

#5689 Refactor: remove spin_now in Gint_k
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.cpp
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_rdmft/rdmft_tools.cpp
  source/module_rdmft/update_state_rdmft.cpp
Labels: Refactor

#5701 update exx code format
  source/module_ri/Exx_LRI.hpp
  source/module_ri/LRI_CV.hpp
Labels: Refactor

#5697 Refactor: add smooth threshold support for `david` method
  python/pyabacus/src/hsolver/py_diago_dav_subspace.hpp
  python/pyabacus/src/hsolver/py_diago_david.hpp
  python/pyabacus/src/hsolver/py_hsolver.cpp
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_lr/hsolver_lrtd.hpp
Labels: Refactor, Diago

#5702 rename Conv_Coulomb_Pot_K::Ccp_Type
  source/module_io/input_conv.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_ri/Exx_LRI.hpp
  source/module_ri/conv_coulomb_pot_k.cpp
  source/module_ri/conv_coulomb_pot_k.h
  source/module_ri/exx_lip.hpp
Labels: Refactor

#5712 Feature: GGA XC kernel for LR-TDDFT at nspin=2
  source/module_lr/potentials/pot_hxc_lrtd.cpp
  source/module_lr/potentials/xc_kernel.cpp
  source/module_lr/potentials/xc_kernel.h
  tests/integrate/391_NO_GO_LR_PBE/INPUT
  tests/integrate/391_NO_GO_LR_PBE/STRU
  tests/integrate/391_NO_GO_LR_PBE/jd
  tests/integrate/391_NO_GO_LR_PBE/result.ref
  tests/integrate/CASES_CPU.txt
Labels: EXX and lr-TDDFT

#5713 Refactor: add smooth threshold support for cg method
  python/pyabacus/src/hsolver/py_diago_cg.hpp
  python/pyabacus/src/hsolver/py_hsolver.cpp
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
  source/module_hsolver/diago_cg.cpp
  source/module_hsolver/diago_cg.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/test/diago_cg_float_test.cpp
  source/module_hsolver/test/diago_cg_real_test.cpp
  source/module_hsolver/test/diago_cg_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_lr/hsolver_lrtd.hpp
Labels: The Absolute Zero

#5718 Fix: add check for smearing_method
  source/module_io/read_input_item_elec_stru.cpp
  source/module_io/test_serial/read_input_item_test.cpp
Labels: Input&Output, Refactor

#5721 Fix: Fix the Ewald force and stress when atom number of some elements are zero.
  source/module_cell/atom_spec.cpp
  source/module_cell/read_atoms.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_ewa.cpp
  tests/integrate/123_PW_zero_atom/INPUT
  tests/integrate/123_PW_zero_atom/KPT
  tests/integrate/123_PW_zero_atom/STRU
  tests/integrate/123_PW_zero_atom/jd
  tests/integrate/123_PW_zero_atom/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs, Refactor

#5717 Refactor: Combine gamma-only and multi-k versions of some functions in DeePKS.
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_odelta.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/cal_gdmx.cpp
  source/module_hamilt_lcao/module_deepks/cal_gdmx_k.cpp
  source/module_hamilt_lcao/module_deepks/deepks_hmat.cpp
  source/module_hamilt_lcao/module_deepks/deepks_hmat.h
  source/module_hamilt_lcao/module_deepks/orbital_precalc.cpp
  source/module_hamilt_lcao/module_deepks/orbital_precalc_k.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/v_delta_precalc.cpp
  source/module_hamilt_lcao/module_deepks/v_delta_precalc_k.cpp
Labels: The Absolute Zero

#5720 Refactor: remove GlobalC::GridD
  source/module_base/tool_title.cpp
  source/module_cell/module_neighbor/sltk_atom_arrange.cpp
  source/module_cell/module_neighbor/sltk_atom_arrange.h
  source/module_cell/module_neighbor/sltk_grid.cpp
  source/module_cell/module_neighbor/sltk_grid.h
  source/module_cell/module_neighbor/sltk_grid_driver.cpp
  source/module_cell/module_neighbor/sltk_grid_driver.h
  source/module_cell/module_neighbor/test/sltk_atom_arrange_test.cpp
  source/module_cell/module_neighbor/test/sltk_grid_test.cpp
  source/module_elecstate/module_dm/test/test_dm_R_init.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_lj.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/tmp_mocks.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_hamilt_lcao/module_dftu/dftu.h
  source/module_hamilt_lcao/module_dftu/dftu_folding.cpp
  source/module_hamilt_lcao/module_dftu/dftu_force.cpp
  source/module_io/berryphase.cpp
  source/module_io/berryphase.h
  source/module_io/cal_r_overlap_R.cpp
  source/module_io/cal_r_overlap_R.h
  source/module_io/output_mat_sparse.cpp
  source/module_io/output_mulliken.h
  source/module_io/td_current_io.cpp
  source/module_io/td_current_io.h
  source/module_io/to_wannier90_lcao.cpp
  source/module_io/to_wannier90_lcao.h
  source/module_io/unk_overlap_lcao.cpp
  source/module_io/unk_overlap_lcao.h
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/esolver_lrtd_lcao.h
  source/module_lr/operator_casida/operator_lr_hxc.cpp
  source/module_rdmft/rdmft.cpp
  source/module_rdmft/rdmft.h
  source/module_rdmft/rdmft_pot.cpp
  source/module_rdmft/update_state_rdmft.cpp
Labels: The Absolute Zero

#5727 Feature: Allow directly compiling CUDA version on DCU harware
  CMakeLists.txt
  source/module_base/module_device/device.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
Labels: GPU & DCU & HPC

#5729 Fix: update kinetic energy when all atoms are fixed
  source/module_md/md_func.cpp
Labels: Bugs

#5731 Refactor: Change some functions in module_deepks into template.
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_odelta.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/cal_gdmx.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fgamma.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fk.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
Labels: Refactor, The Absolute Zero

#5730 Refactor:remove GlobalC::ucell in module_elesctate
  source/module_cell/setup_nonlocal.cpp
  source/module_elecstate/elecstate.cpp
  source/module_elecstate/elecstate.h
  source/module_elecstate/elecstate_energy.cpp
  source/module_elecstate/elecstate_getters.cpp
  source/module_elecstate/elecstate_getters.h
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/elecstate_pw_cal_tau.cpp
  source/module_elecstate/magnetism.cpp
  source/module_elecstate/magnetism.h
  source/module_elecstate/module_charge/charge.cpp
  source/module_elecstate/module_charge/charge.h
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_elecstate/module_charge/charge_mixing.cpp
  source/module_elecstate/module_charge/charge_mixing.h
  source/module_elecstate/module_charge/charge_mixing_preconditioner.cpp
  source/module_elecstate/module_charge/charge_mixing_residual.cpp
  source/module_elecstate/potentials/H_TDDFT_pw.cpp
  source/module_elecstate/potentials/H_TDDFT_pw.h
  source/module_elecstate/test/charge_mixing_test.cpp
  source/module_elecstate/test/charge_test.cpp
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_elecstate/test/elecstate_magnetism_test.cpp
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_elecstate/test/elecstate_pw_test.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_rdmft/rdmft.cpp
Labels: The Absolute Zero

#5732 Feature: add smooth ethr for all iter methods
  docs/advanced/input_files/input-main.md
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_io/read_input_item_elec_stru.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test/support/INPUT
  source/module_parameter/input_parameter.h
  tests/integrate/104_PW_NC_magnetic/INPUT
  tests/integrate/140_PW_15_SO/INPUT
  tests/integrate/160_PW_DJ_PK_PU_SO/INPUT
Labels: Features Needed, The Absolute Zero

#5735 Refactor: remove GlobalC::solvent_model
  source/module_elecstate/elecstate_energy_terms.cpp
  source/module_elecstate/potentials/efield.cpp
  source/module_elecstate/potentials/efield.h
  source/module_elecstate/potentials/potential_new.cpp
  source/module_elecstate/potentials/potential_new.h
  source/module_elecstate/potentials/potential_types.cpp
  source/module_elecstate/test/potential_new_test.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_hamilt_general/module_surchem/cal_totn.cpp
  source/module_hamilt_general/module_surchem/cal_vcav.cpp
  source/module_hamilt_general/module_surchem/sol_force.cpp
  source/module_hamilt_general/module_surchem/surchem.cpp
  source/module_hamilt_general/module_surchem/surchem.h
  source/module_hamilt_general/module_surchem/test/setcell.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_io/write_eband_terms.hpp
  source/module_io/write_elecstat_pot.cpp
  source/module_io/write_elecstat_pot.h
  source/module_io/write_vxc.hpp
  source/module_io/write_vxc_lip.hpp
Labels: The Absolute Zero

#5736 Docs: move doxygen to headers for DiagoDavid class and add some new
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
Labels: The Absolute Zero

#5738 Fix: Segment Fault of PAW
  source/module_cell/atom_spec.cpp
  source/module_cell/atom_spec.h
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_cell/unitcell_data.h
  source/module_elecstate/module_dm/test/test_cal_dm_R.cpp
  source/module_elecstate/module_dm/test/test_cal_dmk_psi.cpp
  source/module_elecstate/module_dm/test/test_dm_R_init.cpp
  source/module_elecstate/module_dm/test/test_dm_constructor.cpp
  source/module_esolver/test/esolver_dp_test.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_T_NL_cd.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_dftu.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_ekineticnew.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_nonlocalnew.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_overlapnew.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_overlapnew_cd.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_func_folding.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_complex.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_output.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_time.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_transfer.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.h
  source/module_io/test/for_testing_input_conv.h
  source/module_lr/ri_benchmark/test/ri_benchmark_test.cpp
Labels: Bugs, Refactor

#5737 Refactor:Remove GlobalC::ucell
  source/driver.cpp
  source/driver.h
  source/driver_run.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/module_dftu/dftu.cpp
  source/module_hamilt_lcao/module_dftu/dftu.h
  source/module_hamilt_lcao/module_dftu/dftu_tools.cpp
  source/module_hamilt_pw/hamilt_ofdft/of_stress_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/global.h
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_stress_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_stress_pw.h
  source/module_io/input_conv.cpp
  source/module_rdmft/rdmft.h
  source/module_rdmft/rdmft_pot.cpp
  source/module_rdmft/update_state_rdmft.cpp
Labels: The Absolute Zero

#5740 Refactor: remove GlobalC::Pgrid
  source/module_elecstate/elecstate.cpp
  source/module_elecstate/elecstate.h
  source/module_elecstate/module_charge/charge.h
  source/module_elecstate/module_charge/charge_extra.cpp
  source/module_elecstate/module_charge/charge_extra.h
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_elecstate/potentials/pot_surchem.hpp
  source/module_elecstate/test/charge_extra_test.cpp
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_elecstate/test/elecstate_pw_test.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_general/module_surchem/H_correction_pw.cpp
  source/module_hamilt_general/module_surchem/cal_pseudo.cpp
  source/module_hamilt_general/module_surchem/surchem.h
  source/module_hamilt_general/module_surchem/test/cal_pseudo_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/global.cpp
  source/module_hamilt_pw/hamilt_pwdft/global.h
  source/module_hamilt_pw/hamilt_pwdft/structure_factor.cpp
  source/module_hamilt_pw/hamilt_pwdft/structure_factor.h
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_io/get_pchg_lcao.cpp
  source/module_io/get_pchg_lcao.h
  source/module_io/get_pchg_pw.h
  source/module_io/get_wf_lcao.cpp
  source/module_io/get_wf_lcao.h
  source/module_io/write_elecstat_pot.cpp
  source/module_io/write_elf.cpp
  source/module_io/write_elf.h
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_psi/test/psi_initializer_unit_test.cpp
  source/module_relax/relax_new/test/relax_test.h
Labels: The Absolute Zero

#5759 Refactor: refactor neighbour atom search but no change on algo
  source/Makefile.Objects
  source/module_cell/module_neighbor/CMakeLists.txt
  source/module_cell/module_neighbor/sltk_atom.cpp
  source/module_cell/module_neighbor/sltk_atom.h
  source/module_cell/module_neighbor/sltk_atom_arrange.cpp
  source/module_cell/module_neighbor/sltk_atom_arrange.h
  source/module_cell/module_neighbor/sltk_atom_input.cpp
  source/module_cell/module_neighbor/sltk_atom_input.h
  source/module_cell/module_neighbor/sltk_grid.cpp
  source/module_cell/module_neighbor/sltk_grid.h
  source/module_cell/module_neighbor/sltk_grid_driver.cpp
  source/module_cell/module_neighbor/sltk_grid_driver.h
  source/module_cell/module_neighbor/test/CMakeLists.txt
  source/module_cell/module_neighbor/test/sltk_atom_arrange_test.cpp
  source/module_cell/module_neighbor/test/sltk_atom_input_test.cpp
  source/module_cell/module_neighbor/test/sltk_atom_test.cpp
  source/module_cell/module_neighbor/test/sltk_grid_test.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_io/cal_r_overlap_R.cpp
  source/module_io/to_wannier90_lcao.cpp
  source/module_md/test/CMakeLists.txt
Labels: Features Needed, Refactor

#5758 Docs: update the docs of `exx_ccp_rmesh_times` and `exx_real_number`
  docs/advanced/input_files/input-main.md
Labels: Compile & CICD & Docs & Dependencies

#5752 Feature: enable cal_force and cal_stress in nscf
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/elecstate_pw.h
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_hsolver/test/test_hsolver_sdft.cpp
  source/module_io/read_input_item_system.cpp
  source/module_relax/relax_driver.cpp
Labels: The Absolute Zero

#5745 Refactor: remove the Psi Constructors using `int* ngk_in`
  source/module_hamilt_general/operator.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/test/diago_cg_float_test.cpp
  source/module_hsolver/test/diago_cg_real_test.cpp
  source/module_hsolver/test/diago_cg_test.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_io/get_wf_lcao.cpp
  source/module_io/test/write_wfc_nao_test.cpp
  source/module_lr/utils/lr_util.hpp
  source/module_psi/psi.cpp
  source/module_psi/psi.h
  source/module_psi/test/psi_test.cpp
Labels: The Absolute Zero

#5763 Fix: Segment fault in GPU-Davidson
  source/module_hsolver/kernels/cuda/math_kernel_op.cu
Labels: Bugs, Refactor

#5760 Feature: LR-TDDFT absorption spectrum in velocity gauge
  examples/lr-tddft/lcao_H2O/INPUT
  examples/lr-tddft/lcao_Si2/INPUT
  source/Makefile.Objects
  source/module_basis/module_nao/two_center_bundle.h
  source/module_io/read_input_item_tddft.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_lr/CMakeLists.txt
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/lr_spectrum.cpp
  source/module_lr/lr_spectrum.h
  source/module_lr/lr_spectrum_velocity.cpp
  source/module_lr/utils/lr_util.cpp
  source/module_lr/utils/lr_util.h
  source/module_lr/utils/lr_util_hcontainer.h
  source/module_parameter/input_parameter.h
Labels: EXX and lr-TDDFT

#5766 Refactor: Replace `nlm_save` in DeePKS by HContainer object `phialpha`.
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_phialpha.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_psialpha.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/cal_gdmx.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fgamma.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fk.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.h
  source/module_hamilt_lcao/module_deepks/orbital_precalc.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp
  source/module_hamilt_lcao/module_deepks/v_delta_precalc.cpp
  source/module_hamilt_lcao/module_hcontainer/atom_pair.cpp
  source/module_hamilt_lcao/module_hcontainer/base_matrix.cpp
  source/module_hamilt_lcao/module_hcontainer/base_matrix.h
  source/module_io/read_input_item_deepks.cpp
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/result.ref
  tests/deepks/602_NO_deepks_d_H2O_scf_lda2pbe/result.ref
  tests/deepks/603_NO_deepks_H2O_v_delta_2/result.ref
  tests/integrate/tools/catch_properties.sh
Labels: The Absolute Zero, DeePKS

#5772 Fix stru
  source/module_cell/read_atoms.cpp
Labels: Bugs, Refactor

#5765 Fix: enable ecutrho/ecutwfc > 4 for ncpp
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/elecstate_pw.h
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  tests/integrate/101_PW_upf201_Al_pseudopots/INPUT
  tests/integrate/101_PW_upf201_Al_pseudopots/README
  tests/integrate/101_PW_upf201_Al_pseudopots/jd
  tests/integrate/101_PW_upf201_Al_pseudopots/result.ref
  tests/integrate/101_PW_upf201_uspp_ncpp/INPUT
  tests/integrate/101_PW_upf201_uspp_ncpp/KPT
  tests/integrate/101_PW_upf201_uspp_ncpp/STRU
  tests/integrate/101_PW_upf201_uspp_ncpp/jd
  tests/integrate/101_PW_upf201_uspp_ncpp/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs, Refactor

#5767 Refactor:Move the relaxation part of the ucell function
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/prepare_unitcell.h
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_setupcell.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_cell/unitcell_data.h
  source/module_cell/update_cell.cpp
  source/module_cell/update_cell.h
  source/module_md/msst.cpp
  source/module_md/nhchain.cpp
  source/module_md/test/CMakeLists.txt
  source/module_relax/relax_new/relax.cpp
  source/module_relax/relax_new/test/CMakeLists.txt
  source/module_relax/relax_new/test/relax_test.cpp
  source/module_relax/relax_new/test/relax_test.h
  source/module_relax/relax_old/relax_old.cpp
Labels: The Absolute Zero

#5778 Refactor: Remove global dependence of some functions in DeePKS.
  source/Makefile.Objects
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_odelta.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.h
  source/module_hamilt_lcao/module_deepks/deepks_orbital.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbital.h
  source/module_hamilt_lcao/module_deepks/orbital_precalc.cpp
Labels: The Absolute Zero, DeePKS

#5781 Fix: Reopen UT in HContainer output.
  source/module_base/parallel_2d.cpp
  source/module_base/parallel_2d.h
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/test/CMakeLists.txt
Labels: Bugs, Refactor
