Repository deepmodeling/abacus-develop, pull requests merged in 2024-10, with the labels that each got.

#5201 Refactor:Change the variable type.
  source/module_parameter/input_parameter.h
Labels: Bugs (Exclude input and output)

#5202 Refactor hpsi_func in hsolver
  python/pyabacus/src/py_diago_dav_subspace.hpp
  python/pyabacus/src/py_diago_david.hpp
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_lr/hsolver_lrtd.cpp
Labels: The Absolute Zero

#5210 Fix: fix a deadlock bug in CUDA version of gint
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
Labels: Bugs (Exclude input and output)

#5140 Feature: Support outputting real space wave functions in Gaussian CUBE format
  source/module_esolver/lcao_others.cpp
  source/module_io/get_pchg_lcao.cpp
  source/module_io/get_pchg_lcao.h
  source/module_io/get_wf_lcao.cpp
  source/module_io/get_wf_lcao.h
  source/module_io/read_input_item_output.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/write_wfc_r.cpp
  source/module_parameter/input_parameter.h
  tests/integrate/312_NO_GO_wfc_ienvelope/result.ref
Labels: Features Needed

#5208 Fix memory bug in XC_Functional_Libxc::cal_gdr()
  source/module_hamilt_general/module_xc/xc_functional_libxc.h
  source/module_hamilt_general/module_xc/xc_functional_libxc_tools.cpp
  source/module_hamilt_general/module_xc/xc_functional_libxc_vxc.cpp
Labels: Bugs (Exclude input and output)

#5205 Change wrapper `spsi_func` in hsolver-dav
  python/pyabacus/src/py_diago_david.hpp
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_lr/hsolver_lrtd.cpp
Labels: The Absolute Zero

#5215 Fix: md restart can not read STRU
  source/driver.cpp
  source/module_esolver/esolver.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_io/output_log.cpp
  source/module_io/output_log.h
  source/module_io/print_info.cpp
  source/module_io/print_info.h
  source/module_io/read_input_item_system.cpp
  source/module_io/read_set_globalv.cpp
  source/module_io/test/outputlog_test.cpp
  source/module_io/test/print_info_test.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_md/md_base.cpp
  source/module_md/run_md.cpp
  source/module_relax/relax_driver.cpp
  tests/integrate/701_LJ_MD_NVE/INPUT
  tests/integrate/701_LJ_MD_NVE/Restart_md.dat
  tests/integrate/701_LJ_MD_NVE/STRU
  tests/integrate/701_LJ_MD_NVE/STRU_MD_155
  tests/integrate/701_LJ_MD_NVE/result.ref
  tests/integrate/701_LJ_MD_rescale_v/INPUT
  tests/integrate/701_LJ_MD_rescale_v/OUT.autotest/Restart_md.dat
  tests/integrate/701_LJ_MD_rescale_v/OUT.autotest/STRU/STRU_MD_10
  tests/integrate/701_LJ_MD_rescale_v/STRU
  tests/integrate/701_LJ_MD_rescale_v/result.ref
Labels: The Absolute Zero

#5218 Docs: update default behaviors on building built-in libm
  docs/advanced/install.md
Labels: Compile & CICD & Docs

#5219 CI: Align test commands for coverage tests
  .github/workflows/coverage.yml
Labels: Compile & CICD & Docs

#5222 CI: add back missing command for codecov
  .github/workflows/coverage.yml
Labels: Compile & CICD & Docs

#5223 toolchain bug fix
  toolchain/build_abacus_gnu.sh
  toolchain/build_abacus_intel-mpich.sh
  toolchain/build_abacus_intel.sh
  toolchain/scripts/stage3/install_elpa.sh
Labels: Compile & CICD & Docs

#5238 Fix: TDDFT now can use `ks_solver=cusolver`, and velocity gauge is able to use Heaviside external field
  source/module_elecstate/elecstate_lcao_tddft.cpp
  source/module_elecstate/potentials/H_TDDFT_pw.cpp
Labels: Bugs (Exclude input and output)

#5233 Toolchain fix stage4
  toolchain/build_abacus_gnu.sh
  toolchain/build_abacus_intel-mpich.sh
  toolchain/build_abacus_intel.sh
  toolchain/scripts/stage4/install_libtorch.sh
Labels: Compile & CICD & Docs

#5199 Feature: update new version of dav_subspace with higher performance
  docs/advanced/input_files/input-main.md
  examples/lr-tddft/lcao_Si2/INPUT
  python/pyabacus/src/py_diago_dav_subspace.hpp
  python/pyabacus/src/py_hsolver.cpp
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
  source/module_elecstate/elecstate.cpp
  source/module_elecstate/elecstate.h
  source/module_elecstate/potentials/pot_local.cpp
  source/module_elecstate/potentials/pot_local.h
  source/module_elecstate/potentials/potential_new.h
  source/module_elecstate/potentials/potential_types.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/pw_fun.cpp
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
  source/module_io/read_input_item_system.cpp
  source/module_lr/hsolver_lrtd.cpp
  source/module_parameter/input_parameter.h
  tests/integrate/102_PW_DS_davsubspace/INPUT
Labels: Performance

#5239 Remove Base class DiagH in LCAO code
  source/module_hsolver/diago_cusolver.h
  source/module_hsolver/diago_cusolvermp.h
  source/module_hsolver/diago_elpa.h
  source/module_hsolver/diago_elpa_native.h
  source/module_hsolver/diago_lapack.h
  source/module_hsolver/diago_scalapack.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/test/diago_lapack_test.cpp
  source/module_hsolver/test/diago_lcao_cusolver_test.cpp
  source/module_hsolver/test/diago_lcao_test.cpp
Labels: The Absolute Zero

#5224 Refactor class `DensityMatrix`: remove the dependence on `K_Vectors` and the ambiguity of `_nks`
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/module_dm/density_matrix.cpp
  source/module_elecstate/module_dm/density_matrix.h
  source/module_elecstate/module_dm/test/test_cal_dm_R.cpp
  source/module_elecstate/module_dm/test/test_dm_R_init.cpp
  source/module_elecstate/module_dm/test/test_dm_constructor.cpp
  source/module_elecstate/module_dm/test/test_dm_io.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/edm.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_io/get_pchg_lcao.cpp
  source/module_io/get_pchg_lcao.h
  source/module_io/td_current_io.cpp
  source/module_lr/dm_trans/dmr_complex.cpp
  source/module_lr/hamilt_casida.h
  source/module_lr/lr_spectrum.cpp
  source/module_lr/lr_spectrum.h
  source/module_lr/operator_casida/operator_lr_hxc.cpp
  source/module_lr/operator_casida/operator_lr_hxc.h
Labels: Refactor

#5259 Remove DiagH of lcao PEXSI
  source/module_hsolver/diago_cusolvermp.h
  source/module_hsolver/diago_pexsi.h
Labels: The Absolute Zero

#5257 Refactor: refactor `solve` func in `hsolver-lcao` class
  source/module_hsolver/hsolver_lcao.cpp
Labels: The Absolute Zero

#5258 Fix: remove unnecessary gpu memory allocation under LCAO basis
  source/module_elecstate/potentials/potential_new.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_hamilt_pw/hamilt_pwdft/structure_factor.cpp
  source/module_hamilt_pw/hamilt_pwdft/structure_factor.h
Labels: GPU & DCU & HPC

#5242 Refactor: Seperate BLAS functions' declaration and implementation, and add a device_type flag for blas kernels
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_base/blas_connector.cpp
  source/module_base/blas_connector.h
  source/module_base/test/CMakeLists.txt
  source/module_basis/module_ao/test/CMakeLists.txt
  source/module_basis/module_pw/kernels/test/CMakeLists.txt
  source/module_basis/module_pw/test/CMakeLists.txt
  source/module_hamilt_general/module_xc/test/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt
  source/module_hsolver/kernels/test/CMakeLists.txt
  source/module_md/test/CMakeLists.txt
  source/module_relax/relax_new/test/CMakeLists.txt
Labels: Features Needed

#5284 Test: fix some incorrect INPUT files
  tests/integrate/933_NO_H_dzp_ns2_GPU/INPUT
  tests/integrate/935_NO_Si2_tzdp_ns2_k_GPU/INPUT
Labels: GPU & DCU & HPC

#5294 Doc&Test: update the documentation about pseudopotential and orbitals
  docs/advanced/pp_orb.md
  docs/conf.py
  source/module_io/test/to_qo_test.cpp
  source/module_io/to_qo.h
  source/module_io/to_qo_mpi.cpp
  source/module_io/to_qo_structures.cpp
Labels: Compile & CICD & Docs & Dependencies

#5246 Refactor: Use memory_op to set diag_const_nums
  source/module_hsolver/diag_const_nums.cpp
  source/module_hsolver/diag_const_nums.h
  source/module_hsolver/diago_dav_subspace.cpp
Labels: GPU & DCU & HPC

#5293 Modify the berry phase document.
  docs/advanced/elec_properties/Berry_phase.md
  examples/berryphase/lcao_PbTiO3/INPUT-nscf-a
  examples/berryphase/lcao_PbTiO3/INPUT-nscf-b
  examples/berryphase/lcao_PbTiO3/INPUT-nscf-c
  examples/berryphase/pw_PbTiO3/INPUT-nscf-a
  examples/berryphase/pw_PbTiO3/INPUT-nscf-b
  examples/berryphase/pw_PbTiO3/INPUT-nscf-c
  source/module_io/read_input_item_postprocess.cpp
Labels: Compile & CICD & Docs & Dependencies

#5292 Becke's partition for multi-center grid integration
  source/module_base/grid/partition.cpp
  source/module_base/grid/partition.h
  source/module_base/grid/radial.cpp
  source/module_base/grid/test/CMakeLists.txt
  source/module_base/grid/test/test_delley.cpp
  source/module_base/grid/test/test_partition.cpp
Labels: Features Needed

#5303 Fix a segfault in rhog_symmetry
  source/module_cell/module_symmetry/symmetry.cpp
Labels: Symmetry

#5305 Fix: nupdown = 0 for spin-unpolarized calculation
  source/module_io/read_input_item_elec_stru.cpp
Labels: Bugs (Exclude input and output)

#5212 Refactor XC_Functional_Libxc::convert_vtxc_v()
  source/module_hamilt_general/module_xc/xc_functional_libxc.h
  source/module_hamilt_general/module_xc/xc_functional_libxc_tools.cpp
  source/module_hamilt_general/module_xc/xc_functional_libxc_vxc.cpp
Labels: Refactor

#5323 Refactor: remove `read_rho` and make `read_cube` independent of `esolver_type`
  source/Makefile.Objects
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_esolver/cal_edm_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/lcao_gets.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/pw_fun.cpp
  source/module_esolver/pw_init_after_vc.cpp
  source/module_esolver/pw_init_globalc.cpp
  source/module_esolver/pw_nscf.cpp
  source/module_esolver/pw_others.cpp
  source/module_esolver/set_matrix_grid.cpp
  source/module_io/CMakeLists.txt
  source/module_io/cube_io.h
  source/module_io/read_cube.cpp
  source/module_io/read_rho.cpp
  source/module_io/rho_io.h
  source/module_io/test_serial/CMakeLists.txt
  source/module_io/test_serial/rho_io_test.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
Labels: The Absolute Zero

#5281 Add number of threads output in stdout
  source/main.cpp
  source/module_base/parallel_global.cpp
  source/module_base/parallel_global.h
  source/module_cell/module_symmetry/run_symmetry.cpp
  source/module_io/print_info.cpp
  source/module_parameter/parameter.cpp
  source/module_parameter/parameter.h
  source/module_parameter/system_parameter.h
  tools/SIAB/SimulatedAnnealing/backup_old_version/1_Source/src_parallel/parallel_global.cpp
  tools/SIAB/SimulatedAnnealing/backup_old_version/1_Source/src_parallel/parallel_global.h
  tools/SIAB/SimulatedAnnealing/backup_old_version/1_Source/src_spillage/main.cpp
  tools/SIAB/SimulatedAnnealing/source/src_parallel/parallel_global.cpp
  tools/SIAB/SimulatedAnnealing/source/src_parallel/parallel_global.h
  tools/SIAB/SimulatedAnnealing/source/src_spillage/main.cpp
Labels: Refactor

#5298 Refactor: replace sto_hchi by HamiltSdftPW::hPsi
  source/Makefile.Objects
  source/module_base/math_chebyshev.cpp
  source/module_base/math_chebyshev.h
  source/module_base/test/math_chebyshev_test.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_hamilt_general/operator.cpp
  source/module_hamilt_general/operator.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/ekinetic_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/ekinetic_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/ekinetic_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/ekinetic_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/ekinetic_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/ekinetic_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/ekinetic_pw.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/meta_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/meta_pw.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/nonlocal_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/nonlocal_pw.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/veff_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/veff_pw.h
  source/module_hamilt_pw/hamilt_stodft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.h
  source/module_hamilt_pw/hamilt_stodft/sto_dos.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_dos.h
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.h
  source/module_hamilt_pw/hamilt_stodft/sto_hchi.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_hchi.h
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.h
  source/module_hamilt_pw/hamilt_stodft/sto_tool.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_tool.h
  source/module_hamilt_pw/hamilt_stodft/test/CMakeLists.txt
  source/module_hamilt_pw/hamilt_stodft/test/test_hamilt_sto.cpp
  source/module_hamilt_pw/hamilt_stodft/test/test_sto_tool.cpp
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/diago_mock.h
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: Performance

#5307 Remove DiagH class in hsolver
  source/module_hsolver/diagh.h
  source/module_hsolver/diago_bpcg.h
  source/module_hsolver/diago_cg.cpp
  source/module_hsolver/diago_cg.h
  source/module_hsolver/diago_cusolver.h
  source/module_hsolver/diago_cusolvermp.h
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/diago_elpa.h
  source/module_hsolver/diago_elpa_native.h
  source/module_hsolver/diago_lapack.h
  source/module_hsolver/diago_pexsi.h
  source/module_hsolver/diago_scalapack.h
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/test/diago_lapack_test.cpp
  source/module_hsolver/test/diago_lcao_test.cpp
Labels: The Absolute Zero

#5301 Feature: Porting abacus to DSP hardware (mtblas part)
  CMakeLists.txt
  install_dsp.sh
  source/module_base/blas_connector.cpp
  source/module_base/kernels/dsp/dsp_connector.h
  source/module_base/module_device/memory_op.cpp
  source/module_base/module_device/types.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/kernels/math_kernel_op.cpp
  source/module_hsolver/kernels/math_kernel_op.h
Labels: GPU & DCU & HPC

#5322 Fix::Change the gamma_only_lcao when nspin=4
  source/module_io/read_input_item_elec_stru.cpp
  source/module_io/read_set_globalv.cpp
  source/module_io/test_serial/read_input_item_test.cpp
Labels: Refactor

#5327 Performance: change the position of open mp
  source/module_hamilt_pw/hamilt_pwdft/kernels/ekinetic_op.cpp
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.cpp
Labels: Performance

#4874 Fix: boost Davidson by removal of useless scc
  source/module_hsolver/diago_david.cpp
Labels: The Absolute Zero

#5332 Remove diagh.h in module_hsolver
  source/module_hsolver/diagh.h
Labels: The Absolute Zero

#5247 Feature: Add Cell for pyabacus
  python/pyabacus/pyproject.toml
  python/pyabacus/src/pyabacus/__init__.py
  python/pyabacus/src/pyabacus/cell.py
  python/pyabacus/src/pyabacus/io/__init__.py
  python/pyabacus/src/pyabacus/io/stru.py
  python/pyabacus/src/pyabacus/io/utils.py
  python/pyabacus/src/pyabacus/io/xyz.py
  python/pyabacus/tests/test_cell.py
  python/pyabacus/tests/test_cell/h2o.xyz
  python/pyabacus/tests/test_cell/lcao_ZnO/INPUT
  python/pyabacus/tests/test_cell/lcao_ZnO/KPT
  python/pyabacus/tests/test_cell/lcao_ZnO/STRU
  python/pyabacus/tests/test_cell/lcao_ZnO/run.sh
Labels: pyabacus

#5344 Fix: Fix Consts memory leak by directly removing custome consts
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
Labels: The Absolute Zero

#5348 Fix: make EXX symmetry consistent with the fixed irreducible k-points
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_ri/Exx_LRI_interface.h
  source/module_ri/Exx_LRI_interface.hpp
  source/module_ri/module_exx_symmetry/irreducible_sector.cpp
  source/module_ri/module_exx_symmetry/irreducible_sector.h
  source/module_ri/module_exx_symmetry/symmetry_rotation.cpp
  source/module_ri/module_exx_symmetry/symmetry_rotation.h
Labels: Refactor

#5346 Refactor: Organize code structure to improve maintainability in pyabacus
  python/pyabacus/CMakeLists.txt
  python/pyabacus/CONTRIBUTING.md
  python/pyabacus/README.md
  python/pyabacus/examples/diago_matrix.py
  python/pyabacus/src/ModuleBase/CMakeLists.txt
  python/pyabacus/src/ModuleBase/py_base_math.cpp
  python/pyabacus/src/ModuleNAO/CMakeLists.txt
  python/pyabacus/src/ModuleNAO/py_m_nao.cpp
  python/pyabacus/src/hsolver/CMakeLists.txt
  python/pyabacus/src/hsolver/py_diago_dav_subspace.hpp
  python/pyabacus/src/hsolver/py_diago_david.hpp
  python/pyabacus/src/hsolver/py_hsolver.cpp
  python/pyabacus/src/py_abacus.cpp
  python/pyabacus/src/pyabacus/ModuleBase/_module_base.py
  python/pyabacus/src/pyabacus/ModuleNAO/__init__.py
  python/pyabacus/src/pyabacus/ModuleNAO/_module_nao.py
  python/pyabacus/src/pyabacus/__init__.py
  python/pyabacus/src/pyabacus/hsolver/__init__.py
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
  python/pyabacus/tests/test_base_math.py
Labels: pyabacus

#5351 Feature: MPI available on ABACUS DSP version
  source/module_base/blas_connector.cpp
  source/module_base/kernels/dsp/dsp_connector.h
  source/module_base/module_device/memory_op.cpp
  source/module_esolver/esolver_ks_pw.cpp
Labels: GPU & DCU & HPC

#5350 Toolchain: fix build scripts
  toolchain/build_abacus_gnu.sh
  toolchain/build_abacus_intel-mpich.sh
  toolchain/build_abacus_intel.sh
Labels: Compile & CICD & Docs & Dependencies

#5355 Fix: make the symmetry condition in RPA consistent with EXX
  source/module_ri/RPA_LRI.hpp
Labels: EXX

#5362 Refactor IO cube
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_elecstate/module_charge/symmetry_rho.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/io_npz.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/pw_nscf.cpp
  source/module_hamilt_pw/hamilt_pwdft/parallel_grid.cpp
  source/module_hamilt_pw/hamilt_pwdft/parallel_grid.h
  source/module_io/cube_io.h
  source/module_io/get_pchg_lcao.cpp
  source/module_io/get_pchg_pw.h
  source/module_io/get_wf_lcao.cpp
  source/module_io/read_cube.cpp
  source/module_io/test_serial/rho_io_test.cpp
  source/module_io/write_cube.cpp
  source/module_io/write_elecstat_pot.cpp
  source/module_io/write_elf.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
Labels: Refactor

#5375 Feature: move `scf_ene_thr` before `mix_rho`
  source/module_esolver/esolver_ks.cpp
Labels: Refactor

#5374 Unify the output of BFGS, CG, and FIRE relaxation method.
  source/module_md/fire.cpp
  source/module_md/test/fire_test.cpp
  source/module_relax/relax_new/relax.cpp
  source/module_relax/relax_old/ions_move_basic.cpp
  source/module_relax/relax_old/lattice_change_basic.cpp
  source/module_relax/relax_old/test/ions_move_basic_test.cpp
  source/module_relax/relax_old/test/ions_move_cg_test.cpp
  source/module_relax/relax_old/test/ions_move_sd_test.cpp
  source/module_relax/relax_old/test/lattice_change_basic_test.cpp
  source/module_relax/relax_old/test/lattice_change_cg_test.cpp
Labels: The Absolute Zero
