Repository deepmodeling/abacus-develop, pull requests merged in 2024-01, with the labels that each got.

#3454 Feature: support list input parse and multiple values for `bessel_nao_rcut`
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/test/input_test.cpp
  source/module_io/test/support/INPUT_list
Labels: Project

#3463 Feature: support QO can be installed like `python setup.py install` and use as `import abacus2qo`
  source/module_io/input.cpp
  source/module_io/to_qo.cpp
  tools/qo/README.md
  tools/qo/abacus2qo/__init__.py
  tools/qo/abacus2qo/components/__init__.py
  tools/qo/abacus2qo/components/basis_filter.py
  tools/qo/abacus2qo/components/calculator.py
  tools/qo/abacus2qo/components/data_container.py
  tools/qo/abacus2qo/components/data_manager.py
  tools/qo/abacus2qo/components/driver.py
  tools/qo/abacus2qo/components/safe_guard.py
  tools/qo/abacus2qo/tools/__init__.py
  tools/qo/abacus2qo/tools/basic_functions.py
  tools/qo/abacus2qo/tools/hamiltonian.py
  tools/qo/abacus2qo/tools/kpoints.py
  tools/qo/abacus2qo/tools/qo_ovlp.py
  tools/qo/abacus2qo/tools/wavefunction.py
  tools/qo/examples/INPUT
  tools/qo/examples/STRU
  tools/qo/main.py
  tools/qo/setup.py
Labels: Feature Request, Friendliness

#3483 Feature&Refactor: multiple values input now is supported by QO
  docs/advanced/input_files/input-main.md
  source/module_base/global_variable.cpp
  source/module_base/global_variable.h
  source/module_basis/module_nao/hydrogen_radials.cpp
  source/module_basis/module_nao/hydrogen_radials.h
  source/module_basis/module_nao/radial_collection.cpp
  source/module_basis/module_nao/radial_collection.h
  source/module_basis/module_nao/radial_set.h
  source/module_basis/module_nao/test/hydrogen_radials_test.cpp
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/input_conv.cpp
  source/module_io/test/input_test_para.cpp
  source/module_io/test/to_qo_test.cpp
  source/module_io/to_qo.cpp
  source/module_io/to_qo.h
  source/module_io/to_qo_tools.cpp
  tools/qo/abacus2qo/components/calculator.py
  tools/qo/abacus2qo/components/data_manager.py
  tools/qo/abacus2qo/components/driver.py
Labels: Feature Request, Friendliness

#3449 Feature: enable the computation of zeros of multiple spherical Bessel functions in one call
  source/module_base/math_sphbes.cpp
  source/module_base/math_sphbes.h
  source/module_base/test/math_sphbes_test.cpp
Labels: Friendliness

#3493 Feature: support segment split in kline mode in KPT file and `out_band` band output precision control, `8` as default
  docs/advanced/input_files/input-main.md
  source/module_cell/klist.cpp
  source/module_cell/klist.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/nscf_band.cpp
  source/module_io/nscf_band.h
  source/module_io/parameter_pool.cpp
  source/module_io/test/input_test.cpp
  source/module_io/test/input_test_para.cpp
  source/module_io/test/support/INPUT
  source/module_io/test/support/witestfile
  source/module_io/test_serial/nscf_band_test.cpp
  source/module_io/write_input.cpp
  tests/integrate/107_PW_OBOD_MemSaver/refBANDS_1.dat
  tests/integrate/107_PW_OB_outputbands/refBANDS_1.dat
  tests/integrate/207_NO_KP_OB/refBANDS_1.dat
Labels: Feature Request, Friendliness

#3575 CUDA: Add device error check for CUDA API and device function
  source/driver.cpp
  source/module_base/kernels/cuda/math_op.cu
  source/module_base/module_container/ATen/kernels/cuda/blas.cu
  source/module_base/module_container/ATen/kernels/cuda/lapack.cu
  source/module_base/module_container/ATen/kernels/cuda/linalg.cu
  source/module_base/module_container/ATen/kernels/cuda/memory.cu
  source/module_base/module_container/base/macros/cuda.h
  source/module_base/module_container/base/third_party/cublas.h
  source/module_base/module_container/base/third_party/cusolver.h
  source/module_basis/module_pw/kernels/cuda/pw_op.cu
  source/module_elecstate/kernels/cuda/elecstate_op.cu
  source/module_hamilt_general/module_xc/kernels/cuda/xc_functional_op.cu
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/ekinetic_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/force_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/meta_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/nonlocal_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/veff_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/vnl_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/wf_op.cu
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/kernels/cuda/dngvd_op.cu
  source/module_hsolver/kernels/cuda/math_kernel_op.cu
  source/module_hsolver/kernels/math_kernel_op.h
  source/module_psi/kernels/cuda/memory_op.cu
Labels: GPU
