Repository deepmodeling/abacus-develop, pull requests merged in 2024-07, with the labels that each got.

#4496 test: modify to check all properties even one property is reach warning threshold in Autotest.sh
  tests/integrate/101_PW_15_paw/threshold
  tests/integrate/108_PW_RE/threshold
  tests/integrate/109_PW_CR_fix_a/threshold
  tests/integrate/109_PW_CR_fix_ab/threshold
  tests/integrate/109_PW_CR_fix_abc/threshold
  tests/integrate/109_PW_CR_fix_ac/threshold
  tests/integrate/109_PW_CR_fix_b/threshold
  tests/integrate/109_PW_CR_fix_bc/threshold
  tests/integrate/109_PW_CR_fix_c/threshold
  tests/integrate/109_PW_CR_moveatoms/threshold
  tests/integrate/110_PW_SY_symmetry_6K/threshold
  tests/integrate/111_PW_S2_elec_add/threshold
  tests/integrate/116_PW_scan_Si2_nspin2/threshold
  tests/integrate/120_PW_KP_MD_NPT/threshold
  tests/integrate/120_PW_KP_MD_NVT/threshold
  tests/integrate/170_PW_MD_1O/threshold
  tests/integrate/170_PW_MD_2O/threshold
  tests/integrate/180_PW_SDFT_10S_M/threshold
  tests/integrate/181_PW_SDFT_5D10S/threshold
  tests/integrate/183_PW_MD_SDFT_ALL/threshold
  tests/integrate/184_PW_BNDPAR_SDFT_10S/threshold
  tests/integrate/184_PW_BNDPAR_SDFT_5D10S/threshold
  tests/integrate/Autotest.sh
Labels: Compile & CICD

#4519 Refactor: remove some variables from `LCAO_Matrix` class
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_HS_arrays.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_hamilt.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_exx.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.h
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_sparse.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_io/write_HS_R.cpp
  source/module_io/write_HS_sparse.cpp
  source/module_io/write_HS_sparse.h
Labels: The Absolute Zero

#4503 Refactor: removal of ORB_table_phi
  source/Makefile.Objects
  source/module_basis/module_ao/CMakeLists.txt
  source/module_basis/module_ao/ORB_control.cpp
  source/module_basis/module_ao/ORB_control.h
  source/module_basis/module_ao/ORB_gen_tables.cpp
  source/module_basis/module_ao/ORB_gen_tables.h
  source/module_basis/module_ao/ORB_table_phi.cpp
  source/module_basis/module_ao/ORB_table_phi.h
  source/module_basis/module_ao/README
  source/module_basis/module_ao/test/CMakeLists.txt
  source/module_basis/module_ao/test/ORB_table_alpha_test.cpp
  source/module_basis/module_ao/test/ORB_table_phi_test.cpp
  source/module_basis/module_ao/test/ORB_unittest.h
  source/module_basis/module_nao/test/two_center_integrator_test.cpp
  source/module_basis/module_nao/test/two_center_table_test.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb11.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb11.h
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb21.h
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb22.h
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.h
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_io/cal_r_overlap_R.cpp
  source/module_io/test/CMakeLists.txt
  source/module_io/to_wannier90_lcao.cpp
  source/module_io/to_wannier90_lcao.h
  source/module_io/to_wannier90_lcao_in_pw.h
  source/module_io/unk_overlap_lcao.cpp
  source/module_io/unk_overlap_lcao.h
  source/module_ri/Matrix_Orbs11.cpp
  source/module_ri/Matrix_Orbs11.h
  source/module_ri/Matrix_Orbs21.cpp
  source/module_ri/Matrix_Orbs21.h
  source/module_ri/Matrix_Orbs22.cpp
  source/module_ri/Matrix_Orbs22.h
Labels: The Absolute Zero

#4499 Refactor: Remove `check_structure()` from `UnitCell`.
  source/Makefile.Objects
  source/driver_run.cpp
  source/module_cell/CMakeLists.txt
  source/module_cell/check_atomic_stru.cpp
  source/module_cell/check_atomic_stru.h
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test_readpp.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
Labels: The Absolute Zero

#4509 refactor: replace the interface of out_dm by using DensityMatrix.DMK instead of loc.DM
  source/Makefile.Objects
  source/module_elecstate/elecstate_lcao.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_io/CMakeLists.txt
  source/module_io/dm_io.h
  source/module_io/io_dmk.cpp
  source/module_io/io_dmk.h
  source/module_io/output_dm.cpp
  source/module_io/output_dm.h
  source/module_io/read_dm.cpp
  source/module_io/test_serial/CMakeLists.txt
  source/module_io/test_serial/dm_io_test.cpp
  source/module_io/test_serial/io_dmk_test.cpp
  source/module_io/write_dm.cpp
  tests/integrate/314_NO_GO_dm_out/SPIN1_DM.ref
  tests/integrate/314_NO_GO_dm_out/result.ref
  tests/integrate/tools/catch_properties.sh
Labels: The Absolute Zero

#4548 refactor: remove the read of ntype from INPUT
  source/module_io/input.cpp
Labels: Features Needed

#4542 Fix test for output Vxc
  tests/integrate/207_NO_KP_OXC/k-1-Vxc.ref
  tests/integrate/207_NO_KP_OXC/result.ref
  tests/integrate/207_NO_KP_OXC/vxc_out.ref
  tests/integrate/307_NO_GO_OXC/result.ref
  tests/integrate/tools/catch_properties.sh
Labels: Bug Report (Exclude input and output)

#4541 Perf: reduce data tansfer in GPU code of module_gint
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_force_gpu.h
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.h
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.h
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/gtask_rho.cpp
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_vl.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_vl.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/interp.cuh
  source/module_hamilt_lcao/module_gint/mult_psi_dm_new.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
Labels: The Absolute Zero

#4568 Refactor: remove some variables from `LCAO_Matrix` class
  source/Makefile.Objects
  source/module_base/formatter.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_io/write_HS.hpp
Labels: The Absolute Zero

#4569 refactor: remove the useless variables and functions in unkOverlap_lcao
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_io/berryphase.cpp
  source/module_io/berryphase.h
  source/module_io/unk_overlap_lcao.cpp
  source/module_io/unk_overlap_lcao.h
Labels: The Absolute Zero

#4573 CI: login to use alicloud image sync
  .github/workflows/devcontainer.yml
Labels: Compile & CICD

#4571 Fix: get_S failed when smearing_method is gauss
  source/module_elecstate/elecstate.cpp
Labels: Bug Report (Exclude input and output)

#4566 Refactor: Split the function into different functionalities
  source/Makefile.Objects
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_force_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_gpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_rho_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
Labels: The Absolute Zero

#4579 Refactor: remove module_device additional dependencies
  source/module_base/memory.h
  source/module_base/module_device/device.cpp
  source/module_base/module_device/device.h
  source/module_base/module_device/memory_op.cpp
  source/module_base/module_device/memory_op.h
Labels: The Absolute Zero

#4578 CI: Remove `FormatStyle: file` in clang-tidy
  .clang-format
  .clang-tidy
Labels: Compile & CICD

#4557 Fix: now out_wfc_lcao is available in nscf
  source/module_esolver/esolver_ks_lcao_elec.cpp
Labels: Features Needed

#4575 Fix: DeePKS MD/Relax/Cell-relax calculation convergence
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
Labels: Features Needed

#4581 Refactor: fully refactored original obsolete lapack hsolver
  .github/workflows/build_test_cmake.yml
  CMakeLists.txt
  source/Makefile.Objects
  source/module_base/global_function.h
  source/module_basis/module_ao/ORB_control.cpp
  source/module_elecstate/math_tools.h
  source/module_elecstate/module_dm/cal_dm_psi.cpp
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_charge.cpp
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diago_lapack.cpp
  source/module_hsolver/diago_lapack.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_io/input.cpp
Labels: The Absolute Zero

#4593 Fix: fix a bug introduced by PR#4541
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  tests/integrate/922_NO_FeBiTe/INPUT
  tests/integrate/922_NO_FeBiTe/KPT
  tests/integrate/922_NO_FeBiTe/STRU
  tests/integrate/922_NO_FeBiTe/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bug Report (Exclude input and output), GPU & DCU & HPC

#4582 Refactor: Separate Class `diag_comm_info` and Class `const_nums `
  source/Makefile.Objects
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diag_comm_info.h
  source/module_hsolver/diag_const_nums.cpp
  source/module_hsolver/diag_const_nums.h
  source/module_hsolver/diagh.h
  source/module_hsolver/diagh_consts.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/hsolver_pw_sup.h
Labels: The Absolute Zero

#4585 Refactor: remove additional dependencies of `parallel_reduce.h`
  source/module_base/lapack_connector.h
  source/module_base/lapack_wrapper.h
  source/module_base/parallel_comm.h
  source/module_base/parallel_reduce.cpp
  source/module_base/parallel_reduce.h
  source/module_hsolver/kernels/dngvd_op.cpp
  source/module_hsolver/kernels/dngvd_op.h
  source/module_hsolver/kernels/math_kernel_op.h
Labels: The Absolute Zero

#4596 Build: enable deepmd-kit-3.0.0 interface
  CMakeLists.txt
  docs/advanced/install.md
  source/Makefile
Labels: Features Needed

#4591 Feature: add EXX H(R) to HContainer hR
  docs/advanced/input_files/input-main.md
  source/module_cell/klist.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.cpp
  source/module_io/restart_exx_csr.h
  source/module_io/restart_exx_csr.hpp
  source/module_io/write_Vxc.hpp
  source/module_ri/Exx_LRI_interface.h
  source/module_ri/Exx_LRI_interface.hpp
  source/module_ri/RI_2D_Comm.h
  source/module_ri/RI_2D_Comm.hpp
Labels: Features Needed

#4598 Refactor: add some info in nscf calculation
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_pw.cpp
Labels: Input&Output

#4560 refactor: add new option auto for init_chg
  docs/advanced/input_files/input-main.md
  docs/advanced/scf/initialization.md
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_io/input.cpp
  source/module_io/test/input_test.cpp
  source/module_io/write_input.cpp
  source/module_ri/exx_lip.cpp
  tests/integrate/117_PW_out_pot/INPUT
  tests/integrate/117_PW_out_pot/jd
  tests/integrate/117_PW_out_pot_nscf/INPUT
  tests/integrate/117_PW_out_pot_nscf/SPIN1_CHG.cube
  tests/integrate/117_PW_out_pot_nscf/refSPIN1_POT.cube
  tests/integrate/118_PW_CHG_BINARY/INPUT
  tests/integrate/118_PW_CHG_BINARY/jd
  tests/integrate/118_PW_CHG_BINARY/result.ref
  tests/integrate/214_NO_mulliken_nscf/INPUT
  tests/integrate/214_NO_mulliken_nscf/SPIN1_CHG.cube
  tests/integrate/214_NO_mulliken_nscf/STRU
  tests/integrate/214_NO_mulliken_nscf/mulliken.txt.ref
  tests/integrate/217_NO_out_pot_nscf/INPUT
  tests/integrate/217_NO_out_pot_nscf/SPIN1_CHG.cube
  tests/integrate/217_NO_out_pot_nscf/refSPIN1_POT.cube
Labels: Features Needed

#4590 Fix some minor security risks about ModuleESolver::init_esolver() and some potential functions
  source/driver_run.cpp
  source/module_elecstate/potentials/H_Hartree_pw.cpp
  source/module_elecstate/potentials/H_Hartree_pw.h
  source/module_elecstate/potentials/pot_base.h
  source/module_elecstate/potentials/pot_surchem.hpp
  source/module_elecstate/potentials/pot_xc.cpp
  source/module_elecstate/potentials/pot_xc.h
  source/module_elecstate/potentials/potential_new.cpp
  source/module_elecstate/potentials/potential_new.h
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver.h
Labels: Refactor

#4599 Fix: do not append Hk and Sk at the first step
  source/module_io/write_HS.hpp
Labels: Input&Output

#4603 Build: fix compatibility with oneAPI 2024.2
  CMakeLists.txt
  cmake/FindIntelMKL.cmake
Labels: Compile & CICD

#4536 Refactor: Separate LCAO-in-PW ESolver and HSolver from PW ones
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_hamilt_pw/hamilt_pwdft/wfinit.cpp
  source/module_hamilt_pw/hamilt_pwdft/wfinit.h
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_lcaopw.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_psi/psi_initializer.h
Labels: Features Needed

#4608 Add the R-space parallelization of Ewald energy calculations
  source/module_hamilt_general/module_ewald/H_Ewald_pw.cpp
Labels: Features Needed

#4609 Refactor: refactor diagHsubspace in dav_subspace method
  .clang-format
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/diago_iter_assist.h
  source/module_hsolver/hsolver_pw.cpp
Labels: The Absolute Zero

#4613 Fix: oneAPI runtime error when build with libtorch
  CMakeLists.txt
  README.md
  cmake/FindIntelMKL.cmake
  cmake/FindMKL.cmake
Labels: Compile & CICD

#4619 Refactor: remove LM from several class
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_HS_arrays.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_hamilt.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nl_mu.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_fs.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_mat2d.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fedm_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fedm_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deltaspin/cal_mw.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hamilt_lcao/module_deltaspin/init_sc.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.h
  source/module_hamilt_lcao/module_deltaspin/template_helpers.cpp
  source/module_hamilt_lcao/module_deltaspin/test/init_sc_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/spin_constrain_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/template_helpers_test.cpp
  source/module_hamilt_lcao/module_dftu/dftu.cpp
  source/module_hamilt_lcao/module_dftu/dftu_force.cpp
  source/module_hamilt_lcao/module_dftu/dftu_yukawa.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma.h
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_io/output_mat_sparse.cpp
  source/module_io/write_HS_R.cpp
  source/module_io/write_HS_R.h
  source/module_io/write_HS_sparse.cpp
  source/module_io/write_Vxc.hpp
  source/module_ri/Exx_LRI_interface.h
  source/module_ri/Exx_LRI_interface.hpp
  source/module_ri/RI_2D_Comm.h
Labels: The Absolute Zero

#4629 Fix: bug of misunderstanding absolute path as annotation
  source/module_io/read_input.cpp
Labels: Bug Report (Exclude input and output)

#4630 fix: bug of missing head of running.log
  source/driver.cpp
  source/driver.h
Labels: Bug Report (Exclude input and output)

#4620 Refactor: removal of ORB_control
  source/Makefile.Objects
  source/module_basis/module_ao/CMakeLists.txt
  source/module_basis/module_ao/ORB_control.cpp
  source/module_basis/module_ao/ORB_control.h
  source/module_basis/module_ao/ORB_read.cpp
  source/module_basis/module_ao/ORB_read.h
  source/module_basis/module_ao/README
  source/module_basis/module_ao/parallel_2d.h
  source/module_basis/module_ao/parallel_orbitals.cpp
  source/module_basis/module_ao/parallel_orbitals.h
  source/module_basis/module_ao/test/CMakeLists.txt
  source/module_basis/module_ao/test/ORB_read_test.cpp
  source/module_basis/module_ao/test/ORB_unittest.cpp
  source/module_basis/module_nao/two_center_bundle.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_esolver/io_npz.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_hsolver/test/diago_pexsi_test.cpp
Labels: The Absolute Zero

#4618 refactor: remove LOC
  source/Makefile.Objects
  source/module_basis/module_ao/parallel_orbitals.cpp
  source/module_basis/module_ao/parallel_orbitals.h
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_lcao.h
  source/module_elecstate/elecstate_lcao_tddft.cpp
  source/module_elecstate/elecstate_lcao_tddft.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma_2d_to_grid.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma_2d_to_grid.h
  source/module_hamilt_lcao/hamilt_lcaodft/DM_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/dm_2d.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_charge.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_charge.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/meta_lcao.h
  source/module_io/input_conv.cpp
  source/module_io/istate_charge.h
  source/module_io/read_wfc_nao.cpp
  source/module_io/read_wfc_nao.h
  source/module_io/test/for_testing_input_conv.h
  source/module_io/test/input_conv_test.cpp
  source/module_io/test_serial/CMakeLists.txt
  source/module_io/test_serial/read_wfc_nao_test.cpp
  source/module_io/unk_overlap_lcao.h
  source/module_io/write_dos_lcao.cpp
  source/module_ri/Exx_LRI_interface.h
  source/module_ri/Exx_LRI_interface.hpp
  source/module_ri/RPA_LRI.h
Labels: The Absolute Zero

#4640 test to merge
  source/module_cell/klist.cpp
  source/module_cell/parallel_kpoints.cpp
  source/module_cell/parallel_kpoints.h
  source/module_io/numerical_basis.cpp
Labels: Bug Report (Exclude input and output)

#4644 fix: mkl scalapack linking
  CMakeLists.txt
  cmake/FindMKL.cmake
  source/module_base/test_parallel/CMakeLists.txt
Labels: Compile & CICD

#4646 Refactor: refactor paw func in hsolver_pw
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
Labels: The Absolute Zero

#4649 test: modify to print runningxxx.log only one time in integrate test
  tests/integrate/Autotest.sh
Labels: Input&Output

#4645 Refactor: remove `LCAO_Matrix` from several class
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_hamilt.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_exx.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.h
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_io/dos_nao.cpp
  source/module_io/dos_nao.h
  source/module_io/output_mat_sparse.cpp
  source/module_io/output_sk.cpp
  source/module_io/output_sk.h
  source/module_io/restart.h
  source/module_io/restart_exx_csr.h
  source/module_io/test/output_mulliken_mock.cpp
  source/module_io/test/output_mulliken_test.cpp
  source/module_io/write_HS.h
  source/module_io/write_HS_R.cpp
  source/module_io/write_HS_R.h
  source/module_io/write_HS_sparse.cpp
  source/module_io/write_HS_sparse.h
  source/module_io/write_dos_lcao.cpp
  source/module_io/write_dos_lcao.h
  source/module_io/write_proj_band_lcao.cpp
  source/module_io/write_proj_band_lcao.h
Labels: The Absolute Zero

#4651 Perf: optimize function cal_fvnl_dbeta
  source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_k.cpp
Labels: The Absolute Zero

#4621 Feature: recover `Exx_Lip` and support `out_mat_xc` for lcao-in-pw calculation
  source/module_base/lapack_connector.h
  source/module_base/parallel_reduce.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_hamilt_general/module_xc/exx_info.h
  source/module_hamilt_general/module_xc/xc_functional.cpp
  source/module_hamilt_general/module_xc/xc_functional.h
  source/module_hamilt_pw/hamilt_pwdft/global.cpp
  source/module_hamilt_pw/hamilt_pwdft/global.h
  source/module_hamilt_pw/hamilt_pwdft/hamilt_lcaopw.h
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.h
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/diago_iter_assist.h
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_io/write_HS.h
  source/module_io/write_HS.hpp
  source/module_io/write_Vxc.hpp
  source/module_io/write_Vxc_lip.hpp
  source/module_ri/exx_lip.cpp
  source/module_ri/exx_lip.h
Labels: Refactor

#4648 fix: wrong running_*.log
  source/driver.cpp
  source/module_io/input_conv.cpp
  source/module_io/read_input.cpp
  source/module_psi/psi_initializer.h
Labels: Bug Report (Exclude input and output)

#4656 Fix MKL finding problem in pyabacus
  python/pyabacus/CMakeLists.txt
Labels: Compile & CICD

#4584 Refactor: adjust cif file output
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_cell/module_symmetry/symmetry.h
  source/module_cell/print_cif.cpp
  source/module_cell/read_atoms.cpp
  source/module_cell/test/CMakeLists.txt
  source/module_cell/unitcell.cpp
  source/module_esolver/esolver_ks.cpp
Labels: Input&Output

#4671 Perf: optimize function grad_rl_sph_harm
  source/module_base/array_pool.h
  source/module_base/math_ylmreal.cpp
  source/module_base/test/math_ylmreal_test.cpp
  source/module_base/ylm.cpp
  source/module_base/ylm.h
  source/module_basis/module_nao/two_center_integrator.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb11.cpp
  source/module_hamilt_lcao/module_gint/cal_ddpsir_ylm.cpp
  source/module_hamilt_lcao/module_gint/cal_dpsir_ylm.cpp
  source/module_hamilt_lcao/module_gint/gint_fvl.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma_env.cpp
  source/module_hamilt_lcao/module_gint/gint_k_env.cpp
  source/module_hamilt_lcao/module_gint/gint_rho.cpp
  source/module_hamilt_lcao/module_gint/gint_tau.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/test/test_sph.cpp
  source/module_hamilt_lcao/module_gint/test/test_sph.cu
  source/module_hamilt_lcao/module_gint/test/test_sph.h
Labels: The Absolute Zero

#4672 Fix a possible compile error in `module_lr/lr_spectrum.cpp`
  source/module_lr/lr_spectrum.cpp
Labels: Refactor

#4668 test: add an option to set thread number in Autotest.sh
  tests/deepks/Autotest.sh
  tests/deepks/CMakeLists.txt
  tests/integrate/Autotest.sh
Labels: Compile & CICD

#4678 Fix the problematic logic in catch_properties.sh induced by #4472
  tests/integrate/tools/catch_properties.sh
Labels: Compile & CICD

#4679 Refactor: remove EXX in LM and finally remove LM
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/io_npz.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.h
  source/module_io/output_mat_sparse.cpp
  source/module_io/output_mat_sparse.h
  source/module_io/write_HS_R.cpp
  source/module_io/write_HS_R.h
  source/module_io/write_Vxc.hpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_ri/Exx_LRI_interface.hpp
Labels: The Absolute Zero

#4658 Refactor: remove comm_2D from Parallel_2D (Useful Information: BLACS encapsulates MPI and maintains its own internal data structure for MPI communicators)
  source/module_base/blacs_connector.h
  source/module_basis/module_ao/parallel_2d.cpp
  source/module_basis/module_ao/parallel_2d.h
  source/module_basis/module_ao/parallel_orbitals.cpp
  source/module_basis/module_ao/test/parallel_2d_test.cpp
  source/module_basis/module_ao/test/parallel_orbitals_test.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/module_tddft/bandenergy.cpp
  source/module_hamilt_lcao/module_tddft/norm_psi.cpp
  source/module_hamilt_lcao/module_tddft/propagator.cpp
  source/module_hamilt_lcao/module_tddft/test/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/test/bandenergy_test.cpp
  source/module_hamilt_lcao/module_tddft/test/norm_psi_test.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test1.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test2.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test3.cpp
  source/module_hsolver/test/diago_pexsi_test.cpp
  source/module_io/io_dmk.cpp
  source/module_io/istate_envelope.cpp
  source/module_io/read_wfc_lcao.cpp
  source/module_io/read_wfc_nao.cpp
  source/module_io/write_Vxc.hpp
  source/module_io/write_dmr.cpp
  source/module_io/write_wfc_nao.cpp
  source/module_lr/AX/AX_parallel.cpp
  source/module_lr/AX/test/AX_test.cpp
  source/module_lr/dm_trans/dm_trans_parallel.cpp
  source/module_lr/dm_trans/test/dm_trans_test.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/utils/lr_util.cpp
  source/module_lr/utils/lr_util.h
  source/module_lr/utils/lr_util.hpp
Labels: Useful Information

#4683 Doc: Correct the formula of $\Delta\rho_R$ in the annotation of `scf_thr_type`.
  docs/advanced/input_files/input-main.md
Labels: Input&Output

#4682 Fix: change C++14 codes to C++11
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_lr/utils/gint_move.hpp
  source/module_lr/utils/lr_util.cpp
  source/module_lr/utils/lr_util.h
  source/module_lr/utils/lr_util.hpp
Labels: Refactor

#4610 Test: Unit test for diago_lapack, add a build test and update the document
  .github/workflows/build_test_cmake.yml
  CMakeLists.txt
  docs/advanced/input_files/input-main.md
  docs/quick_start/easy_install.md
  source/module_base/CMakeLists.txt
  source/module_base/module_container/ATen/kernels/CMakeLists.txt
  source/module_base/module_container/ATen/ops/CMakeLists.txt
  source/module_base/module_container/CMakeLists.txt
  source/module_basis/module_ao/CMakeLists.txt
  source/module_basis/module_nao/CMakeLists.txt
  source/module_basis/module_pw/CMakeLists.txt
  source/module_cell/CMakeLists.txt
  source/module_cell/module_neighbor/CMakeLists.txt
  source/module_cell/module_paw/CMakeLists.txt
  source/module_cell/module_symmetry/CMakeLists.txt
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/module_dm/CMakeLists.txt
  source/module_elecstate/test/CMakeLists.txt
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_general/CMakeLists.txt
  source/module_hamilt_general/module_surchem/CMakeLists.txt
  source/module_hamilt_general/module_vdw/CMakeLists.txt
  source/module_hamilt_general/module_xc/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/CMakeLists.txt
  source/module_hamilt_lcao/module_deltaspin/CMakeLists.txt
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_hcontainer/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_stodft/CMakeLists.txt
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diago_lapack.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/GammaOnly-Si2-Solution.dat
  source/module_hsolver/test/GammaOnly-Si64-Solution.dat
  source/module_hsolver/test/KPoints-Si2-Solution.dat
  source/module_hsolver/test/KPoints-Si64-Solution.dat
  source/module_hsolver/test/diago_lapack_test.cpp
  source/module_io/CMakeLists.txt
  source/module_io/json_output/CMakeLists.txt
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/hamilt_casida.cpp
  source/module_lr/lr_spectrum.cpp
  source/module_lr/operator_casida/operator_lr_hxc.cpp
  source/module_md/CMakeLists.txt
  source/module_psi/CMakeLists.txt
  source/module_relax/CMakeLists.txt
  source/module_ri/CMakeLists.txt
Labels: The Absolute Zero

#4688 Test: add ccache installation step to cuda.yml
  .github/workflows/cuda.yml
Labels: Compile & CICD

#4689 delete redundant setting in STRU
  examples/tddft/Absoption_spectrum/H2_length/STRU
  examples/tddft/Absoption_spectrum/H2_velocity/STRU
Labels: Refactor

#4691 Feature: read a slice of bands from WFC_NAO files & enable custom close-to-HOMO `nocc` for LR
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver.cpp
  source/module_io/input.h
  source/module_io/read_input_item_other.cpp
  source/module_io/read_wfc_nao.cpp
  source/module_io/read_wfc_nao.h
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_io/test_serial/read_wfc_nao_test.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/esolver_lrtd_lcao.h
  source/module_parameter/input_parameter.h
Labels: Features Needed

#4680 Perf: optimize function pow in module_gint
  source/module_hamilt_lcao/module_gint/cal_ddpsir_ylm.cpp
  source/module_hamilt_lcao/module_gint/cal_dpsir_ylm.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
  source/module_hamilt_lcao/module_gint/grid_meshball.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/interp.cuh
Labels: The Absolute Zero

#4696 Fix the missing EXX operator and minor refactor in LR-HSE
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/esolver_lrtd_lcao.h
  source/module_lr/hamilt_casida.h
  source/module_lr/operator_casida/operator_lr_exx.cpp
  source/module_lr/operator_casida/operator_lr_exx.h
  source/module_lr/potentials/pot_hxc_lrtd.cpp
Labels: Refactor

#4704 Fix the bug causing incorrect Berry phase calculations under the pw basis.
  source/module_io/unk_overlap_pw.cpp
Labels: Bug Report (Exclude input and output)

#4675 Refactor: reorganized `HSolverPW<T, Device>::solve` function in `HSolverPW`
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/test/test_hsolver_pw.cpp
Labels: The Absolute Zero

#4711 Refactor: Remove useless variables from `read_pp.h`.
  source/module_cell/pseudo.cpp
  source/module_cell/pseudo.h
  source/module_cell/read_cell_pseudopots.cpp
  source/module_cell/read_pp.cpp
  source/module_cell/read_pp.h
  source/module_cell/read_pp_blps.cpp
  source/module_cell/read_pp_upf100.cpp
  source/module_cell/read_pp_upf201.cpp
  source/module_cell/read_pp_vwr.cpp
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/atom_pseudo_test.cpp
  source/module_cell/test/atom_spec_test.cpp
  source/module_cell/test/pseudo_nc_test.cpp
  source/module_cell/test/read_pp_test.cpp
Labels: The Absolute Zero

#4715 Refactor: separate `parallel_comm` from `parallel_global`
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_base/parallel_comm.cpp
  source/module_base/parallel_comm.h
  source/module_base/parallel_global.cpp
  source/module_base/parallel_global.h
  source/module_base/parallel_reduce.cpp
  source/module_base/test/CMakeLists.txt
  source/module_base/test_parallel/CMakeLists.txt
  source/module_basis/module_pw/kernels/test/CMakeLists.txt
  source/module_cell/test/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt
  source/module_io/test/CMakeLists.txt
  source/module_md/test/CMakeLists.txt
Labels: The Absolute Zero

#4555 Feature: Partial function heterogeneous parallel acceleration of force/stress_cc.
  .gitignore
  source/Makefile.Objects
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_cc.cpp
Labels: GPU & DCU & HPC

#4717 test: correct the inputs in /examples
  examples/bsse/water/run.sh
  examples/dft_plus_u/NiO/INPUT
  examples/relax/pw_al/INPUT
Labels: Input&Output

#4722 Refactor david: complete removal of Psi and Hamilt datatypes
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_lr/hsolver_lrtd.cpp
Labels: The Absolute Zero

#4727 Perf: optimize force calculation in module_gint (Useful information about how to take advantages of data locality to improve the code efficiency)
  source/module_hamilt_lcao/module_gint/cal_dpsir_ylm.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_force_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_fvl.cpp
  source/module_hamilt_lcao/module_gint/gint_rho.cpp
  source/module_hamilt_lcao/module_gint/gint_tau.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
Labels: Useful Information

#4726 Refactor hsolver: redesign david interface to be consistent with dav_subspace
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_lr/hsolver_lrtd.cpp
Labels: The Absolute Zero

#4731 Fix: memory leak of basis set in david
  source/module_hsolver/diago_david.cpp
Labels: Bug Report (Exclude input and output)

#4720 Fix: replace most of bare pointers with weak/unique_ptr in module_lr to prevent memory leak (Useful information about how to use smart pointers in C++11))
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/hamilt_casida.h
  source/module_lr/operator_casida/operator_lr_exx.cpp
  source/module_lr/operator_casida/operator_lr_exx.h
  source/module_lr/operator_casida/operator_lr_hxc.cpp
  source/module_lr/operator_casida/operator_lr_hxc.h
  source/module_lr/potentials/pot_hxc_lrtd.cpp
  source/module_lr/potentials/pot_hxc_lrtd.h
  source/module_lr/utils/lr_util.hpp
Labels: Useful Information

#4605 Fix: DeePKS MD calculation restart by DMK and fixed the lack of DeePKS tests
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/INPUT
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/KPT
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/STRU
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/get_dm_eig.py
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/get_grad_vepsl.py
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/get_grad_vx.py
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/jd
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/jle.orb
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/result.ref
  tests/deepks/602_NO_deepks_d_H2O_scf_lda2pbe/result.ref
  tests/deepks/603_NO_deepks_H2O_bandgap/INPUT
  tests/deepks/603_NO_deepks_H2O_bandgap/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_bandgap/result.ref
  tests/deepks/603_NO_deepks_H2O_multik/result.ref
  tests/deepks/603_NO_deepks_H2O_v_delta_1/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_v_delta_1/result.ref
  tests/deepks/603_NO_deepks_H2O_v_delta_2/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_v_delta_2/result.ref
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/log.scf
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/result.ref
  tests/deepks/603_NO_deepks_watertrimer/result.ref
  tests/deepks/CASES_CPU.txt
  tests/integrate/Autotest.sh
  tests/integrate/tools/catch_properties.sh
Labels: Refactor

#4650 Feature: support k-parallelism diagonalization in lcao basis
  source/Makefile.Objects
  source/module_base/global_variable.cpp
  source/module_base/global_variable.h
  source/module_basis/module_ao/parallel_orbitals.cpp
  source/module_basis/module_ao/parallel_orbitals.h
  source/module_cell/parallel_kpoints.h
  source/module_cell/test/CMakeLists.txt
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/tmp_mocks.cpp
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diagh.h
  source/module_hsolver/diago_elpa.cpp
  source/module_hsolver/diago_elpa.h
  source/module_hsolver/diago_scalapack.cpp
  source/module_hsolver/diago_scalapack.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/hsolver_lcao.h
  source/module_hsolver/parallel_k2d.cpp
  source/module_hsolver/parallel_k2d.h
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/parallel_k2d_test.cpp
  source/module_hsolver/test/parallel_k2d_test.sh
  source/module_io/input_conv.cpp
  source/module_io/read_input_item_general.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/test/input_test.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  tests/integrate/201_NO_15_pseudopots_kpar/INPUT
  tests/integrate/201_NO_15_pseudopots_kpar/KPT
  tests/integrate/201_NO_15_pseudopots_kpar/STRU
  tests/integrate/201_NO_15_pseudopots_kpar/jd
  tests/integrate/201_NO_15_pseudopots_kpar/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Feature Discussed

#4746 Remove init_basis_lcao from ESolver_LCAO to LCAO_domain
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_init_basis.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
Labels: The Absolute Zero

#4749 Fix: no Fail of read_input_serial_test.cpp
  source/module_base/test/tool_quit_no_exit.cpp
  source/module_io/read_input_item_general.cpp
  source/module_io/test_serial/CMakeLists.txt
  source/module_io/test_serial/read_input_test.cpp
Labels: Bug Report (Exclude input and output)

#4734 Refactor david: add docs and standardize the code
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
Labels: The Absolute Zero

#4770 Fix: consider fractional electron number
  source/module_cell/atom_pseudo.cpp
  source/module_cell/pseudo.h
  source/module_cell/read_pp_blps.cpp
  source/module_cell/read_pp_upf201.cpp
  source/module_cell/read_pp_vwr.cpp
  source/module_io/berryphase.cpp
  source/module_io/json_output/init_info.cpp
  source/module_io/json_output/test/para_json_test.cpp
Labels: Features Needed

#4773 Reduce the size of LCAO_deepks_torch.cpp
  source/Makefile.Objects
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/orbital_precalc.cpp
  source/module_hamilt_lcao/module_deepks/orbital_precalc_k.cpp
Labels: The Absolute Zero

#4752 Fix incomplete atom map due to the subtle symmetry_prec
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_cell/module_symmetry/symmetry.h
Labels: Symmetry

#4764 Refactor: remove globalV from hsolver_pw
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/test/test_hsolver_pw.cpp
Labels: The Absolute Zero

#4776 Code Quality: polish the docs in Symmetry Class and remove some unused functions
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_cell/module_symmetry/symmetry.h
  source/module_cell/module_symmetry/symmetry_basic.h
Labels: Compile & CICD & Docs

#4777 Keep refactoring DeePKS module (the third one)
  source/Makefile.Objects
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_fdelta.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_fgamma.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_fk.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/cal_descriptor.cpp
  source/module_hamilt_lcao/module_deepks/cal_gdmx.cpp
  source/module_hamilt_lcao/module_deepks/cal_gdmx_k.cpp
  source/module_hamilt_lcao/module_deepks/cal_gedm.cpp
  source/module_hamilt_lcao/module_deepks/cal_gvx.cpp
  source/module_hamilt_lcao/module_deepks/orbital_precalc.cpp
  source/module_hamilt_lcao/module_deepks/v_delta_precalc.cpp
Labels: The Absolute Zero

#4782 update out_dos_lcao of '2' for output PDOS
  docs/advanced/input_files/input-main.md
  examples/dos/lcao_Si2/run.sh
  source/module_io/write_dos_lcao.cpp
Labels: Features Needed

#4769 Refactor: refactor `set_diagethr`, `cal_hsolerror`, `cal_hsolerror` func in hsolver class
  source/module_esolver/esolver_ks.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver.cpp
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/hsolver_lrtd.h
Labels: The Absolute Zero

#4788 Fix: eliminate the implicit type conversion when calculating number of electrons of system and repair bessel_nao_rcut behavior
  source/module_cell/unitcell.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/numerical_basis.cpp
  source/module_io/numerical_basis.h
Labels: Bug Report (Exclude input and output)

#4793 Fix a memory leak in LR constructor
  source/module_lr/esolver_lrtd_lcao.cpp
Labels: Bug Report (Exclude input and output)

#4784 Refactor DeepKS (the fourth one)
  examples/deepks/lcao_H2O/INPUT
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_fgamma.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_fk.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/cal_descriptor.cpp
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/INPUT
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/get_dm_eig.py
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/get_grad_vepsl.py
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/get_grad_vx.py
  tests/deepks/602_NO_deepks_d_H2O_scf_lda2pbe/get_dm_eig.py
  tests/deepks/602_NO_deepks_d_H2O_scf_lda2pbe/get_grad_vepsl.py
  tests/deepks/602_NO_deepks_d_H2O_scf_lda2pbe/get_grad_vx.py
  tests/deepks/603_NO_deepks_CH4/INPUT
  tests/deepks/603_NO_deepks_CH4/STRU
  tests/deepks/603_NO_deepks_CH4/result.ref
  tests/deepks/603_NO_deepks_H2O_bandgap/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_bandgap/get_odelta.py
  tests/deepks/603_NO_deepks_H2O_bandgap/get_oprec.py
  tests/deepks/603_NO_deepks_H2O_v_delta_1/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_v_delta_1/get_v_delta.py
  tests/deepks/603_NO_deepks_H2O_v_delta_2/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_v_delta_2/get_v_delta.py
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/get_dm_eig.py
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/get_grad_vepsl.py
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/get_grad_vx.py
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/get_odelta.py
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/get_oprec.py
  tests/deepks/Autotest1.sh
  tests/deepks/clean.sh
  tests/integrate/clean.sh
  tests/integrate/tools/catch_properties.sh
Labels: The Absolute Zero

#4792 fix: wrong use of bessel_nao_rcut
  source/module_cell/unitcell.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/bcast_globalv.cpp
  source/module_io/input.h
  source/module_io/input_conv_tmp.cpp
  source/module_io/numerical_basis.cpp
  source/module_io/numerical_basis.h
  source/module_io/read_input_item_other.cpp
  source/module_io/test/input_test.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_parameter/system_parameter.h
Labels: The Absolute Zero

#4806 Refactor: allocate david gpu memory in unified constructor&destructor
  source/module_hsolver/diago_david.cpp
Labels: The Absolute Zero

#4790 Refactor: remove `diago_iter_assist` from `hsolverPW`
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver.cpp
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: The Absolute Zero

#4799 Feature: output vacuum level when output electrostatic potential
  source/module_io/output_log.cpp
  source/module_io/output_log.h
  source/module_io/test/CMakeLists.txt
  source/module_io/test/outputlog_test.cpp
  source/module_io/write_pot.cpp
Labels: Features Needed

#4809 Update Esolver and DeePKS (5th)
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/dftu_cal_occup_m.cpp
  source/module_esolver/dpks_cal_e_delta_band.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/print_funcs.cpp
  source/module_esolver/print_funcs.h
  source/module_esolver/set_matrix_grid.cpp
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fgamma.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fk.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.h
  source/module_hamilt_lcao/module_deepks/deepks_hmat.cpp
  source/module_hamilt_lcao/module_deepks/deepks_hmat.h
Labels: The Absolute Zero

#4805 Feature: write band energy of T, VL, VNL, Hartree and XC terms separately
  docs/advanced/input_files/input-main.md
  source/module_base/scalapack_connector.h
  source/module_elecstate/potentials/potential_new.cpp
  source/module_elecstate/potentials/potential_new.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_io/read_input_item_output.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/write_eband_terms.hpp
  source/module_io/write_vxc.hpp
  source/module_io/write_vxc_lip.hpp
  source/module_parameter/input_parameter.h
  tests/integrate/207_NO_KP_OXC/INPUT
  tests/integrate/207_NO_KP_OXC/kinetic_out.ref
  tests/integrate/207_NO_KP_OXC/result.ref
  tests/integrate/207_NO_KP_OXC/vhartree_out.ref
  tests/integrate/207_NO_KP_OXC/vpp_local_out.ref
  tests/integrate/207_NO_KP_OXC/vpp_nonlocal_out.ref
  tests/integrate/307_NO_GO_OXC/INPUT
  tests/integrate/307_NO_GO_OXC/kinetic_out.ref
  tests/integrate/307_NO_GO_OXC/result.ref
  tests/integrate/307_NO_GO_OXC/vhartree_out.ref
  tests/integrate/307_NO_GO_OXC/vpp_local_out.ref
  tests/integrate/307_NO_GO_OXC/vpp_nonlocal_out.ref
  tests/integrate/tools/catch_properties.sh
Labels: Features Needed

#4803 Fix the incorrect calculation of partial charge for multi-k-points under both PW and LCAO when symmetry is turned on
  source/Makefile.Objects
  source/module_elecstate/module_charge/symmetry_rho.cpp
  source/module_elecstate/module_charge/symmetry_rho.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/CMakeLists.txt
  source/module_io/get_pchg.cpp
  source/module_io/get_pchg.h
  source/module_io/get_wf.cpp
  source/module_io/get_wf.h
Labels: Bug Report (Exclude input and output)

#4771 Docs: add docs for running_scf.log file in docs/advanced/input_files.
  docs/advanced/output_files/index.rst
  docs/advanced/output_files/running_scf.log.md
Labels: Feature Discussed

#4812 Refactor ESolver, separate out some functions that will be moved to other places later.
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/cal_edm_tddft.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/io_npz.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_fun.cpp
  source/module_esolver/lcao_gets.cpp
  source/module_esolver/lcao_init_after_vc.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/pw_fun.cpp
  source/module_esolver/pw_init_after_vc.cpp
  source/module_esolver/pw_init_globalc.cpp
  source/module_esolver/pw_nscf.cpp
  source/module_esolver/pw_others.cpp
  source/module_esolver/set_matrix_grid.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
Labels: The Absolute Zero

#4808 Refactor: enable const md_para as md_line passing parameter
  source/driver_run.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_st.cpp
  source/module_hamilt_lcao/module_tddft/evolve_psi.cpp
  source/module_hamilt_lcao/module_tddft/propagator.cpp
  source/module_hamilt_lcao/module_tddft/propagator.h
  source/module_hamilt_lcao/module_tddft/test/propagator_test1.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test2.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test3.cpp
  source/module_io/input.h
  source/module_io/input_conv.cpp
  source/module_io/input_conv_tmp.cpp
  source/module_io/print_info.cpp
  source/module_io/read_input_item_md.cpp
  source/module_io/read_input_item_relax.cpp
  source/module_io/read_input_item_system.cpp
  source/module_io/test/print_info_test.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_md/fire.cpp
  source/module_md/fire.h
  source/module_md/langevin.cpp
  source/module_md/langevin.h
  source/module_md/md_base.cpp
  source/module_md/md_base.h
  source/module_md/md_func.cpp
  source/module_md/md_func.h
  source/module_md/msst.cpp
  source/module_md/msst.h
  source/module_md/nhchain.cpp
  source/module_md/nhchain.h
  source/module_md/run_md.cpp
  source/module_md/run_md.h
  source/module_md/test/fire_test.cpp
  source/module_md/test/langevin_test.cpp
  source/module_md/test/md_func_test.cpp
  source/module_md/test/msst_test.cpp
  source/module_md/test/nhchain_test.cpp
  source/module_md/test/setcell.h
  source/module_md/test/verlet_test.cpp
  source/module_md/verlet.cpp
  source/module_md/verlet.h
  source/module_parameter/md_parameter.h
  source/module_parameter/parameter.cpp
Labels: The Absolute Zero

#4759 Refactor: Heterogeneous parallel acceleration hsolver-pw force_scc.
  source/Makefile.Objects
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/forces_scc.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_stodft/sto_forces.cpp
Labels: GPU & DCU & HPC

#4786 Fix: dcu error in pw_force calculation
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
Labels: GPU & DCU & HPC

#4822 Feature: stop abacus manually according to the keyword in EXIT
  docs/advanced/opt.md
  source/Makefile.Objects
  source/module_io/CMakeLists.txt
  source/module_io/read_exit_file.cpp
  source/module_io/read_exit_file.h
  source/module_io/test/CMakeLists.txt
  source/module_io/test/read_exit_file_test.cpp
  source/module_relax/relax_driver.cpp
  tests/integrate/706_LJ_RE_stop/EXIT
  tests/integrate/706_LJ_RE_stop/INPUT
  tests/integrate/706_LJ_RE_stop/STRU
  tests/integrate/706_LJ_RE_stop/jd
  tests/integrate/706_LJ_RE_stop/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Features Needed

#4811 Refactor: Move `pseudo::set_pseudo` to `Pseudopot::complete_default`.
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/pseudo.cpp
  source/module_cell/pseudo.h
  source/module_cell/read_cell_pseudopots.cpp
  source/module_cell/read_pp.cpp
  source/module_cell/read_pp.h
  source/module_cell/read_pp_complete.cpp
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/atom_pseudo_test.cpp
  source/module_cell/test/atom_spec_test.cpp
  source/module_cell/test/pseudo_nc_test.cpp
  source/module_cell/test_pw/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_md/test/CMakeLists.txt
Labels: The Absolute Zero

#4835 Refactor: remove uncessary interfaces in module_io
  source/Makefile.Objects
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_gets.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/pw_fun.cpp
  source/module_esolver/pw_init_after_vc.cpp
  source/module_esolver/pw_init_globalc.cpp
  source/module_esolver/pw_nscf.cpp
  source/module_esolver/pw_others.cpp
  source/module_esolver/set_matrix_grid.cpp
  source/module_io/CMakeLists.txt
  source/module_io/get_pchg.cpp
  source/module_io/get_wf.cpp
  source/module_io/output_potential.cpp
  source/module_io/output_potential.h
  source/module_io/output_rho.cpp
  source/module_io/output_rho.h
  source/module_io/rho_io.h
  source/module_io/test_serial/CMakeLists.txt
  source/module_io/test_serial/rho_io_test.cpp
  source/module_io/write_elecstat_pot.cpp
  source/module_io/write_elecstat_pot.h
  source/module_io/write_pot.h
  source/module_io/write_rho.cpp
Labels: The Absolute Zero
