Repository deepmodeling/abacus-develop, pull requests merged in 2024-05, with the labels that each got.

#4110 Replace “lm->paraV” with “paraV” to simpifier parameters
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma.h
  source/module_hamilt_lcao/module_gint/gint_gamma_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_pvpr.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_io/write_Vxc.hpp
Labels: Refactor

#4148 Fix wrong output of S(k) in TDDFT calculation
  source/module_esolver/esolver_ks_lcao_tddft.cpp
Labels: Input&Output

#4151 Feature: enable uspp in upf100 format
  source/module_cell/read_pp_upf100.cpp
  source/module_cell/test/read_pp_test.cpp
  source/module_cell/test/support/Zn.pw91-n-van.UPF
  source/module_cell/test/support/fe_pbe_v1.5.uspp.F.UPF
  tests/PP_ORB/fe_pbe_v1.5.uspp.F.UPF
  tests/integrate/101_PW_upf100_uspp_Fe/INPUT
  tests/integrate/101_PW_upf100_uspp_Fe/KPT
  tests/integrate/101_PW_upf100_uspp_Fe/README
  tests/integrate/101_PW_upf100_uspp_Fe/STRU
  tests/integrate/101_PW_upf100_uspp_Fe/jd
  tests/integrate/101_PW_upf100_uspp_Fe/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Features Needed

#4154 Enhance PSI Constructor: Lower Peak Device Memory Usage
  source/module_psi/psi.cpp
Labels: GPU & DCU & HPC

#4157 Update ESolver
  source/driver.cpp
  source/driver_run.cpp
  source/module_esolver/esolver.h
  source/module_esolver/esolver_dp.cpp
  source/module_esolver/esolver_dp.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_lj.cpp
  source/module_esolver/esolver_lj.h
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_esolver/test/esolver_dp_test.cpp
  source/module_md/md_func.cpp
  source/module_md/test/fire_test.cpp
  source/module_md/test/langevin_test.cpp
  source/module_md/test/lj_pot_test.cpp
  source/module_md/test/msst_test.cpp
  source/module_md/test/nhchain_test.cpp
  source/module_md/test/verlet_test.cpp
  source/module_relax/relax_driver.cpp
Labels: The Absolute Zero

#3561 Feature: Add PEXSI Support for Gamma Only LCAO Calculation
  CMakeLists.txt
  cmake/FindPEXSI.cmake
  docs/advanced/input_files/input-main.md
  docs/advanced/install.md
  examples/pexsi/md_Si8/INPUT
  examples/pexsi/md_Si8/KPT
  examples/pexsi/md_Si8/STRU
  examples/pexsi/scf_Si64/INPUT
  examples/pexsi/scf_Si64/KPT
  examples/pexsi/scf_Si64/STRU
  examples/pexsi/scf_spin_Fe2/INPUT
  examples/pexsi/scf_spin_Fe2/KPT
  examples/pexsi/scf_spin_Fe2/STRU
  source/Makefile
  source/Makefile.Objects
  source/Makefile.vars
  source/module_base/global_function.h
  source/module_basis/module_ao/ORB_control.cpp
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_lcao.h
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/module_dm/density_matrix.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma_edm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_odelta.cpp
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diago_pexsi.cpp
  source/module_hsolver/diago_pexsi.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/module_pexsi/CMakeLists.txt
  source/module_hsolver/module_pexsi/dist_bcd_matrix.cpp
  source/module_hsolver/module_pexsi/dist_bcd_matrix.h
  source/module_hsolver/module_pexsi/dist_ccs_matrix.cpp
  source/module_hsolver/module_pexsi/dist_ccs_matrix.h
  source/module_hsolver/module_pexsi/dist_matrix_transformer.cpp
  source/module_hsolver/module_pexsi/dist_matrix_transformer.h
  source/module_hsolver/module_pexsi/pexsi_solver.cpp
  source/module_hsolver/module_pexsi/pexsi_solver.h
  source/module_hsolver/module_pexsi/simple_pexsi.cpp
  source/module_hsolver/module_pexsi/simple_pexsi.h
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/PEXSI-DM-GammaOnly-Si2.dat
  source/module_hsolver/test/PEXSI-H-GammaOnly-Si2.dat
  source/module_hsolver/test/PEXSI-S-GammaOnly-Si2.dat
  source/module_hsolver/test/diago_pexsi_parallel_test.sh
  source/module_hsolver/test/diago_pexsi_test.cpp
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/input_conv.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/test/input_conv_test.cpp
  source/module_io/test/input_test_para.cpp
  source/module_io/test/write_input_test.cpp
  source/module_io/write_input.cpp
Labels: Features Needed

#4152 Refactor: SphericalBesselTransformer cleanup
  source/module_base/spherical_bessel_transformer.cpp
  source/module_base/spherical_bessel_transformer.h
  source/module_base/test/spherical_bessel_transformer_test.cpp
  source/module_basis/module_nao/numerical_radial.cpp
  source/module_basis/module_nao/numerical_radial.h
  source/module_basis/module_nao/test/numerical_radial_test.cpp
  source/module_basis/module_nao/two_center_bundle.cpp
Labels: Refactor

#4114 Refactor: more light-weighted formatter library
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_base/formatter.h
  source/module_base/formatter_contextfmt.cpp
  source/module_base/formatter_contextfmt.h
  source/module_base/formatter_fmt.cpp
  source/module_base/formatter_fmt.h
  source/module_base/formatter_physfmt.cpp
  source/module_base/formatter_physfmt.h
  source/module_base/formatter_table.cpp
  source/module_base/formatter_table.h
  source/module_base/ndarray.h
  source/module_base/test/CMakeLists.txt
  source/module_base/test/formatter_contextfmt_test.cpp
  source/module_base/test/formatter_fmt_test.cpp
  source/module_base/test/formatter_physfmt_test.cpp
  source/module_base/test/formatter_table_test.cpp
  source/module_base/test/formatter_test.cpp
  source/module_base/test/ndarray_test.cpp
  source/module_base/timer.cpp
  source/module_basis/module_ao/test/CMakeLists.txt
  source/module_basis/module_pw/test/CMakeLists.txt
  source/module_basis/module_pw/test/Makefile
  source/module_cell/klist.cpp
  source/module_cell/read_atoms.cpp
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/unitcell.h
  source/module_elecstate/elecstate_print.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_hamilt_general/module_xc/test/CMakeLists.txt
  source/module_hamilt_lcao/module_deltaspin/basic_funcs.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.cpp
  source/module_hamilt_lcao/module_deltaspin/test/basic_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/cal_mw_helper_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/lambda_loop_helper_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/spin_constrain_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt
  source/module_io/nscf_band.cpp
  source/module_io/output_log.cpp
  source/module_io/test/outputlog_test.cpp
  source/module_io/test_serial/nscf_band_test.cpp
  source/module_io/write_HS.hpp
  source/module_md/run_md.cpp
  source/module_md/test/CMakeLists.txt
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_new/test/CMakeLists.txt
  source/module_relax/relax_new/test/relax_test.h
  tests/integrate/207_NO_KP_OH/data-1-H.ref
  tests/integrate/207_NO_KP_OH/data-1-S.ref
  tests/integrate/307_NO_GO_OH/data-0-H.ref
  tests/integrate/307_NO_GO_OH/data-0-S.ref
Labels: Input&Output

#4084 Fix: enable out_mat_r in nscf calculation
  source/module_esolver/esolver_ks_lcao_elec.cpp
  tests/integrate/207_NO_KP_OH_nscf/INPUT
  tests/integrate/207_NO_KP_OH_nscf/KPT
  tests/integrate/207_NO_KP_OH_nscf/SPIN1_CHG.cube
  tests/integrate/207_NO_KP_OH_nscf/STRU
  tests/integrate/207_NO_KP_OH_nscf/data-SR-sparse_SPIN0.csr.ref
  tests/integrate/207_NO_KP_OH_nscf/data-TR-sparse_SPIN0.csr.ref
  tests/integrate/207_NO_KP_OH_nscf/data-rR-sparse.csr.ref
  tests/integrate/207_NO_KP_OH_nscf/jd
  tests/integrate/207_NO_KP_OH_nscf/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Input&Output

#4129 Test: supplementary use of Memory::record to record memory
  source/module_base/mathzone_add1.cpp
  source/module_base/module_container/ATen/core/tensor.cpp
  source/module_base/module_container/ATen/core/tensor.h
  source/module_base/module_container/ATen/core/tensor_buffer.h
  source/module_base/module_mixing/broyden_mixing.cpp
  source/module_base/module_mixing/broyden_mixing.h
  source/module_basis/module_nao/two_center_table.cpp
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_elecstate/module_charge/charge_mixing.cpp
  source/module_elecstate/module_charge/symmetry_rhog.cpp
  source/module_elecstate/potentials/H_Hartree_pw.cpp
  source/module_hamilt_general/module_xc/xc_functional_gradcorr.cpp
  source/module_hamilt_general/module_xc/xc_functional_vxc.cpp
  source/module_hamilt_lcao/module_gint/gint_fvl.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma_env.cpp
  source/module_hamilt_lcao/module_gint/gint_k_env.cpp
  source/module_hamilt_lcao/module_gint/gint_rho.cpp
  source/module_hamilt_lcao/module_gint/gint_tau.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.cpp
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_nl.cpp
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp
Labels: High Priority

#4137 Feature : loading equivariant deepks model
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_fdelta.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp
  tests/deepks/604_NO_deepks_ut_CH4_gamma/H_V_delta_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/H_V_deltaR_ref.dat
Labels: Features Needed

#3840 [Test] zdot_real_op (and some other math ops) benchmark on cpu
  source/module_hsolver/kernels/test/CMakeLists.txt
  source/module_hsolver/kernels/test/perf_math_kernel.cpp
Labels: GPU & DCU & HPC

#4150 Fix HR output in tddft
  source/Makefile.Objects
  source/module_elecstate/potentials/H_TDDFT_pw.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_nonlocal_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_nonlocal_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.h
  source/module_hamilt_lcao/module_tddft/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/td_velocity.cpp
  source/module_hamilt_lcao/module_tddft/td_velocity.h
  source/module_io/input_conv.cpp
  source/module_io/td_current_io.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/write_HS_sparse.cpp
Labels: Input&Output

#4164 Replace GlobalC in module_gint
  source/module_elecstate/elecstate_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/grid_init.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_fvl.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma.h
  source/module_hamilt_lcao/module_gint/gint_gamma_env.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_env.cpp
  source/module_hamilt_lcao/module_gint/gint_k_pvpr.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_hamilt_lcao/module_gint/gint_rho.cpp
  source/module_hamilt_lcao/module_gint/gint_tau.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.cpp
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/grid_bigcell.cpp
  source/module_hamilt_lcao/module_gint/grid_bigcell.h
  source/module_hamilt_lcao/module_gint/grid_meshcell.cpp
  source/module_hamilt_lcao/module_gint/grid_meshcell.h
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/kernels/cuda/vbatch_matrix_mul.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/vbatch_matrix_mul.cuh
  source/module_io/istate_envelope.cpp
Labels: The Absolute Zero

#4172 refactor: remove template on relax_driver
  source/driver_run.cpp
  source/module_esolver/esolver.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_of.h
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_driver.h
Labels: The Absolute Zero

#3943 Feature: set OpenMP thread num to a proper default value
  docs/quick_start/easy_install.md
  source/module_base/global_variable.cpp
  source/module_base/parallel_global.cpp
  source/module_cell/test/parallel_kpoints_test.cpp
Labels: Compile & CICD

#4207 Refactor: clean up BLACS initialization in Parallel_2D
  source/module_base/blacs_connector.h
  source/module_basis/module_ao/parallel_2d.cpp
Labels: Refactor

#4229 Refactor: Remove unused function `Gint_Gamma::vl_grid_to_2D` and related variables
  source/Makefile.Objects
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_gint/gint_gamma.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma.h
  source/module_hamilt_lcao/module_gint/gint_gamma_vl.cpp
Labels: The Absolute Zero

#4233 Refactor: rename diago_blas to diago_scalapack
  source/Makefile.Objects
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diago_scalapack.cpp
  source/module_hsolver/diago_scalapack.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/diago_lcao_cusolver_test.cpp
  source/module_hsolver/test/diago_lcao_test.cpp
Labels: The Absolute Zero

#4173 Feature: Input and output vector potential in tddft calculation
  docs/advanced/input_files/input-main.md
  source/module_elecstate/potentials/H_TDDFT_pw.cpp
  source/module_elecstate/potentials/H_TDDFT_pw.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_nonlocal_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.h
  source/module_hamilt_lcao/module_tddft/td_velocity.cpp
  source/module_hamilt_lcao/module_tddft/td_velocity.h
  source/module_io/input.cpp
  source/module_io/input.h
  source/module_io/input_conv.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/write_HS_sparse.cpp
Labels: Features Needed

#4185 Feature: a better looking of SCF iteration information on screen
  source/module_base/test/timer_test.cpp
  source/module_base/timer.cpp
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
Labels: Input&Output

#4210 Perf: split code_gen.cpp to reduce compilation time
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_00.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_01.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_02.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_03.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_04.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_05.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_06.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_07.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_08.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/code_gen_09.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gemm_selector.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gemm_selector.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/vbatch_matrix_mul.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/vbatch_matrix_mul.cuh
Labels: GPU & DCU & HPC

#4236 Modify the input file of examples/interface_wannier90 to run the Wannier90 interface correctly.
  examples/interface_wannier90/ABACUS_towannier90_lcao/INPUT-nscf
  examples/interface_wannier90/ABACUS_towannier90_lcao/INPUT-scf
  examples/interface_wannier90/ABACUS_towannier90_lcao/diamond.win
  examples/interface_wannier90/ABACUS_towannier90_lcao_in_pw/INPUT-nscf
  examples/interface_wannier90/ABACUS_towannier90_lcao_in_pw/INPUT-scf
  examples/interface_wannier90/ABACUS_towannier90_lcao_in_pw/diamond.win
  examples/interface_wannier90/ABACUS_towannier90_pw/INPUT-nscf
  examples/interface_wannier90/ABACUS_towannier90_pw/diamond.win
Labels: Features Needed

#4200 replace `cal_stress` in GPU relax calculation，use NUM_STREAM in INPUT file and fix memory leak in force calculation
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint_force.h
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu
Labels: Bug Report (Exclude input and output)

#4211 Refactor: remove all globalV in diago_david
  source/module_hsolver/diagh.h
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
Labels: The Absolute Zero

#4191 Perf: optimize single-process performence of cusolver
  source/module_hsolver/diago_cusolver.cpp
Labels: GPU & DCU & HPC

#4252 Fix: add one whitespaces between each column of scf stdout
  source/module_elecstate/elecstate_print.cpp
Labels: Input&Output

#4237 Refactor: simplified Parallel_2d interface
  source/module_base/blacs_connector.h
  source/module_base/scalapack_connector.h
  source/module_base/test/CMakeLists.txt
  source/module_base/test/blacs_connector_test.cpp
  source/module_base/test_parallel/CMakeLists.txt
  source/module_base/test_parallel/blacs_connector_test.cpp
  source/module_base/test_parallel/blacs_connector_test.sh
  source/module_basis/module_ao/ORB_control.cpp
  source/module_basis/module_ao/parallel_2d.cpp
  source/module_basis/module_ao/parallel_2d.h
  source/module_basis/module_ao/parallel_orbitals.cpp
  source/module_basis/module_ao/parallel_orbitals.h
  source/module_basis/module_ao/test/parallel_2d_test.cpp
  source/module_basis/module_ao/test/parallel_orbitals_test.cpp
  source/module_elecstate/module_dm/test/test_cal_dm_R.cpp
  source/module_elecstate/module_dm/test/test_cal_dmk_psi.cpp
  source/module_elecstate/module_dm/test/test_dm_R_init.cpp
  source/module_elecstate/module_dm/test/test_dm_constructor.cpp
  source/module_elecstate/module_dm/test/test_dm_io.cpp
  source/module_esolver/io_npz.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_T_NL_cd.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_dftu.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_ekineticnew.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_nonlocalnew.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_overlapnew.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_overlapnew_cd.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_sc_lambda_lcao.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp
  source/module_hamilt_lcao/module_deltaspin/test/cal_h_lambda_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/cal_mw_helper_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/spin_constrain_test.cpp
  source/module_hamilt_lcao/module_hcontainer/atom_pair.cpp
  source/module_hamilt_lcao/module_hcontainer/atom_pair.h
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_complex.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_output.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_readCSR.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_transfer.cpp
  source/module_hamilt_lcao/module_tddft/bandenergy.h
  source/module_hamilt_lcao/module_tddft/middle_hamilt.h
  source/module_hamilt_lcao/module_tddft/norm_psi.h
  source/module_hamilt_lcao/module_tddft/propagator.h
  source/module_hamilt_lcao/module_tddft/test/bandenergy_test.cpp
  source/module_hamilt_lcao/module_tddft/test/middle_hamilt_test.cpp
  source/module_hamilt_lcao/module_tddft/test/norm_psi_test.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test1.cpp
  source/module_hamilt_lcao/module_tddft/test/upsi_test1.cpp
  source/module_hamilt_lcao/module_tddft/upsi.h
  source/module_io/single_R_io.h
  source/module_io/test/single_R_io_test.cpp
  source/module_io/test_serial/read_wfc_nao_test.cpp
  source/module_io/write_Vxc.hpp
Labels: Refactor
