Repository deepmodeling/abacus-develop, pull requests merged in 2024-06, with the labels that each got.

#4280 Perf: Incorporate OpenMP in the force and rho computations on the GPU
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
Labels: GPU & DCU & HPC

#4285 Remove Unused `chg_extrap = dm` INPUT Parameter Code
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_io/input.cpp
  source/module_io/test/input_test.cpp
Labels: The Absolute Zero

#4281 Refactor Separate the coupled GPU task functions.
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint_force.h
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho.h
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl.h
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/gtask_rho.cpp
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu
Labels: GPU & DCU & HPC

#4326 Perf: optimize psir_dot function in gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_force_gpu.h
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.h
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.h
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/gtask_rho.cpp
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_vl.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/vbatch_matrix_mul.cuh
Labels: GPU & DCU & HPC

#4330 Refactor: redesign the constructor and member variables of davsubspace class
  examples/scf/pw_Si2/INPUT
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/hsolver_pw.cpp
Labels: The Absolute Zero

#4295 Perf: Optimize `hsolver` GPU code
  source/module_hsolver/kernels/cuda/math_kernel_op.cu
Labels: GPU & DCU & HPC

#4336 Update write_potential and "others" function in ESolver
  source/Makefile.Objects
  source/driver_run.cpp
  source/module_elecstate/elecstate_energy.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_io/CMakeLists.txt
  source/module_io/output_potential.cpp
  source/module_io/write_cube.cpp
  source/module_io/write_pot.cpp
  source/module_io/write_pot.h
  tests/integrate/107_PW_CHG_mismatch/SPIN2_CHG.cube
  tests/integrate/107_PW_OBOD_MemSaver/SPIN1_CHG.cube
  tests/integrate/107_PW_OB_outputbands/SPIN1_CHG.cube
  tests/integrate/107_PW_OD_outputdos/SPIN1_CHG.cube
  tests/integrate/107_PW_OK/INPUT
  tests/integrate/107_PW_OK/SPIN1_CHG.cube.ref
  tests/integrate/107_PW_OK/SPIN1_TAU.cube.ref
  tests/integrate/107_PW_W90/SPIN1_CHG.cube
  tests/integrate/117_PW_out_pot/refSPIN1_POT.cube
  tests/integrate/118_PW_WFC_BINARY/SPIN1_CHG.cube
  tests/integrate/186_PW_NSCF_KG_100/SPIN1_CHG.cube
  tests/integrate/186_PW_SDOS_MALL/SPIN1_CHG.cube
  tests/integrate/186_PW_SKG_10D10S/SPIN1_CHG.cube
  tests/integrate/201_NO_15_f_pseudopots/refElecStaticPot.cube
  tests/integrate/207_NO_KP_OB/SPIN1_CHG.cube
  tests/integrate/207_NO_KP_OD/SPIN1_CHG.cube
  tests/integrate/207_NO_KP_OH_nscf/SPIN1_CHG.cube
  tests/integrate/207_NO_OK/SPIN1_CHG.cube.ref
  tests/integrate/207_NO_OK/SPIN1_TAU.cube.ref
  tests/integrate/217_NO_out_pot/refSPIN1_POT.cube
  tests/integrate/tools/catch_properties.sh
Labels: The Absolute Zero

#4343 refactor: remove the usused LOC in getForceStress
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
Labels: Refactor

#4350 Modify the average electrostatic potential script
  tools/average_pot/README
  tools/average_pot/aveElecStatPot.py
Labels: Features Needed

#4347 Refactor: replace cudamalloc and cudafree with cuda_mem_wrapper
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_force_gpu.h
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.h
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.h
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/gtask_rho.cpp
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_vl.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_vl.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/interp.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/sph.cuh
  source/module_hamilt_lcao/module_gint/test/test_sph.cu
Labels: GPU & DCU & HPC

#4348 Fix: report error when fr-uspp used in linear calculations
  source/module_cell/read_pp.cpp
  source/module_cell/test/read_pp_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.cpp
Labels: Bug Report (Exclude input and output)

#4346 Refactor: Remove DiagoIterAssist dependencies in DiagoDavid
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_hsolver/test/hsolver_pw_sup.h
Labels: The Absolute Zero

#4225 CI: add pre-commit.ci to apply clang-format and clang-tidy fixes
  .clang-format
  .clang-tidy
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/CONTRIBUTING.md
  source/driver.cpp
  source/driver.h
Labels: Compile & CICD

#4331 Refactor: add alternatives to functions `LOWF::gamma_file` and `LOWF::allocate_k`
  source/Makefile.Objects
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_wfc.cpp
  source/module_io/CMakeLists.txt
  source/module_io/read_wfc_lcao.cpp
  source/module_io/read_wfc_lcao.h
  source/module_io/read_wfc_nao.cpp
  source/module_io/test/CMakeLists.txt
  source/module_io/test/read_wfc_lcao_test.cpp
  source/module_io/test/support/WFC_NAO_GAMMA1.txt
  source/module_io/test/support/WFC_NAO_K1.txt
  source/module_io/test/support/WFC_NAO_K2.txt
  source/module_io/test/support/WFC_NAO_K3.txt
  source/module_io/test/support/WFC_NAO_K4.txt
Labels: Refactor

#4355 Refactor: remove Kubo-Greenwood and DOS functions from esolver
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_esolver/esolver_sdft_pw_tool.cpp
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/elecond.cpp
  source/module_hamilt_pw/hamilt_pwdft/elecond.h
  source/module_hamilt_pw/hamilt_stodft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_stodft/sto_dos.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_dos.h
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.h
  source/module_hamilt_pw/hamilt_stodft/sto_tool.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_tool.h
  source/module_hamilt_pw/hamilt_stodft/test/CMakeLists.txt
  source/module_hamilt_pw/hamilt_stodft/test/test_sto_tool.cpp
  tests/integrate/186_PW_SKG_10D10S/refOnsager.txt
  tests/integrate/186_PW_SNLKG_10D10S/refOnsager.txt
Labels: The Absolute Zero

#4361 Perf: remove unnecessary sync for cuda ops
  source/module_base/kernels/cuda/math_op.cu
  source/module_base/kernels/rocm/math_op.hip.cu
  source/module_base/module_container/ATen/kernels/cuda/lapack.cu
  source/module_base/module_container/ATen/kernels/cuda/linalg.cu
  source/module_base/module_container/ATen/kernels/cuda/memory.cu
  source/module_base/module_container/base/macros/cuda.h
  source/module_base/module_container/base/macros/rocm.h
  source/module_base/module_device/cuda/memory_op.cu
  source/module_base/module_device/rocm/memory_op.hip.cu
  source/module_basis/module_pw/fft.cpp
  source/module_basis/module_pw/kernels/cuda/pw_op.cu
  source/module_basis/module_pw/kernels/rocm/pw_op.hip.cu
  source/module_elecstate/kernels/cuda/elecstate_op.cu
  source/module_elecstate/kernels/rocm/elecstate_op.hip.cu
  source/module_hamilt_general/module_xc/kernels/cuda/xc_functional_op.cu
  source/module_hamilt_general/module_xc/kernels/rocm/xc_functional_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/global.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/ekinetic_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/force_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/meta_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/nonlocal_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/veff_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/vnl_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/wf_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/ekinetic_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/force_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/meta_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/nonlocal_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/veff_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/vnl_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/wf_op.hip.cu
  source/module_hsolver/kernels/cuda/math_kernel_op.cu
  source/module_hsolver/kernels/rocm/math_kernel_op.hip.cu
Labels: GPU & DCU & HPC

#4383 Test: use origin python in test.yml to support numpy
  .github/workflows/test.yml
Labels: Compile & CICD

#4384 CI: enable clang-tidy in CI by pre-commit-config
  .pre-commit-config.yaml
Labels: Compile & CICD

#4390 CI: add clang-tidy `readability-braces-around-statements` setting
  .clang-tidy
Labels: Compile & CICD

#4391 Refactor: delete some useless files in `module_psi/kernel/` folder
  source/module_base/kernels/test/math_op_test.cpp
  source/module_base/math_ylmreal.cpp
  source/module_basis/module_pw/kernels/test/pw_op_test.cpp
  source/module_elecstate/kernels/test/elecstate_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/ekinetic_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/force_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/meta_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/nonlocal_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/stress_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/veff_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/vnl_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/wf_op_test.cpp
  source/module_hsolver/diago_bpcg.h
  source/module_hsolver/kernels/cuda/math_kernel_op.cu
  source/module_hsolver/kernels/rocm/math_kernel_op.hip.cu
  source/module_hsolver/kernels/test/math_dngvd_test.cpp
  source/module_hsolver/kernels/test/math_kernel_test.cpp
  source/module_hsolver/kernels/test/perf_math_kernel.cpp
  source/module_psi/kernels/cuda/memory_op.cu
  source/module_psi/kernels/device.cpp
  source/module_psi/kernels/device.h
  source/module_psi/kernels/memory_op.h
  source/module_psi/kernels/psi_memory_op.cpp
  source/module_psi/kernels/rocm/memory_op.hip.cu
  source/module_psi/kernels/test/CMakeLists.txt
  source/module_psi/kernels/test/device_test.cpp
  source/module_psi/kernels/test/memory_test.cpp
  source/module_psi/kernels/types.h
  source/module_psi/psi.h
Labels: The Absolute Zero

#4392 Refactor `istate_charge.cpp` using new DensityMatrix class
  source/module_elecstate/module_dm/cal_dm_psi.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_io/istate_charge.cpp
  source/module_io/istate_charge.h
Labels: The Absolute Zero

#4400 Update LCAO_matrix and related functions and delete LCAO_gen_fixedH
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/io_npz.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_gen_fixedH.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_gen_fixedH.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nl_beta.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nl_mu.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_fs.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fedm_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fedm_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/ftvnl_dphi_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/ftvnl_dphi_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fvl_dphi_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fvl_dphi_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/grid_init.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.h
  source/module_io/output_mat_sparse.cpp
  source/module_io/output_mat_sparse.h
  source/module_io/td_current_io.cpp
  source/module_io/td_current_io.h
  source/module_io/write_HS_R.cpp
  source/module_io/write_HS_R.h
  source/module_io/write_dos_lcao.cpp
Labels: The Absolute Zero

#4389 Add several warning quits in `DensityMatrix` and `Gint` when parameters are not initialized
  source/module_elecstate/module_dm/density_matrix.cpp
  source/module_hamilt_lcao/module_gint/gint.cpp
Labels: Refactor

#4407 delete 31 double arrays in LCAO_matrix, add a new class named force_stress_arrays.h used in force and stress calcualtions
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nl_mu.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fedm_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fedm_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/force_stress_arrays.h
  source/module_hamilt_lcao/hamilt_lcaodft/ftvnl_dphi_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/ftvnl_dphi_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_hamilt_lcao/module_dftu/dftu.cpp
  source/module_hamilt_lcao/module_dftu/dftu.h
  source/module_hamilt_lcao/module_dftu/dftu_folding.cpp
  source/module_hamilt_lcao/module_dftu/dftu_force.cpp
  source/module_io/td_current_io.cpp
  source/module_io/td_current_io.h
Labels: The Absolute Zero

#4398 Refactor: Initial removal of Hamilt from diag_once func in Davsubspace
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/hsolver_pw.cpp
Labels: The Absolute Zero

#4356 Perf: reduce data transmission in the GPU code of module_gint
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_force_gpu.h
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.h
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.h
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/gtask_rho.cpp
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_rho.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_vl.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_vl.cuh
Labels: GPU & DCU & HPC

#4405 Adding comments and modifying properties in the PW module
  source/module_basis/module_pw/fft.h
  source/module_basis/module_pw/pw_basis.cpp
  source/module_relax/relax_old/lattice_change_cg.cpp
Labels: Refactor

#4408 Refactor: remove useless function from wavefunc
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.h
  source/module_io/unk_overlap_lcao.cpp
Labels: The Absolute Zero

#4414 Refactor: move snap_psibeta_half_tddft to module_tddft
  source/Makefile.Objects
  source/module_basis/module_ao/ORB_gen_tables.cpp
  source/module_basis/module_ao/ORB_gen_tables.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_nonlocal_lcao.cpp
  source/module_hamilt_lcao/module_tddft/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/snap_psibeta_half_tddft.cpp
  source/module_hamilt_lcao/module_tddft/snap_psibeta_half_tddft.h
Labels: Refactor

#4416 Refactor: Initial removal of psi::Psi<T, Device> from Diago_DavSubspace
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
Labels: The Absolute Zero

#4353 Use Vector to replace new and delete in gint，spilt gint_tools and change Makefile,remove ORB in gint
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nnr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_gint/cal_ddpsir_ylm.cpp
  source/module_hamilt_lcao/module_gint/cal_dpsir_ylm.cpp
  source/module_hamilt_lcao/module_gint/cal_psir_ylm.cpp
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_gamma.h
  source/module_hamilt_lcao/module_gint/gint_gamma_env.cpp
  source/module_hamilt_lcao/module_gint/gint_gamma_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_env.cpp
  source/module_hamilt_lcao/module_gint/gint_k_pvpr.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
  source/module_hamilt_lcao/module_gint/grid_bigcell.cpp
  source/module_hamilt_lcao/module_gint/grid_bigcell.h
  source/module_hamilt_lcao/module_gint/grid_meshball.cpp
  source/module_hamilt_lcao/module_gint/grid_meshball.h
  source/module_hamilt_lcao/module_gint/grid_meshcell.cpp
  source/module_hamilt_lcao/module_gint/grid_meshcell.h
  source/module_hamilt_lcao/module_gint/grid_meshk.cpp
  source/module_hamilt_lcao/module_gint/grid_meshk.h
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/init_orb.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dm.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dm_new.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
  source/module_io/istate_envelope.cpp
  source/module_io/output_dm.cpp
  source/module_io/unk_overlap_lcao.cpp
Labels: The Absolute Zero

#4415 Refactor: delete some variables of LCAO_Matrix
  source/Makefile.Objects
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_HS_arrays.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nl_mu.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nnr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_set_zero.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_io/td_current_io.cpp
Labels: The Absolute Zero

#4374 refactor: output sparse DMR by Output_HContainer instead of output_dm1.h/cpp
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.h
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_output.cpp
  source/module_hamilt_lcao/module_hcontainer/test/test_hcontainer_readCSR.cpp
  source/module_io/CMakeLists.txt
  source/module_io/output_dm1.cpp
  source/module_io/output_dm1.h
  source/module_io/write_dm_sparse.cpp
  source/module_io/write_dm_sparse.h
  source/module_io/write_dmr.cpp
  source/module_io/write_dmr.h
  tests/integrate/201_NO_15_f_pseudopots/refdata-DMR-sparse_SPIN0.csr
Labels: Refactor

#4426 CI: fix precommit failure
  .github/workflows/test.yml
Labels: Compile & CICD

#4419 Build: disable build libm by default
  CMakeLists.txt
Labels: Compile & CICD

#4434 Refactor: remove the dependency of `Hloc_fixedR` from LCAO_Matrix.
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.h
  source/module_io/write_HS_R.cpp
Labels: The Absolute Zero

#4446 Refactor: delete some unused functions in `LCAO_Matrix`
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h
Labels: The Absolute Zero

#4440 add function get_global_row/col_size() in parallel_2d
  source/module_basis/module_ao/parallel_2d.cpp
  source/module_basis/module_ao/parallel_2d.h
  source/module_basis/module_ao/test/parallel_2d_test.cpp
Labels: Refactor

#4456 refactor: remove the useless DM_R in Gint_inout
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_lcao_tddft.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
Labels: The Absolute Zero

#4465 refactor: replace LOC.ParaV-> by orb_con.ParaV. in ESolver_KS_LCAO_TDFT
  source/module_esolver/esolver_ks_lcao_tddft.cpp
Labels: The Absolute Zero

#4466 Add INPUT parameter `bands_to_print` for `get_wf` calculation
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_io/istate_envelope.cpp
  source/module_io/istate_envelope.h
Labels: The Absolute Zero

#4467 delete sparse file and Optimize global memory access
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cu
  source/module_hamilt_lcao/module_gint/kernels/cuda/gint_force.cuh
  source/module_hamilt_lcao/module_gint/kernels/cuda/interp.cuh
Labels: The Absolute Zero

#4453 add cusolvermp lib to ABACUS and edit gint to adopt multicards, use for multi node multi cards
  CMakeLists.txt
  source/module_base/global_function.h
  source/module_base/module_device/device.cpp
  source/module_base/module_device/device.h
  source/module_basis/module_ao/ORB_control.cpp
  source/module_elecstate/elecstate_lcao.cpp
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_wfc.cpp
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diago_cusolvermp.cpp
  source/module_hsolver/diago_cusolvermp.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/kernels/cuda/diag_cusolvermp.cu
  source/module_hsolver/kernels/cuda/diag_cusolvermp.cuh
  source/module_hsolver/kernels/cuda/helper_cusolver.h
  source/module_io/input.cpp
  source/module_io/write_input.cpp
Labels: GPU & DCU & HPC

#4450 test: support reading threshold from file 'threshold' in integrate test
  tests/integrate/Autotest.sh
Labels: Compile & CICD

#4463 Fix: bug in mulliken output
  source/module_cell/test/unitcell_test_para.cpp
  source/module_cell/unitcell.cpp
Labels: Bug Report (Exclude input and output)

#4468 Refactor: remove the use of LOWF in istate_envelope
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_charge.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_wfc.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_wfc.h
  source/module_io/istate_envelope.cpp
  source/module_io/istate_envelope.h
  source/module_io/read_wfc_lcao.cpp
Labels: The Absolute Zero

#4469 Refactor: remove the LOWF class from ABACUS code
  source/Makefile.Objects
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_lcao.h
  source/module_elecstate/elecstate_lcao_tddft.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/DM_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_charge.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_charge.h
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_wfc.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_wfc.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/module_gint/gint_gamma_vl.cpp
  source/module_hamilt_lcao/module_tddft/evolve_elec.cpp
  source/module_hamilt_lcao/module_tddft/evolve_elec.h
  source/module_hsolver/diago_lapack.cpp
  source/module_io/berryphase.cpp
  source/module_io/berryphase.h
  source/module_io/istate_envelope.h
  source/module_io/read_wfc_nao.cpp
  source/module_io/read_wfc_nao.h
  source/module_io/td_current_io.h
  source/module_io/test/write_wfc_nao_test.cpp
  source/module_io/to_wannier90_lcao.h
  source/module_io/to_wannier90_lcao_in_pw.h
  source/module_io/unk_overlap_lcao.cpp
  source/module_io/unk_overlap_lcao.h
Labels: The Absolute Zero

#4476 refactor: remove LOC in istate_charge
  source/module_esolver/esolver_ks_lcao_elec.cpp
  source/module_hamilt_lcao/module_gint/gint_rho.cpp
  source/module_io/istate_charge.cpp
  source/module_io/istate_charge.h
Labels: The Absolute Zero

#4447 feature: add function get_nbasis in class HContainer
  source/module_hamilt_lcao/module_hcontainer/hcontainer.h
Labels: Refactor

#4488 CI: modify clang-tidy setting
  .clang-tidy
Labels: Compile & CICD

#4492 Fix: address memory leak with single precision
  source/module_esolver/esolver_ks_pw.cpp
Labels: Bug Report (Exclude input and output)

#4047 Refactor: use less memory and optimize performance to calculate force and stress in pw base
  source/Makefile.Objects
  source/module_base/module_device/cuda/memory_op.cu
  source/module_base/module_device/memory_op.cpp
  source/module_base/module_device/rocm/memory_op.hip.cu
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/forces_nl.cpp
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.cpp
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/force_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/vnl_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/vnl_tools_cu.hpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/force_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/force_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/force_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/vnl_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/force_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/vnl_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/vnl_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/vnl_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/vnl_tools.hpp
  source/module_hamilt_pw/hamilt_pwdft/nonlocal_maths.hpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_nl.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_us.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_pw.h
  source/module_hamilt_pw/hamilt_stodft/sto_stress_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_stress_pw.h
  source/module_hsolver/diago_cg.cpp
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/hsolver_pw.cpp
Labels: Features Needed

#4485 Refactor: remove ORB_table_beta & ORB_table_alpha and decouple center2_orb-orb & module_io from ORB_table_phi
  source/Makefile.Objects
  source/module_basis/module_ao/CMakeLists.txt
  source/module_basis/module_ao/ORB_control.cpp
  source/module_basis/module_ao/ORB_gen_tables.cpp
  source/module_basis/module_ao/ORB_gen_tables.h
  source/module_basis/module_ao/ORB_table_alpha.cpp
  source/module_basis/module_ao/ORB_table_alpha.h
  source/module_basis/module_ao/ORB_table_beta.cpp
  source/module_basis/module_ao/ORB_table_beta.h
  source/module_basis/module_ao/ORB_table_phi.cpp
  source/module_basis/module_ao/ORB_table_phi.h
  source/module_basis/module_ao/README
  source/module_basis/module_ao/test/CMakeLists.txt
  source/module_basis/module_ao/test/ORB_table_phi_test.cpp
  source/module_basis/module_ao/test/ORB_unittest.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb11.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb11.h
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb21.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb21.h
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb22.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/center2_orb-orb22.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_io/cal_r_overlap_R.cpp
  source/module_io/cal_r_overlap_R.h
  source/module_io/to_wannier90_lcao.cpp
  source/module_io/to_wannier90_lcao.h
  source/module_io/unk_overlap_lcao.cpp
  source/module_io/unk_overlap_lcao.h
  source/module_ri/Matrix_Orbs11.cpp
  source/module_ri/Matrix_Orbs21.cpp
  source/module_ri/Matrix_Orbs22.cpp
Labels: The Absolute Zero

#4512 CI: Remove unused workflow
  .github/workflows/cuda.yml
  .github/workflows/static.yaml
  docs/community/cicd.md
Labels: Compile & CICD

#4497 Fix: move Vxc output from after_scf to after_all_runners
  source/module_esolver/esolver_ks_lcao.cpp
Labels: Refactor

#4506 fix: no STRU_ION_1 file output
  source/module_relax/relax_driver.cpp
  tests/integrate/108_PW_RE_NEW/INPUT
  tests/integrate/108_PW_RE_NEW/STRU_ION1_D.ref
  tests/integrate/108_PW_RE_NEW/result.ref
Labels: Input&Output

#4520 Refactor: remove pdiagh pointer and redundant code
  source/module_hsolver/hsolver_pw.cpp
Labels: The Absolute Zero
