Repository deepmodeling/abacus-develop, pull requests merged in 2024-11, with the labels that each got.

#5377 Fix: force and stress calculation with noncollinear-spin or SOC for PW code
  source/module_hamilt_general/module_xc/xc_functional_gradcorr.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_nl.cpp
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/force_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/nonlocal_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/force_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/force_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/force_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/nonlocal_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.h
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/force_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/stress_op_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_kin.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_loc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_nl.cpp
  tests/integrate/104_PW_NC_magnetic/INPUT
  tests/integrate/104_PW_NC_magnetic/KPT
  tests/integrate/104_PW_NC_magnetic/STRU
  tests/integrate/104_PW_NC_magnetic/jd
  tests/integrate/104_PW_NC_magnetic/result.ref
  tests/integrate/140_PW_15_SO/INPUT
  tests/integrate/140_PW_15_SO/KPT
  tests/integrate/140_PW_15_SO/result.ref
Labels: Features Needed

#5384 Test: unit test for read/write_cube
  source/module_io/test_serial/rho_io_test.cpp
  source/module_io/test_serial/support/SPIN1_CHG.cube
Labels: Refactor

#5388 Fix: widen the range of support on STRU file of Molden interface
  tools/molden/molden.py
Labels: Refactor

#5390 Feature: change the default value of `ecutwfc` based on basis_type
  docs/advanced/input_files/input-main.md
  source/module_io/read_input_item_system.cpp
  source/module_parameter/input_parameter.h
Labels: Refactor

#5392 Fix: disable four rarely used functionals which involves the laplacian of rho
  source/module_hamilt_general/module_xc/xc_functional_libxc.cpp
Labels: Refactor

#5396 Fix cal_edm_tddft
  source/module_esolver/cal_edm_tddft.cpp
  tests/integrate/601_NO_TDDFT_H2_kpoint/result.ref
  tests/integrate/601_NO_TDDFT_H2_len_gauss/result.ref
  tests/integrate/601_NO_TDDFT_H2_len_gauss_dire/result.ref
  tests/integrate/601_NO_TDDFT_H2_len_heavi/result.ref
  tests/integrate/601_NO_TDDFT_H2_len_hhg/result.ref
  tests/integrate/601_NO_TDDFT_H2_len_trape/result.ref
  tests/integrate/601_NO_TDDFT_H2_len_trigo/result.ref
  tests/integrate/601_NO_TDDFT_H2_oldedm/INPUT
  tests/integrate/601_NO_TDDFT_H2_oldedm/result.ref
  tests/integrate/601_NO_TDDFT_graphene_kpoint/result.ref
Labels: Bugs

#5398 Feature: Add `CG` algorithm to `pyabacus.hsolver`
  python/pyabacus/examples/diago_matrix.py
  python/pyabacus/src/hsolver/CMakeLists.txt
  python/pyabacus/src/hsolver/py_diago_cg.hpp
  python/pyabacus/src/hsolver/py_hsolver.cpp
  python/pyabacus/src/pyabacus/hsolver/__init__.py
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
  python/pyabacus/tests/test_hsolver.py
Labels: pyabacus

#5382 Docs: Add Chinese wiki page link to README
  README.md
Labels: Compile & CICD & Docs & Dependencies

#5399 Feature: apply CG eigensolver to LR-TDDFT
  docs/advanced/input_files/input-main.md
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/diago_iter_assist.h
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/hsolver_lrtd.hpp
Labels: Refactor

#5391 Fix: disable the XC in LibXC in which nonlocal dispersion correction is required
  source/module_hamilt_general/module_xc/xc_functional_libxc.cpp
Labels: Refactor

#5361 Feature: Optimized memory management on DSP
  source/module_base/blas_connector.cpp
  source/module_base/kernels/dsp/dsp_connector.h
  source/module_base/module_device/memory_op.cpp
  source/module_base/module_device/memory_op.h
  source/module_base/module_device/types.h
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_psi/psi.h
Labels: GPU & DCU & HPC

#5378 Feature: build-in DFTD3 parameters
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_hamilt_general/module_vdw/dftd3_xc_name.h
  source/module_hamilt_general/module_vdw/dftd3_xc_param.h
  source/module_hamilt_general/module_vdw/test/CMakeLists.txt
  source/module_hamilt_general/module_vdw/test/dftd3_xc_test.cpp
  source/module_hamilt_general/module_vdw/vdw.cpp
  source/module_hamilt_general/module_vdw/vdw.h
  source/module_hamilt_general/module_vdw/vdwd2_parameters.cpp
  source/module_hamilt_general/module_vdw/vdwd2_parameters.h
  source/module_hamilt_general/module_vdw/vdwd3.cpp
  source/module_hamilt_general/module_vdw/vdwd3_parameters.cpp
  source/module_hamilt_general/module_vdw/vdwd3_parameters.h
  source/module_hamilt_general/module_xc/xc_functional_libxc.h
  source/module_io/read_input_item_model.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  tests/integrate/150_PW_15_CR_VDW3/INPUT
  tests/integrate/250_NO_KP_CR_VDW3/INPUT
  tests/integrate/250_NO_KP_CR_VDW3ABC/INPUT
  tests/integrate/250_NO_KP_CR_VDW3BJ/INPUT
Labels: Features Needed

#5412 Fix: not build useless library without ENABLE_LCAO
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_hcontainer/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/CMakeLists.txt
Labels: Compile & CICD & Docs & Dependencies

#5413 Refactor: wrap exx-routine in `iter_finish` into `Exx_LRI_Interface`
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_ri/Exx_LRI_interface.h
  source/module_ri/Exx_LRI_interface.hpp
Labels: The Absolute Zero

#5416 Refactor: remove useless functions in esolver
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_of.h
Labels: The Absolute Zero

#5418 Fix: update the example of vdwd3 acoording to the latest impl.
  examples/vdw/si2-vdwd2/INPUT1
  examples/vdw/si2-vdwd2/INPUT2
  examples/vdw/si2-vdwd2/KPT
  examples/vdw/si2-vdwd2/STRU
  examples/vdw/si2-vdwd2/c6.txt
  examples/vdw/si2-vdwd2/run.sh
  examples/vdw/si2-vdwd3/INPUT1
  examples/vdw/si2-vdwd3/INPUT2
  examples/vdw/si2-vdwd3/INPUT3
  examples/vdw/si2-vdwd3/KPT
  examples/vdw/si2-vdwd3/STRU
  examples/vdw/si2-vdwd3/run.sh
Labels: Features Needed

#5421 Feature: enable ABACUS can finish SCF if charge density oscillation is found
  docs/advanced/input_files/input-main.md
  source/module_elecstate/module_charge/charge_mixing.cpp
  source/module_elecstate/module_charge/charge_mixing.h
  source/module_elecstate/test/charge_mixing_test.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_io/read_input_item_elec_stru.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test/support/INPUT
  source/module_parameter/input_parameter.h
Labels: Features Needed

#5426 Refactor: refactor iter_finish and iter_init
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
Labels: The Absolute Zero

#5381 Fix&Refactor: soc force/stress error for LCAO code, refactor the force/stress code into operator
  source/Makefile.Objects
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/module_dm/density_matrix.cpp
  source/module_elecstate/module_dm/density_matrix.h
  source/module_elecstate/module_dm/density_matrix_io.cpp
  source/module_elecstate/module_dm/test/CMakeLists.txt
  source/module_elecstate/module_dm/test/test_cal_dm_R.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_init_basis.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/edm.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_new.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_new.h
  source/module_lr/dm_trans/dmr_complex.cpp
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/result.ref
  tests/integrate/240_NO_KP_15_SO/INPUT
  tests/integrate/240_NO_KP_15_SO/KPT
  tests/integrate/240_NO_KP_15_SO/STRU
  tests/integrate/240_NO_KP_15_SO/result.ref
  tests/integrate/260_NO_DJ_PK_PU_SO/result.ref
  tests/integrate/308_NO_GO_CF_RE/result.ref
  tests/integrate/320_NO_GO_MD_NVT/result.ref
  tests/integrate/934_NO_Si2_dzp_neq_GPU/result.ref
  tests/integrate/934_NO_Si2_dzp_neq_ns2_GPU/result.ref
  tests/integrate/934_NO_Si2_tzdp_neq_GPU/result.ref
  tests/integrate/934_NO_Si2_tzdp_neq_ns2_GPU/result.ref
Labels: Refactor

#5380 Feature: add interface `Gint::psir_func`
  source/module_base/array_pool.h
  source/module_hamilt_lcao/module_gint/cal_psir_ylm.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_rho.cpp
  source/module_hamilt_lcao/module_gint/gint_rho_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
Labels: Refactor

#5431 Integration test: Rename folders for consistency with `get_pchg` and `get_wf`
  tests/integrate/212_NO_wfc_get_wf/INPUT
  tests/integrate/212_NO_wfc_get_wf/KPT
  tests/integrate/212_NO_wfc_get_wf/STRU
  tests/integrate/212_NO_wfc_get_wf/WFC_NAO_K1.txt
  tests/integrate/212_NO_wfc_get_wf/WFC_NAO_K2.txt
  tests/integrate/212_NO_wfc_get_wf/jd
  tests/integrate/212_NO_wfc_get_wf/result.ref
  tests/integrate/312_NO_GO_wfc_get_pchg/INPUT
  tests/integrate/312_NO_GO_wfc_get_pchg/KPT
  tests/integrate/312_NO_GO_wfc_get_pchg/STRU
  tests/integrate/312_NO_GO_wfc_get_pchg/WFC_NAO_GAMMA1.txt
  tests/integrate/312_NO_GO_wfc_get_pchg/jd
  tests/integrate/312_NO_GO_wfc_get_pchg/result.ref
  tests/integrate/312_NO_GO_wfc_get_wf/INPUT
  tests/integrate/312_NO_GO_wfc_get_wf/KPT
  tests/integrate/312_NO_GO_wfc_get_wf/STRU
  tests/integrate/312_NO_GO_wfc_get_wf/WFC_NAO_GAMMA1.txt
  tests/integrate/312_NO_GO_wfc_get_wf/jd
  tests/integrate/312_NO_GO_wfc_get_wf/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Refactor

#5423 Feature：Now sDFT support GPU
  python/pyabacus/src/ModuleBase/CMakeLists.txt
  python/pyabacus/src/ModuleNAO/CMakeLists.txt
  source/CMakeLists.txt
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_base/blas_connector.cpp
  source/module_base/blas_connector.h
  source/module_base/math_chebyshev.cpp
  source/module_base/math_chebyshev.h
  source/module_base/module_container/CMakeLists.txt
  source/module_base/module_device/cuda/memory_op.cu
  source/module_base/module_device/memory_op.cpp
  source/module_base/parallel_device.h
  source/module_base/test/CMakeLists.txt
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/elecstate_pw.h
  source/module_elecstate/elecstate_pw_sdft.cpp
  source/module_elecstate/elecstate_pw_sdft.h
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/kernels/cuda/hpsi_norm_op.cu
  source/module_hamilt_pw/hamilt_stodft/kernels/hpsi_norm_op.cpp
  source/module_hamilt_pw/hamilt_stodft/kernels/hpsi_norm_op.h
  source/module_hamilt_pw/hamilt_stodft/kernels/rocm/hpsi_norm_op.hip.cu
  source/module_hamilt_pw/hamilt_stodft/sto_che.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_che.h
  source/module_hamilt_pw/hamilt_stodft/sto_dos.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.h
  source/module_hamilt_pw/hamilt_stodft/sto_wf.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_wf.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/kernels/math_kernel_op.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: GPU & DCU & HPC

#5445 Refactor: runner() of esolver_ks
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
Labels: The Absolute Zero

#5427 Code: divide charge_mixing.cpp into some files
  source/Makefile.Objects
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/module_charge/charge_mixing.cpp
  source/module_elecstate/module_charge/charge_mixing.h
  source/module_elecstate/module_charge/charge_mixing_dmr.cpp
  source/module_elecstate/module_charge/charge_mixing_preconditioner.cpp
  source/module_elecstate/module_charge/charge_mixing_residual.cpp
  source/module_elecstate/module_charge/charge_mixing_rho.cpp
  source/module_elecstate/module_charge/charge_mixing_uspp.cpp
  source/module_elecstate/test/CMakeLists.txt
Labels: The Absolute Zero

#5456 Fix R-index mismatch in lr_util_hcontainer
  source/module_lr/utils/lr_util_hcontainer.cpp
  tests/integrate/291_NO_KP_LR/result.ref
Labels: EXX

#5410 Refactor:Replace the current fft with templates and polymorphism
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_basis/module_pw/CMakeLists.txt
  source/module_basis/module_pw/fft.cpp
  source/module_basis/module_pw/module_fft/fft_base.cpp
  source/module_basis/module_pw/module_fft/fft_base.h
  source/module_basis/module_pw/module_fft/fft_bundle.cpp
  source/module_basis/module_pw/module_fft/fft_bundle.h
  source/module_basis/module_pw/module_fft/fft_cpu.cpp
  source/module_basis/module_pw/module_fft/fft_cpu.h
  source/module_basis/module_pw/module_fft/fft_cpu_float.cpp
  source/module_basis/module_pw/pw_basis.cpp
  source/module_basis/module_pw/pw_basis.h
  source/module_basis/module_pw/pw_basis_k.cpp
  source/module_basis/module_pw/pw_basis_sup.cpp
  source/module_basis/module_pw/pw_transform.cpp
  source/module_basis/module_pw/pw_transform_k.cpp
  source/module_basis/module_pw/test/CMakeLists.txt
  source/module_basis/module_pw/test/Makefile
  source/module_basis/module_pw/test_serial/CMakeLists.txt
  source/module_elecstate/module_charge/charge.cpp
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_hamilt_general/module_xc/test/CMakeLists.txt
  source/module_hsolver/test/hsolver_pw_sup.h
Labels: Features Needed, Refactor

#5455 Refactor: remove nscf()
  source/Makefile.Objects
  source/driver_run.cpp
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_lcao.h
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/elecstate_pw_sdft.cpp
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/pw_fun.cpp
  source/module_esolver/pw_nscf.cpp
  source/module_esolver/pw_others.cpp
  source/module_hsolver/hsolver.cpp
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_io/read_input_item_elec_stru.cpp
  source/module_io/read_input_item_system.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  tests/integrate/101_PW_15_f_pseudopots/log
Labels: The Absolute Zero

#5469 Fix: let the coverage test pass without checking for its correctness
  .github/workflows/coverage.yml
Labels: Compile & CICD & Docs & Dependencies

#5475 Refactor: move io_npz to ModuleIO
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/lcao_before_scf.cpp
  source/module_io/CMakeLists.txt
  source/module_io/io_npz.cpp
  source/module_io/io_npz.h
Labels: The Absolute Zero

#5488 Fix: compile cuda without openmp
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
Labels: GPU & DCU & HPC

#5485 Refactor: move cal_edm_tddft to module_dm
  source/Makefile.Objects
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/module_dm/cal_edm_tddft.cpp
  source/module_elecstate/module_dm/cal_edm_tddft.h
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
Labels: The Absolute Zero

#5481 Refactor: remove lcao_fun.cpp
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/lcao_fun.cpp
  source/module_io/output_mat_sparse.cpp
  source/module_io/output_mat_sparse.h
  source/module_io/output_mulliken.h
Labels: The Absolute Zero

#5495 Update esolver_ks.h
  source/module_esolver/esolver_ks.h
Labels: The Absolute Zero

#5494 Update esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.cpp
Labels: The Absolute Zero

#5496 Update esolver_ks_lcao_tddft.h
  source/module_esolver/esolver_ks_lcao_tddft.h
Labels: The Absolute Zero

#5491 Fix GPU memory recorder's memory leak
  source/module_base/memory.cpp
Labels: Bugs

#5498 Update esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.cpp
Labels: The Absolute Zero

#5499 Fix: nscf for hse
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_before_scf.cpp
Labels: The Absolute Zero

#5504 Tests: supplementing some tests with OPENMP check directives
  source/module_base/module_mixing/test/mixing_test.cpp
  source/module_elecstate/test/charge_mixing_test.cpp
Labels: GPU & DCU & HPC

#5490 Refactor: replace pvpr with hcontainer
  source/Makefile.Objects
  source/module_esolver/set_matrix_grid.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nnr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_gpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_pvdpr.cpp
  source/module_hamilt_lcao/module_gint/gint_k_pvpr.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.h
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_hcontainer/base_matrix.h
  source/module_hamilt_lcao/module_hcontainer/hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/hcontainer.h
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/utils/gint_move.hpp
Labels: GPU & DCU & HPC

#5509 Fix: provide more information on 2d process grid error message
  source/module_basis/module_ao/parallel_orbitals.cpp
Labels: Compile & CICD & Docs & Dependencies

#5508 Refactor:Add cuda support for fft_bundle
  source/module_basis/module_pw/CMakeLists.txt
  source/module_basis/module_pw/module_fft/fft_base.h
  source/module_basis/module_pw/module_fft/fft_bundle.cpp
  source/module_basis/module_pw/module_fft/fft_bundle.h
  source/module_basis/module_pw/module_fft/fft_cpu_float.cpp
  source/module_basis/module_pw/module_fft/fft_cuda.cpp
  source/module_basis/module_pw/module_fft/fft_cuda.h
  source/module_basis/module_pw/module_fft/fft_rcom.cpp
  source/module_basis/module_pw/module_fft/fft_rcom.h
  source/module_basis/module_pw/pw_basis.cpp
  source/module_basis/module_pw/pw_basis.h
  source/module_basis/module_pw/pw_basis_k.cpp
  source/module_basis/module_pw/pw_basis_sup.cpp
  source/module_basis/module_pw/pw_transform_k.cpp
  source/module_basis/module_pw/test_serial/pw_basis_k_test.cpp
  source/module_basis/module_pw/test_serial/pw_basis_test.cpp
  source/module_elecstate/test/charge_extra_test.cpp
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_hamilt_general/module_xc/test/CMakeLists.txt
  source/module_hsolver/test/hsolver_pw_sup.h
Labels: Features Needed

#5512 Refactor: move dftu_cal_occup_m to dftu
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/dftu_cal_occup_m.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.h
  source/module_hamilt_lcao/module_dftu/dftu.cpp
  source/module_hamilt_lcao/module_dftu/dftu.h
Labels: The Absolute Zero

#5517 Fix: fix the compilation failure with DFTD3 autoset implementation
  source/Makefile.Objects
  source/module_hamilt_general/module_vdw/CMakeLists.txt
  source/module_hamilt_general/module_vdw/dftd3_xc_name.h
  source/module_hamilt_general/module_vdw/dftd3_xc_param.h
  source/module_hamilt_general/module_vdw/test/CMakeLists.txt
  source/module_hamilt_general/module_vdw/test/dftd3_xc_test.cpp
  source/module_hamilt_general/module_vdw/vdwd3_autoset_xcname.cpp
  source/module_hamilt_general/module_vdw/vdwd3_autoset_xcparam.cpp
  source/module_hamilt_general/module_vdw/vdwd3_parameters.cpp
  source/module_hamilt_general/module_vdw/vdwd3_parameters.h
  source/module_hamilt_general/module_xc/xc_functional_libxc.cpp
Labels: Compile & CICD & Docs & Dependencies, Refactor

#5506 Fix: fix a bug of `relax_nmax` default
  docs/advanced/input_files/input-main.md
  source/module_io/read_input_item_relax.cpp
  source/module_parameter/input_parameter.h
Labels: Input&Output

#5511 Fix: init nonlocal beta orbitals only when necessary
  source/module_basis/module_nao/two_center_bundle.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_init_basis.cpp
Labels: Bugs, Refactor

#5474 Refactor: refactor the relevant code for psi initializer
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/wfinit.cpp
  source/module_hamilt_pw/hamilt_pwdft/wfinit.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: The Absolute Zero

#5525 Update gint.h
  source/module_hamilt_lcao/module_gint/gint.h
Labels: The Absolute Zero

#5524 Fix: set zero for unused psi data for nspin4
  source/module_hamilt_pw/hamilt_pwdft/wf_atomic.cpp
Labels: Refactor

#5531 Refactor: merge before_all_runners of tddft and lcao
  source/Makefile.Objects
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/elecstate_lcao_tddft.cpp
  source/module_elecstate/elecstate_lcao_tddft.h
  source/module_esolver/esolver_gets.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
Labels: The Absolute Zero

#5540 Fix: recover the use of -1 value of out_chg
  source/module_io/read_input_item_output.cpp
Labels: Input&Output, Refactor

#5545 fix bug: change Mixing_Data::length from int to size_t
  source/module_base/module_mixing/mixing_data.cpp
  source/module_base/module_mixing/mixing_data.h
  source/module_base/module_mixing/pulay_mixing.cpp
Labels: Bugs, Refactor

#5393 Feature: LR-TDDFT support reading fxc from file or calculating fxc by a specified charge file
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_io/read_input_item_tddft.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_lr/CMakeLists.txt
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/lr_spectrum.cpp
  source/module_lr/operator_casida/operator_lr_hxc.cpp
  source/module_lr/potentials/kernel.h
  source/module_lr/potentials/kernel_xc.cpp
  source/module_lr/potentials/pot_hxc_lrtd.cpp
  source/module_lr/potentials/pot_hxc_lrtd.h
  source/module_lr/potentials/xc_kernel.cpp
  source/module_lr/potentials/xc_kernel.h
  source/module_lr/utils/gint_move.hpp
  source/module_lr/utils/lr_util.cpp
  source/module_lr/utils/lr_util.h
  source/module_lr/utils/lr_util.hpp
  source/module_lr/utils/lr_util_xc.hpp
  source/module_lr/utils/test/CMakeLists.txt
  source/module_parameter/input_parameter.h
Labels: Features Needed

#5546 Refactor atom_input and unify the fake atom data structure of grid and atom_input
  source/module_cell/module_neighbor/sltk_atom.h
  source/module_cell/module_neighbor/sltk_atom_input.cpp
  source/module_cell/module_neighbor/sltk_atom_input.h
  source/module_cell/module_neighbor/sltk_grid.cpp
  source/module_cell/module_neighbor/sltk_grid.h
  source/module_cell/module_neighbor/sltk_grid_driver.cpp
  source/module_cell/module_neighbor/sltk_grid_driver.h
  source/module_cell/module_neighbor/test/sltk_atom_test.cpp
Labels: Refactor

#5547 Refactor: remove init_after_vc
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_init_after_vc.cpp
  source/module_esolver/pw_init_after_vc.cpp
  source/module_lr/esolver_lrtd_lcao.h
Labels: The Absolute Zero

#5558 Refactor: remove set_matrix_grid
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/set_matrix_grid.cpp
Labels: The Absolute Zero

#5559 Refactor: remove pw_init_globalc.cpp
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/pw_init_globalc.cpp
Labels: The Absolute Zero

#5560 Refactor: remove dpks_cal_e_delta_band.cpp
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/dpks_cal_e_delta_band.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
Labels: The Absolute Zero

#5551 Update init_orb.cpp
  source/module_hamilt_lcao/module_gint/init_orb.cpp
Labels: The Absolute Zero

#5550 Update gint_gamma.h
  source/module_hamilt_lcao/module_gint/gint_gamma.h
Labels: The Absolute Zero

#5552 Update mult_psi_dmr.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
Labels: The Absolute Zero

#5557 Refactor: remove `init_wfc`&`mem_saver`&`out_wfc_pw`&`out_wfc_r` of wavefunc in abacus
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.h
  source/module_hamilt_pw/hamilt_pwdft/wfinit.cpp
  source/module_hamilt_pw/hamilt_pwdft/wfinit.h
  source/module_ri/exx_lip.h
  source/module_ri/exx_lip.hpp
Labels: The Absolute Zero

#5568 Refactor: remove some unused variables in module_gint
  source/module_base/vector3.h
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_gamma_env.cpp
  source/module_hamilt_lcao/module_gint/gint_k_env.cpp
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/grid_index.h
  source/module_hamilt_lcao/module_gint/grid_meshcell.h
  source/module_hamilt_lcao/module_gint/grid_meshk.cpp
  source/module_hamilt_lcao/module_gint/grid_meshk.h
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/gtask_rho.cpp
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
Labels: The Absolute Zero

#5569 Refactor: remove GlobalC::ucell in esolver
  source/driver.cpp
  source/driver.h
  source/driver_run.cpp
  source/module_base/opt_TN.hpp
  source/module_cell/unitcell.cpp
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver.h
  source/module_esolver/esolver_dp.cpp
  source/module_esolver/esolver_dp.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_gets.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_lj.cpp
  source/module_esolver/esolver_lj.h
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_esolver/esolver_of_interface.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/pw_others.cpp
  source/module_esolver/test/esolver_dp_test.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/esolver_lrtd_lcao.h
  source/module_md/md_func.cpp
  source/module_md/test/fire_test.cpp
  source/module_md/test/langevin_test.cpp
  source/module_md/test/lj_pot_test.cpp
  source/module_md/test/msst_test.cpp
  source/module_md/test/nhchain_test.cpp
  source/module_md/test/verlet_test.cpp
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_driver.h
Labels: The Absolute Zero

#5586 Fix: EXX suports restart scf from HexxR.csr produced by `out_chg`
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.hpp
  source/module_ri/Exx_LRI_interface.hpp
Labels: Refactor

#5580 Update LCAO_hamilt.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_hamilt.hpp
Labels: The Absolute Zero

#5581 Update overlap_new.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/overlap_new.cpp
Labels: The Absolute Zero

#5584 Update operator_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.h
Labels: The Absolute Zero

#5592 Refactor: move tmp charge density output to esolver_ks
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
Labels: The Absolute Zero

#5593 Refactor: remove template for get_S
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_gets.h
Labels: The Absolute Zero

#5595 Feature: set relax_nmax=0 to enable dry run
  docs/advanced/input_files/input-main.md
  source/module_io/read_input_item_relax.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_parameter/input_parameter.h
Labels: Features Needed, The Absolute Zero

#5563 update the DCU compile
  source/module_base/module_device/rocm/memory_op.hip.cu
  source/module_basis/module_pw/CMakeLists.txt
  source/module_basis/module_pw/module_fft/fft_bundle.cpp
  source/module_basis/module_pw/module_fft/fft_rocm.cpp
  source/module_basis/module_pw/module_fft/fft_rocm.h
Labels: Compile & CICD & Docs & Dependencies

#5600 Refactor: split sum_stoband to sum_stoband and cal_storho in sDFT
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: Refactor

#5599 Grid batching by adapted cut-plane
  source/module_base/blas_connector.h
  source/module_base/grid/batch.cpp
  source/module_base/grid/batch.h
  source/module_base/grid/test/CMakeLists.txt
  source/module_base/grid/test/test_batch.cpp
Labels: Features Needed

#5601 Refactor: move psiinit file to hsolver folder
  CMakeLists.txt
  source/Makefile.Objects
  source/module_esolver/esolver_ks_pw.h
  source/module_hamilt_lcao/module_deepks/test/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_psi/CMakeLists.txt
  source/module_psi/psi_init.cpp
  source/module_psi/psi_init.h
  source/module_ri/exx_lip.hpp
Labels: The Absolute Zero

#5608 Refactor: Remove `cal_ux` from UnitCell.
  source/Makefile.Objects
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/cal_ux.cpp
  source/module_elecstate/cal_ux.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_general/module_xc/test/test_xc3.cpp
  source/module_hamilt_general/module_xc/test/test_xc5.cpp
  source/module_hamilt_general/module_xc/test/xc3_mock.h
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_cc.cpp
Labels: The Absolute Zero

#5614 Feature: enable get_s for nspin=4
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver_gets.cpp
  source/module_io/write_HS_R.cpp
Labels: Features Needed, The Absolute Zero

#5613 Refactor: move wf_atomic and wavefunc files
  source/module_esolver/esolver_ks.h
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/test/hsolver_pw_sup.h
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_io/test/for_testing_input_conv.h
  source/module_io/write_dos_lcao.cpp
  source/module_psi/CMakeLists.txt
  source/module_psi/psi_init.h
  source/module_psi/wavefunc.cpp
  source/module_psi/wavefunc.h
  source/module_psi/wf_atomic.cpp
  source/module_psi/wf_atomic.h
  source/module_ri/exx_lip.hpp
Labels: The Absolute Zero

#5609 Refactor: remove #include hsolver.h
  source/module_esolver/esolver_ks.h
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hsolver/hsolver.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_lcao.h
  source/module_hsolver/hsolver_lcaopw.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_lr/esolver_lrtd_lcao.h
Labels: The Absolute Zero

#5556 refactor: modify the default return value of warning quit to 1
  source/module_base/module_mixing/test/mixing_test.cpp
  source/module_base/test/complexarray_test.cpp
  source/module_base/test/global_function_test.cpp
  source/module_base/test/math_chebyshev_test.cpp
  source/module_base/test/matrix_test.cpp
  source/module_base/test/tool_check_test.cpp
  source/module_base/test/tool_quit_test.cpp
  source/module_base/tool_quit.cpp
  source/module_basis/module_ao/test/ORB_read_test.cpp
  source/module_basis/module_pw/test/test-other.cpp
  source/module_cell/module_neighbor/test/sltk_atom_input_test.cpp
  source/module_cell/test/cell_index_test.cpp
  source/module_cell/test/klist_test.cpp
  source/module_cell/test/read_pp_test.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_readpp.cpp
  source/module_cell/test/unitcell_test_setupcell.cpp
  source/module_elecstate/test/charge_extra_test.cpp
  source/module_elecstate/test/charge_mixing_test.cpp
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_elecstate/test/elecstate_fp_energy_test.cpp
  source/module_elecstate/test/elecstate_occupy_test.cpp
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_elecstate/test/potential_new_test.cpp
  source/module_esolver/test/esolver_dp_test.cpp
  source/module_hamilt_general/module_vdw/test/vdw_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/spin_constrain_test.cpp
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/test/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/test/soc_test.cpp
  source/module_io/test/file_reader_test.cpp
  source/module_io/test/read_wfc_pw_test.cpp
  source/module_io/test/sparse_matrix_test.cpp
  source/module_io/test_serial/io_dmk_test.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_md/test/md_func_test.cpp
  source/module_relax/relax_new/test/line_search_test.cpp
  source/module_relax/relax_old/test/bfgs_basic_test.cpp
  source/module_relax/relax_old/test/ions_move_bfgs_test.cpp
  source/module_relax/relax_old/test/ions_move_sd_test.cpp
Labels: Refactor

#5611 Feature: output mat of <phi|r|phi> with get_S
  source/module_esolver/esolver_gets.cpp
Labels: Features Needed

#5325 add RDMFT(Reduced Density Matrix Functional Theory) code
  CMakeLists.txt
  docs/advanced/input_files/input-main.md
  source/CMakeLists.txt
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/lcao_before_scf.cpp
  source/module_hamilt_general/module_xc/xc_functional.cpp
  source/module_hamilt_general/module_xc/xc_functional.h
  source/module_hamilt_general/module_xc/xc_functional_libxc.cpp
  source/module_hamilt_general/module_xc/xc_functional_libxc.h
  source/module_hamilt_general/module_xc/xc_functional_libxc_vxc.cpp
  source/module_hamilt_general/module_xc/xc_functional_vxc.cpp
  source/module_io/input_conv.cpp
  source/module_io/read_input_item_exx_dftu.cpp
  source/module_io/read_input_item_other.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_parameter/input_parameter.h
  source/module_rdmft/CMakeLists.txt
  source/module_rdmft/rdmft.cpp
  source/module_rdmft/rdmft.h
  source/module_rdmft/rdmft_pot.cpp
  source/module_rdmft/rdmft_tools.cpp
  source/module_rdmft/rdmft_tools.h
  source/module_rdmft/update_state_rdmft.cpp
  source/module_ri/Exx_LRI.h
  source/module_ri/Exx_LRI_interface.hpp
  source/module_ri/conv_coulomb_pot_k.cpp
  source/module_ri/conv_coulomb_pot_k.h
  tests/integrate/1001_NO_Si2_dzp_rdmft/INPUT
  tests/integrate/1001_NO_Si2_dzp_rdmft/KPT
  tests/integrate/1001_NO_Si2_dzp_rdmft/STRU
  tests/integrate/1001_NO_Si2_dzp_rdmft/jd
  tests/integrate/1001_NO_Si2_dzp_rdmft/result.ref
  tests/integrate/1002_NO_H2_dzp_rdmft/INPUT
  tests/integrate/1002_NO_H2_dzp_rdmft/KPT
  tests/integrate/1002_NO_H2_dzp_rdmft/STRU
  tests/integrate/1002_NO_H2_dzp_rdmft/jd
  tests/integrate/1002_NO_H2_dzp_rdmft/result.ref
  tests/integrate/1003_NO_Hsoilds_dzp_rdmft/INPUT
  tests/integrate/1003_NO_Hsoilds_dzp_rdmft/KPT
  tests/integrate/1003_NO_Hsoilds_dzp_rdmft/STRU
  tests/integrate/1003_NO_Hsoilds_dzp_rdmft/jd
  tests/integrate/1003_NO_Hsoilds_dzp_rdmft/result.ref
  tests/integrate/1004_NO_H_dzp_rdmft/INPUT
  tests/integrate/1004_NO_H_dzp_rdmft/KPT
  tests/integrate/1004_NO_H_dzp_rdmft/STRU
  tests/integrate/1004_NO_H_dzp_rdmft/jd
  tests/integrate/1004_NO_H_dzp_rdmft/result.ref
  tests/integrate/1005_NO_Mg_dzp_rdmft/INPUT
  tests/integrate/1005_NO_Mg_dzp_rdmft/KPT
  tests/integrate/1005_NO_Mg_dzp_rdmft/STRU
  tests/integrate/1005_NO_Mg_dzp_rdmft/jd
  tests/integrate/1005_NO_Mg_dzp_rdmft/result.ref
  tests/integrate/CASES_CPU.txt
  tests/integrate/tools/catch_properties.sh
Labels: Features Needed

#5636 Fix low efficiency of stress_kin in DCU
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
Labels: GPU & DCU & HPC

#5630 Refactor: remove GlocalC::ucell in elecstate_energy_terms.cpp
  source/Makefile.Objects
  source/module_elecstate/elecstate_energy_terms.cpp
  source/module_hamilt_general/module_surchem/CMakeLists.txt
  source/module_hamilt_general/module_surchem/cal_vcav.cpp
  source/module_hamilt_general/module_surchem/cal_vel.cpp
  source/module_hamilt_general/module_surchem/corrected_energy.cpp
  source/module_hamilt_general/module_surchem/surchem.h
Labels: The Absolute Zero

#5626 Refactor:Remove GlobalC::ucell in module_cell
  source/module_cell/cell_index.h
  source/module_cell/klist.cpp
  source/module_cell/klist.h
  source/module_cell/test/klist_test.cpp
  source/module_cell/test/klist_test_para.cpp
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_of.cpp
  source/module_io/test/print_info_test.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
Labels: The Absolute Zero

#5621 docs: update SR docs
  docs/advanced/elec_properties/hs_matrix.md
  docs/advanced/elec_properties/position_matrix.md
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_gets.h
Labels: Compile & CICD & Docs & Dependencies

#5634 Test: check if abacus end normally in CI test
  tests/integrate/Autotest.sh
  tests/integrate/CASES_CPU.txt
Labels: Compile & CICD & Docs & Dependencies

#5628 Update rdmft.h
  source/module_rdmft/rdmft.h
Labels: Refactor

#5629 Update rdmft_tools.cpp
  source/module_rdmft/rdmft_tools.cpp
Labels: Refactor

#5632 Update esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.cpp
Labels: The Absolute Zero

#5637 Refactor: Move `if (PARAM.inp.nspin == 4)` into `cal_ux(ucell)`.
  source/module_cell/test/unitcell_test.cpp
  source/module_elecstate/cal_ux.cpp
  source/module_elecstate/cal_ux.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_cc.cpp
Labels: The Absolute Zero

#5649 Refactor:Remove GlobalC::ucell in module_lcaodft
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/grid_init.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/record_adj.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/record_adj.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.h
  source/module_hamilt_lcao/hamilt_lcaodft/wavefunc_in_pw.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/wavefunc_in_pw.h
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_io/output_mat_sparse.cpp
  source/module_io/write_HS_R.cpp
  source/module_io/write_HS_R.h
Labels: The Absolute Zero

#5652 Fix a segfault in LR-TDDFT when nspin=1
  source/module_lr/esolver_lrtd_lcao.cpp
Labels: Bugs, EXX and lr-TDDFT

#5651 Update elecstate_pw.h
  source/module_elecstate/elecstate_pw.h
Labels: The Absolute Zero
