Repository deepmodeling/abacus-develop, pull requests merged in 2024-09, with the labels that each got.

#5037 Perf: optimize the openmp strategy in calculate_HR
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_nonlocal_lcao.cpp
Labels: Performance

#5040 Refactor:Replace GlobalV::KSPACING with PARAM.inp.kspacing.
  source/module_base/global_variable.cpp
  source/module_base/global_variable.h
  source/module_cell/klist.cpp
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/klist_test.cpp
  source/module_io/input_conv.cpp
  source/module_io/test/CMakeLists.txt
Labels: The Absolute Zero

#4969 add elpa native to solver generate eigen
  docs/advanced/acceleration/cuda.md
  source/Makefile.Objects
  source/module_base/global_function.h
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_print.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.cpp
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diago_elpa_native.cpp
  source/module_hsolver/diago_elpa_native.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_io/input_conv.cpp
  source/module_io/read_input_item_elec_stru.cpp
Labels: GPU & DCU & HPC

#5023 Fix&Refactor: support naive and complete CIF file I/O interface
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_cell/module_symmetry/symmetry.h
  source/module_cell/print_cif.cpp
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/unitcell.h
  source/module_esolver/esolver_dp.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_lj.cpp
  source/module_esolver/test/CMakeLists.txt
  source/module_esolver/test/esolver_dp_test.cpp
  source/module_io/CMakeLists.txt
  source/module_io/cif_io.cpp
  source/module_io/cif_io.h
  source/module_io/test/CMakeLists.txt
  source/module_io/test/cif_io_test.cpp
  source/module_md/test/CMakeLists.txt
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_new/test/relax_test.h
Labels: Input&Output

#5041 Perf: optimize function snap_psibeta_half_tddft
  source/module_base/math_polyint.cpp
  source/module_hamilt_lcao/module_tddft/snap_psibeta_half_tddft.cpp
Labels: Performance

#5050 Feature: add rescaling parameter into dp
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_dp.cpp
  source/module_esolver/esolver_dp.h
  source/module_io/read_input_item_md.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test/support/INPUT
  source/module_parameter/md_parameter.h
Labels: Features Needed

#5046 Fix: fix the issue that `out_chg -1` not really work
  source/module_io/read_input_item_output.cpp
  source/module_io/rhog_io.cpp
Labels: Input&Output

#5056 Refactor: remove GlobalC::ORB from module_io
  source/module_esolver/dpks_cal_e_delta_band.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_fun.cpp
  source/module_esolver/lcao_gets.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/set_matrix_grid.cpp
  source/module_io/berryphase.cpp
  source/module_io/berryphase.h
  source/module_io/cal_r_overlap_R.cpp
  source/module_io/cal_r_overlap_R.h
  source/module_io/output_mat_sparse.cpp
  source/module_io/output_mat_sparse.h
  source/module_io/to_wannier90_lcao.cpp
  source/module_io/to_wannier90_lcao.h
  source/module_io/to_wannier90_lcao_in_pw.cpp
  source/module_io/unk_overlap_lcao.cpp
  source/module_io/unk_overlap_lcao.h
Labels: The Absolute Zero

#5054 Refactor: remove useless code about phsol
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.h
  source/module_hamilt_lcao/module_deltaspin/test/spin_constrain_test.cpp
Labels: The Absolute Zero

#5049 Fix: Assert the mesh of <PP_BETA> not exceeding pp.mesh.
  source/module_cell/read_pp_upf100.cpp
Labels: The Absolute Zero

#5058 Refactor: remove `out_mat_dh`, `out_mat_t`, `out_mat_hsR`, `out_mat_hs` from HSolverLCAO
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/lcao_fun.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.cpp
  source/module_hsolver/hsolver_lcao.h
  source/module_io/input_conv.cpp
Labels: The Absolute Zero

#5071 Fix: fix a cuda runtime error introduced by PR #5061
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
Labels: GPU & DCU & HPC

#5068 Refactor: remove GlobalC::ORB in module_hamilt_lcao
  source/module_basis/module_ao/ORB_read.cpp
  source/module_basis/module_ao/ORB_read.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_gets.cpp
  source/module_esolver/set_matrix_grid.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_init_basis.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nnr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/grid_init.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/record_adj.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/record_adj.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_st.h
  source/module_hamilt_lcao/module_dftu/dftu.cpp
  source/module_hamilt_lcao/module_dftu/dftu.h
  source/module_hamilt_lcao/module_dftu/dftu_folding.cpp
  source/module_hamilt_lcao/module_dftu/dftu_yukawa.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/init_orb.cpp
  source/module_io/fR_overlap.cpp
  source/module_io/fR_overlap.h
  source/module_io/output_mat_sparse.cpp
  source/module_io/to_wannier90_lcao.cpp
  source/module_io/write_HS_R.cpp
  source/module_io/write_HS_R.h
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/esolver_lrtd_lcao.h
Labels: The Absolute Zero

#5079 Fix serial version compiling bug
  CMakeLists.txt
Labels: Compile & CICD & Docs

#5082 Feature: add new init_chg method with wavefunctions
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_cell/klist.cpp
  source/module_cell/klist.h
  source/module_elecstate/elecstate.cpp
  source/module_elecstate/elecstate.h
  source/module_elecstate/module_charge/charge.h
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_elecstate/module_charge/charge_mpi.cpp
  source/module_elecstate/module_charge/symmetry_rho.cpp
  source/module_elecstate/module_charge/symmetry_rho.h
  source/module_elecstate/module_charge/symmetry_rhog.cpp
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_elecstate/test/elecstate_pw_test.cpp
  source/module_elecstate/test_mpi/charge_mpi_test.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_pw/hamilt_pwdft/elecond.cpp
  source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_wf.cpp
  source/module_hsolver/hsolver.cpp
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_io/CMakeLists.txt
  source/module_io/get_pchg_lcao.cpp
  source/module_io/get_pchg_pw.h
  source/module_io/read_input.cpp
  source/module_io/read_input.h
  source/module_io/read_input_item_elec_stru.cpp
  source/module_io/read_input_item_relax.cpp
  source/module_io/read_input_item_system.cpp
  source/module_io/read_wfc_pw.cpp
  source/module_io/read_wfc_pw.h
  source/module_io/read_wfc_to_rho.cpp
  source/module_io/read_wfc_to_rho.h
  source/module_io/test/CMakeLists.txt
  source/module_io/test/read_wfc_pw_test.cpp
  source/module_io/test/read_wfc_to_rho_test.cpp
  source/module_io/test/write_istate_info_test.cpp
  source/module_io/write_istate_info.cpp
  source/module_io/write_wfc_pw.cpp
Labels: Features Needed

#5094 Refactor: refactor HsolverPW & HsolverPW_SDFT func
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/pw_fun.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: The Absolute Zero

#5088 Toochain update: new download url and MPICH/OpenMPI version
  toolchain/README.md
  toolchain/build_abacus_gnu.sh
  toolchain/build_abacus_intel-mpich.sh
  toolchain/build_abacus_intel.sh
  toolchain/scripts/stage1/install_mpich.sh
  toolchain/scripts/stage1/install_openmpi.sh
  toolchain/scripts/stage4/install_cereal.sh
  toolchain/scripts/stage4/install_libcomm.sh
  toolchain/scripts/stage4/install_libnpy.sh
  toolchain/scripts/stage4/install_libri.sh
  toolchain/scripts/stage4/install_libtorch.sh
  toolchain/scripts/stage4/install_rapidjson.sh
  toolchain/scripts/tool_kit.sh
  toolchain/toolchain_gnu.sh
Labels: Compile & CICD & Docs

#5093 Refactor: remove `hsolver` base class from `module_hsolver`
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/test/test_hsolver.cpp
Labels: The Absolute Zero

#5126 Refactor: refactor paw code in HSolverLIP
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_lcaopw.h
Labels: The Absolute Zero

#5128 Refactor: remove my_conj func from hsolver_lcao
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/hsolver_lcao.h
Labels: The Absolute Zero

#5146 Perf&Refactor: optimize the performanace of psi_initializer with omp
  source/Makefile.Objects
  source/module_basis/module_nao/atomic_radials.cpp
  source/module_basis/module_nao/atomic_radials.h
  source/module_basis/module_nao/radial_set.cpp
  source/module_basis/module_nao/test/CMakeLists.txt
  source/module_basis/module_nao/test/atomic_radials_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/projop_pw.cpp
  source/module_io/CMakeLists.txt
  source/module_io/orb_io.cpp
  source/module_io/orb_io.h
  source/module_io/test/CMakeLists.txt
  source/module_io/test/orb_io_test.cpp
  source/module_lr/utils/test/CMakeLists.txt
  source/module_psi/psi_initializer.cpp
  source/module_psi/psi_initializer_nao.cpp
  source/module_psi/psi_initializer_nao.h
  source/module_psi/test/CMakeLists.txt
  source/module_relax/relax_old/test/CMakeLists.txt
  tests/integrate/102_PW_PINT_UKS/result.ref
  tests/integrate/401_NP_KP_sp/result.ref
  tests/integrate/401_NP_KP_spd/result.ref
Labels: Performance

#5157 Fix: wrong STRU read in md restart case
  docs/advanced/input_files/input-main.md
  source/driver_run.cpp
  source/module_base/global_variable.cpp
  source/module_base/global_variable.h
  source/module_cell/module_paw/paw_cell_libpaw.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/test/stress_op_test.cpp
  source/module_io/input_conv.cpp
  source/module_io/json_output/general_info.cpp
  source/module_io/json_output/test/para_json_test.cpp
  source/module_io/read_input.cpp
  source/module_io/read_input.h
  source/module_io/read_set_globalv.cpp
  source/module_parameter/system_parameter.h
  tests/integrate/120_PW_KP_MD_NVT/STRU
  tests/integrate/120_PW_KP_MD_NVT/STRU_MD_2
Labels: Bugs (Exclude input and output)

#5148 Refactor: refactor hsolver-lcao func
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/hsolver_lcao.h
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_lcaopw.h
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_lr/hsolver_lrtd.cpp
Labels: The Absolute Zero

#5167 Fix: add MPI_Barrier in unittest of CifParser when necessary to avoid unexpected behavoir
  source/module_io/test/cif_io_test.cpp
Labels: High Priority

#5163 use ELPA_WITH_NVIDIA_GPU_VERSION to judge elpa setup gpu
  docs/advanced/acceleration/cuda.md
  source/module_hsolver/diago_elpa_native.cpp
  source/module_hsolver/genelpa/elpa_new.h
Labels: Compile & CICD & Docs

#5169 Fix docs according to #5133
  source/module_hsolver/diago_david.h
  source/module_hsolver/hsolver_pw.cpp
Labels: The Absolute Zero

#5172 Fix: `timer` not closed in TDDFT code
  source/module_hamilt_lcao/module_tddft/evolve_elec.cpp
  source/module_hamilt_lcao/module_tddft/td_velocity.cpp
  source/module_io/td_current_io.cpp
Labels: The Absolute Zero

#5173 Radial quadrature grid
  source/module_base/grid/delley.cpp
  source/module_base/grid/delley.h
  source/module_base/grid/radial.cpp
  source/module_base/grid/radial.h
  source/module_base/grid/test/CMakeLists.txt
  source/module_base/grid/test/test_delley.cpp
  source/module_base/grid/test/test_radial.cpp
Labels: Features Needed

#5176 Fix: Update function calls in `pyabacus` to align with new function signature in `hpsi_func`
  python/pyabacus/src/py_diago_dav_subspace.hpp
  python/pyabacus/src/py_diago_david.hpp
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
Labels: Bugs (Exclude input and output)

#5177 Fix: recover the wannier90 interface for lcao_in_pw case
  source/module_psi/psi_initializer.cpp
  source/module_psi/psi_initializer.h
Labels: Input&Output

#5185 Fix: let only one rank do file I/O in unittest of orb_io
  source/module_io/orb_io.cpp
  source/module_io/test/orb_io_test.cpp
Labels: Bugs (Exclude input and output)

#5139 Feature: Calculate and output electron localization function (ELF) with KSDFT and OFDFT
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/elecstate.h
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_lcao.h
  source/module_elecstate/elecstate_lcao_cal_tau.cpp
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/elecstate_pw.h
  source/module_elecstate/elecstate_pw_cal_tau.cpp
  source/module_elecstate/module_charge/charge.cpp
  source/module_elecstate/module_charge/charge.h
  source/module_elecstate/module_charge/charge_mpi.cpp
  source/module_elecstate/module_charge/symmetry_rho.cpp
  source/module_elecstate/test/CMakeLists.txt
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_esolver/esolver_of_interface.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_lkt.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_lkt.h
  source/module_hamilt_pw/hamilt_ofdft/kedf_tf.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_tf.h
  source/module_hamilt_pw/hamilt_ofdft/kedf_vw.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_vw.h
  source/module_hamilt_pw/hamilt_ofdft/kedf_wt.cpp
  source/module_hamilt_pw/hamilt_ofdft/kedf_wt.h
  source/module_io/CMakeLists.txt
  source/module_io/read_input_item_output.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/write_elf.cpp
  source/module_io/write_elf.h
  source/module_parameter/input_parameter.h
  tests/integrate/119_PW_out_elf/INPUT
  tests/integrate/119_PW_out_elf/KPT
  tests/integrate/119_PW_out_elf/STRU
  tests/integrate/119_PW_out_elf/jd
  tests/integrate/119_PW_out_elf/refELF.cube
  tests/integrate/119_PW_out_elf/result.ref
  tests/integrate/219_NO_out_elf/INPUT
  tests/integrate/219_NO_out_elf/KPT
  tests/integrate/219_NO_out_elf/STRU
  tests/integrate/219_NO_out_elf/jd
  tests/integrate/219_NO_out_elf/refELF.cube
  tests/integrate/219_NO_out_elf/result.ref
  tests/integrate/919_OF_out_elf/INPUT
  tests/integrate/919_OF_out_elf/KPT
  tests/integrate/919_OF_out_elf/STRU
  tests/integrate/919_OF_out_elf/jd
  tests/integrate/919_OF_out_elf/refELF.cube
  tests/integrate/919_OF_out_elf/result.ref
  tests/integrate/CASES_CPU.txt
  tests/integrate/tools/catch_properties.sh
Labels: Features Needed

#5181 Perf: optimize td_current
  source/module_hamilt_lcao/module_tddft/td_current.cpp
Labels: Performance

#5179 Perf: change default pw_seed=0
  source/module_parameter/input_parameter.h
  tests/integrate/101_PW_15_pseudopots_LibxcLDA/INPUT
  tests/integrate/101_PW_GTH_CF_CS_Si/INPUT
  tests/integrate/101_PW_lps6_pseudopots/INPUT
  tests/integrate/101_PW_upf100_Rappe_Fe/INPUT
  tests/integrate/101_PW_upf100_uspp_Fe/INPUT
  tests/integrate/101_PW_upf201_uspp_Fe/INPUT
  tests/integrate/102_PW_BPCG_GPU/INPUT
  tests/integrate/103_PW_15_CS_CF/INPUT
  tests/integrate/103_PW_15_CS_CF_bspline/INPUT
  tests/integrate/103_PW_OU_CS_CF/INPUT
  tests/integrate/104_PW_FM_magnetic/INPUT
  tests/integrate/107_PW_OB_outputbands/INPUT
  tests/integrate/107_PW_W90/INPUT
  tests/integrate/107_PW_outWfcPw/INPUT
  tests/integrate/107_PW_outWfcR/INPUT
  tests/integrate/110_PW_SY/INPUT
  tests/integrate/112_PW_dipole/INPUT
  tests/integrate/112_PW_efield/INPUT
  tests/integrate/113_PW_gatefield/INPUT
  tests/integrate/114_PW_BD_15/INPUT
  tests/integrate/115_PW_sol_H2O/INPUT
  tests/integrate/116_PW_scan_Si2/INPUT
  tests/integrate/118_PW_CHG_BINARY/INPUT
  tests/integrate/120_PW_KP_MD_MSST/INPUT
  tests/integrate/127_PW_15_PK_AF/INPUT
  tests/integrate/140_PW_15_SO/INPUT
  tests/integrate/801_PW_LT_sc/INPUT
Labels: Performance

#5188 Fix parallel LR-EXX and add a test case
  source/module_lr/operator_casida/operator_lr_exx.cpp
  source/module_lr/operator_casida/operator_lr_exx.h
  tests/integrate/392_NO_GO_LR_HF/INPUT
  tests/integrate/392_NO_GO_LR_HF/KPT
  tests/integrate/392_NO_GO_LR_HF/STRU
  tests/integrate/392_NO_GO_LR_HF/jd
  tests/integrate/392_NO_GO_LR_HF/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs (Exclude input and output)

#5190 Docs: update hpsi_func requirements
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_david.h
Labels: Compile & CICD & Docs

#5150 Refactor `ModuleIO::read/write_cube()`
  source/module_hamilt_pw/hamilt_pwdft/parallel_grid.cpp
  source/module_hamilt_pw/hamilt_pwdft/parallel_grid.h
  source/module_io/cube_io.h
  source/module_io/read_cube.cpp
  source/module_io/write_cube.cpp
Labels: Refactor
