Repository deepmodeling/abacus-develop, pull requests merged in 2024-08, with the labels that each got.

#4795 Refactor: change `HsolverPW` call manner
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/pw_fun.cpp
  source/module_esolver/pw_init_after_vc.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver_pw.cpp
Labels: The Absolute Zero

#4826 feature: automatically use gpu if possible
  source/module_base/module_device/device.cpp
Labels: GPU & DCU & HPC

#4829 Feature: Support outputting partial charge densities for different k-points and spins separately when using PW basis set
  source/Makefile.Objects
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_io/CMakeLists.txt
  source/module_io/get_pchg_lcao.cpp
  source/module_io/get_pchg_lcao.h
  source/module_io/get_pchg_pw.h
  source/module_io/get_wf_lcao.cpp
  source/module_io/get_wf_lcao.h
Labels: Features Needed

#4828 Refactor: Use lambda expressions to reduce if conditions.
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
Labels: GPU & DCU & HPC

#4846 Refactor: remove `pelec` frome hsolverpw `solve` func
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/pw_fun.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/test/test_hsolver_pw.cpp
Labels: The Absolute Zero

#4847 Refactor: move `set_is_occupied` func from hsolver to elecstate
  source/module_elecstate/elecstate.cpp
  source/module_elecstate/elecstate.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/pw_fun.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_io/input_conv.cpp
  source/module_io/read_input_item_system.cpp
Labels: The Absolute Zero

#4855 Docs: SchmidtOrth in david
  source/module_hsolver/diago_david.cpp
Labels: The Absolute Zero

#4839 Feature: enable multi-k calculation for CUDA version of module_gint
  docs/advanced/acceleration/cuda.md
  docs/advanced/input_files/input-main.md
  source/module_base/module_device/device.cpp
  source/module_base/module_device/device.h
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_force_gpu.h
  source/module_hamilt_lcao/module_gint/gint_gpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.h
  source/module_hamilt_lcao/module_gint/gint_tools.cpp
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.h
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/gtask_force.cpp
  source/module_hamilt_lcao/module_gint/gtask_rho.cpp
  source/module_hamilt_lcao/module_gint/gtask_vl.cpp
  source/module_hamilt_lcao/module_hcontainer/hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/hcontainer.h
  source/module_io/input_conv.cpp
  tests/integrate/930_NO_BI2SE2CU2O2_k_GPU/INPUT
  tests/integrate/930_NO_BI2SE2CU2O2_k_GPU/KPT
  tests/integrate/930_NO_BI2SE2CU2O2_k_GPU/STRU
  tests/integrate/930_NO_BI2SE2CU2O2_k_GPU/result.ref
  tests/integrate/934_NO_Si2_dzp_neq_ns2_k_GPU/INPUT
  tests/integrate/934_NO_Si2_dzp_neq_ns2_k_GPU/KPT
  tests/integrate/934_NO_Si2_dzp_neq_ns2_k_GPU/STRU
  tests/integrate/934_NO_Si2_dzp_neq_ns2_k_GPU/result.ref
  tests/integrate/CASES_GPU.txt
Labels: Features Needed

#4866 Refactor: discourage part of the use of c-style array in psi initializer
  source/module_psi/psi_initializer_nao.cpp
Labels: Refactor

#4861 Refactor: remove pes from hsolver
  source/module_hsolver/hsolver_pw.cpp
Labels: The Absolute Zero

#4862 Refactor: Replace the pointers in `pseudo` and `Pseudopot_upf` with std::vector.
  source/module_cell/atom_pseudo.cpp
  source/module_cell/atom_pseudo.h
  source/module_cell/pseudo.cpp
  source/module_cell/pseudo.h
  source/module_cell/read_pp.cpp
  source/module_cell/read_pp.h
  source/module_cell/read_pp_blps.cpp
  source/module_cell/read_pp_complete.cpp
  source/module_cell/read_pp_upf100.cpp
  source/module_cell/read_pp_upf201.cpp
  source/module_cell/read_pp_vwr.cpp
  source/module_cell/setup_nonlocal.cpp
  source/module_cell/test/read_pp_test.cpp
  source/module_elecstate/module_charge/charge.cpp
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_T_NL_cd.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/test_nonlocalnew.cpp
  source/module_hamilt_pw/hamilt_pwdft/VL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_grad_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_scc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_loc.cpp
  source/module_hamilt_pw/hamilt_pwdft/wf_atomic.cpp
  source/module_psi/psi_initializer_atomic.cpp
  source/module_psi/test/psi_initializer_unit_test.cpp
Labels: The Absolute Zero

#4854 Refactor: Add heterogeneous parallel code for the stress loc module.
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_loc.cpp
Labels: GPU & DCU & HPC

#4887 Refactor: add `cal_becp`-like example for radial projector-involving PW operators development
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/projop_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/projop_pw.h
  source/module_hamilt_pw/hamilt_pwdft/radial_proj.cpp
  source/module_hamilt_pw/hamilt_pwdft/radial_proj.h
  source/module_hamilt_pw/hamilt_pwdft/test/radial_proj_test.cpp
Labels: Features Needed

#4893 Fix bug in `add_HexxR` at nspin=4
  source/module_ri/RI_2D_Comm.hpp
Labels: Bugs (Exclude input and output)

#4892 Fix: correct the behavior of profile1d function in cube_manipulator.py
  tools/plot-tools/cube_manipulator.py
Labels: Refactor

#4902 Fix: avoid the redundant file-reading and remove the useless output in write_Vxc
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.hpp
  source/module_io/write_eband_terms.hpp
Labels: EXX, Input&Output

#4889 Refactor: merge after_scf
  docs/advanced/elec_properties/charge.md
  docs/advanced/input_files/input-main.md
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/test/support/NOW_SPIN1_CHG.cube
  source/module_elecstate/test/support/OLD1_SPIN1_CHG.cube
  source/module_elecstate/test/support/SPIN1_CHG.cube
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_esolver/esolver_of_tool.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/pw_nscf.cpp
  source/module_io/get_pchg_pw.h
  source/module_io/read_input_item_output.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_io/test_serial/support/SPIN1_CHG.cube
  source/module_io/write_cube.cpp
  source/module_io/write_elecstat_pot.cpp
  source/module_io/write_elecstat_pot.h
  tests/integrate/107_PW_CHG_mismatch/SPIN1_CHG.cube
  tests/integrate/107_PW_CHG_mismatch/SPIN2_CHG.cube
  tests/integrate/107_PW_OBOD_MemSaver/SPIN1_CHG.cube
  tests/integrate/107_PW_OB_outputbands/SPIN1_CHG.cube
  tests/integrate/107_PW_OD_outputdos/SPIN1_CHG.cube
  tests/integrate/107_PW_OK/SPIN1_CHG.cube.ref
  tests/integrate/107_PW_OK/SPIN1_TAU.cube.ref
  tests/integrate/107_PW_W90/SPIN1_CHG.cube
  tests/integrate/117_PW_out_pot/refSPIN1_POT.cube
  tests/integrate/117_PW_out_pot_nscf/SPIN1_CHG.cube
  tests/integrate/117_PW_out_pot_nscf/refSPIN1_POT.cube
  tests/integrate/118_PW_WFC_BINARY/SPIN1_CHG.cube
  tests/integrate/186_PW_NSCF_KG_100/SPIN1_CHG.cube
  tests/integrate/186_PW_SDOS_MALL/SPIN1_CHG.cube
  tests/integrate/186_PW_SKG_10D10S/SPIN1_CHG.cube
  tests/integrate/201_NO_15_f_pseudopots/refElecStaticPot.cube
  tests/integrate/207_NO_KP_OB/SPIN1_CHG.cube
  tests/integrate/207_NO_KP_OD/SPIN1_CHG.cube
  tests/integrate/207_NO_KP_OH_nscf/SPIN1_CHG.cube
  tests/integrate/207_NO_OK/SPIN1_CHG.cube.ref
  tests/integrate/207_NO_OK/SPIN1_TAU.cube.ref
  tests/integrate/214_NO_mulliken_nscf/SPIN1_CHG.cube
  tests/integrate/217_NO_out_pot/refSPIN1_POT.cube
  tests/integrate/217_NO_out_pot_nscf/SPIN1_CHG.cube
  tests/integrate/217_NO_out_pot_nscf/refSPIN1_POT.cube
  tests/integrate/clean.sh
Labels: The Absolute Zero

#4910 Refactor: remove do_after_converge
  source/module_elecstate/elecstate_print.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
Labels: The Absolute Zero

#4921 Revert "Move the cal_nnrg file and modify the variable length. (#4886)"
  source/Makefile.Objects
  source/module_esolver/set_matrix_grid.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/CMakeLists.txt
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_nnr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_gint/gint.cpp
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_force_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_force_gpu.h
  source/module_hamilt_lcao/module_gint/gint_gpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_k.h
  source/module_hamilt_lcao/module_gint/gint_k_pvpr.cpp
  source/module_hamilt_lcao/module_gint/gint_k_sparse1.cpp
  source/module_hamilt_lcao/module_gint/gint_rho_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/grid_bigcell.cpp
  source/module_hamilt_lcao/module_gint/grid_bigcell.h
  source/module_hamilt_lcao/module_gint/grid_index.h
  source/module_hamilt_lcao/module_gint/grid_meshball.cpp
  source/module_hamilt_lcao/module_gint/grid_meshball.h
  source/module_hamilt_lcao/module_gint/grid_meshcell.cpp
  source/module_hamilt_lcao/module_gint/grid_meshk.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.cpp
  source/module_hamilt_lcao/module_gint/grid_technique.h
  source/module_hamilt_lcao/module_gint/init_orb.cpp
  source/module_io/get_pchg_lcao.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/lr_spectrum.cpp
  source/module_lr/operator_casida/operator_lr_hxc.cpp
  tests/performance/sumdat.py
Labels: The Absolute Zero

#4924 Continue to move the deepks output files into the OUT folder
  docs/advanced/input_files/input-main.md
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/cal_gedm.cpp
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/get_dm_eig.py
  tests/deepks/602_NO_deepks_d_H2O_scf_lda2pbe/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_bandgap/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_v_delta_1/get_dm_eig.py
  tests/deepks/603_NO_deepks_H2O_v_delta_2/get_dm_eig.py
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/get_dm_eig.py
  tests/integrate/tools/catch_properties.sh
Labels: The Absolute Zero

#4926 Refactor: remove function mult_psi_DM and mult_psi_DM_new
  source/Makefile.Objects
  source/module_hamilt_lcao/module_gint/CMakeLists.txt
  source/module_hamilt_lcao/module_gint/gint_force_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_rho_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.cpp
  source/module_hamilt_lcao/module_gint/gint_tools.h
  source/module_hamilt_lcao/module_gint/mult_psi_dm.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dm_new.cpp
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
Labels: The Absolute Zero

#4858 Refactor: Relate to PEXSI-related changes caused by refactor #4767
  source/module_hsolver/diago_pexsi.cpp
  source/module_hsolver/diago_pexsi.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/module_pexsi/simple_pexsi.cpp
Labels: Refactor

#4929 Refactor: change hsolver_lcao call manner
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.h
Labels: The Absolute Zero

#4931 Refactor: change hsolver-lip call manner
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_hsolver/hsolver_lcaopw.h
Labels: The Absolute Zero

#4934 Fix bug due to the forgotten `fix_gamma` in writing eband terms
  source/module_io/write_eband_terms.hpp
  source/module_io/write_vxc.hpp
Labels: Bugs (Exclude input and output)

#4933 Fix the issue of mete-vlocal not being initialized.
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
Labels: Bugs (Exclude input and output)

#4936 Fix: delete the unexpected debug info during scf
  source/module_hsolver/hsolver_lcao.cpp
Labels: Bugs (Exclude input and output)

#4939 Fix the issue of some `timer` instances not being closed, resulting in incorrect time statistics
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/fedm_k.cpp
Labels: The Absolute Zero

#4937 Tools: support molden file generation from ABACUS LCAO calculation via NAO2GTO
  tools/molden.py
Labels: Features Needed

#4941 Refactor: Make Hsolver_sdft a local variable in hamilt_to_density function
  source/Makefile.Objects
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_hamilt_pw/hamilt_stodft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_stodft/sto_che.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_che.h
  source/module_hamilt_pw/hamilt_stodft/sto_dos.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_dos.h
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.h
  source/module_hamilt_pw/hamilt_stodft/sto_func.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_func.h
  source/module_hamilt_pw/hamilt_stodft/sto_hchi.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_hchi.h
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.h
  source/module_hamilt_pw/hamilt_stodft/sto_tool.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_tool.h
  source/module_hamilt_pw/hamilt_stodft/sto_wf.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_wf.h
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver_sdft.cpp
  tests/integrate/184_PW_BNDKPAR_SDFT_MALL/result.ref
Labels: The Absolute Zero

#4946 Refactor: change hsolver-lcao call manner in SpinConstrain
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.h
Labels: The Absolute Zero

#4948 Fix: a possible bug when dir is auto
  source/module_io/read_input_item_system.cpp
  source/module_parameter/input_parameter.h
Labels: Bugs (Exclude input and output)

#4942 Fix: improve the experience of using `molden.py` postprocessing tool by both developer and user
  tools/molden/molden.py
  tools/molden/water/INPUT
  tools/molden/water/KPT
  tools/molden/water/STRU
Labels: Features Needed

#4940 Refactor: `reset_diag_ethr` && `cal_hsolve_error` func in hsolver
  source/Makefile.Objects
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/hsolver.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver.cpp
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
Labels: The Absolute Zero

#4956 Fix an EXX bug with out_mat_hs2
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
Labels: Bugs (Exclude input and output)

#4962 fix bug in catching properties for out_eband_terms
  tests/integrate/tools/catch_properties.sh
Labels: Bugs (Exclude input and output)

#4966 Toolchain : libcomm version update
  toolchain/README.md
  toolchain/scripts/stage4/install_libcomm.sh
  toolchain/scripts/stage4/install_libri.sh
Labels: Compile & CICD & Docs

#4958 Feature: support control on precison of charge cube output
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_hamilt_lcao/module_dftu/dftu_io.cpp
  source/module_io/read_input_item_output.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_parameter/input_parameter.h
  source/module_ri/exx_lip.cpp
Labels: Input&Output

#4883 Feature: Add diago_dav_subspace module to pyabacus
  python/pyabacus/CMakeLists.txt
  python/pyabacus/README.md
  python/pyabacus/examples/Si2.mat
  python/pyabacus/examples/diago_matrix.py
  python/pyabacus/pyproject.toml
  python/pyabacus/src/py_abacus.cpp
  python/pyabacus/src/py_diago_dav_subspace.cpp
  python/pyabacus/src/py_diago_dav_subspace.hpp
  python/pyabacus/src/py_m_nao.cpp
  python/pyabacus/src/pyabacus/ModuleBase/__init__.py
  python/pyabacus/src/pyabacus/ModuleBase/_module_base.py
  python/pyabacus/src/pyabacus/ModuleNAO/__init__.py
  python/pyabacus/src/pyabacus/ModuleNAO/_module_nao.py
  python/pyabacus/src/pyabacus/__init__.py
  python/pyabacus/src/pyabacus/hsolver/__init__.py
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
  python/pyabacus/tests/test_diag/Na5.mat
  python/pyabacus/tests/test_diag/Si2.mat
  python/pyabacus/tests/test_diago_dav_subspace.py
Labels: Pyabacus

#4972 Refactor: remove template<class T> in Chebyshev
  source/module_base/math_chebyshev.cpp
  source/module_base/math_chebyshev.h
  source/module_base/math_chebyshev_def.h
  source/module_base/test/math_chebyshev_test.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_dos.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_tool.cpp
Labels: The Absolute Zero

#4973 Fix: Fix the I/O problem of Rappe pseudopotential caused by the change of `mesh`.
  source/module_cell/read_pp.h
  source/module_cell/read_pp_blps.cpp
  source/module_cell/read_pp_upf100.cpp
  source/module_cell/read_pp_upf201.cpp
  source/module_cell/read_pp_vwr.cpp
  tests/PP_ORB/Fe.Rappe.PBE.UPF
  tests/integrate/101_PW_upf100_Rappe_Fe/INPUT
  tests/integrate/101_PW_upf100_Rappe_Fe/KPT
  tests/integrate/101_PW_upf100_Rappe_Fe/README
  tests/integrate/101_PW_upf100_Rappe_Fe/STRU
  tests/integrate/101_PW_upf100_Rappe_Fe/jd
  tests/integrate/101_PW_upf100_Rappe_Fe/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs (Exclude input and output)

#4994 Fix: do not always output HexxR but only for NSCF
  source/module_esolver/esolver_ks_lcao.cpp
Labels: EXX

#4978 Performance: heterogeneous operator of npw loop in force_cc.
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/rocm/stress_op.hip.cu
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.h
  source/module_hamilt_pw/hamilt_stodft/sto_forces.cpp
Labels: GPU & DCU & HPC

#4980 add elpa gpu in docker cuda image
  Dockerfile.cuda
Labels: GPU & DCU & HPC

#4982 Feature: output T(k)
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_io/read_input_item_output.cpp
  source/module_parameter/input_parameter.h
Labels: Input&Output

#4993 Fix: enable scf_ene_thr for EXX outer loop
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_ri/Exx_LRI_interface.h
  source/module_ri/Exx_LRI_interface.hpp
Labels: EXX

#4991 Feature: support automatic binary output of charge density
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_basis/module_pw/pw_distributeg.cpp
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_esolver/esolver_fp.cpp
  source/module_io/CMakeLists.txt
  source/module_io/read_rhog.cpp
  source/module_io/rhog_io.cpp
  source/module_io/rhog_io.h
  source/module_io/test/CMakeLists.txt
  tests/integrate/118_PW_CHG_BINARY/autotest-CHARGE-DENSITY.restart
Labels: Input&Output

#5007 Fix: bug in charge extrapolation
  source/module_elecstate/module_charge/charge_extra.cpp
  source/module_elecstate/module_charge/charge_extra.h
  source/module_elecstate/test/charge_extra_test.cpp
  source/module_esolver/esolver_fp.cpp
  tests/integrate/108_PW_RE_NEW/result.ref
  tests/integrate/108_PW_RE_PINT_RKS/result.ref
Labels: Bugs (Exclude input and output)

#5014 Fix toolchain scalapack problem
  toolchain/scripts/stage3/install_scalapack.sh
Labels: Compile & CICD & Docs

#5017 Refactor: refactor set_diagethr func and remove phsol from esolver [version 2]
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_nscf.cpp
  source/module_esolver/pw_fun.cpp
  source/module_esolver/pw_init_after_vc.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hamilt_lcao/module_deltaspin/init_sc.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.h
  source/module_hamilt_lcao/module_deltaspin/test/init_sc_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/spin_constrain_test.cpp
  source/module_hsolver/hsolver.cpp
  source/module_hsolver/hsolver.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw.h
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/hsolver_pw_sdft.h
  source/module_hsolver/test/test_hsolver.cpp
Labels: The Absolute Zero
