Repository deepmodeling/abacus-develop, pull requests merged in 2025-02, with the labels that each got.

#5886 Fix: Solve mpi bug for DeePKS.
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbital.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_phialpha.cpp
  source/module_hamilt_lcao/module_deepks/deepks_phialpha.h
  source/module_hamilt_lcao/module_deepks/deepks_spre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
Labels: Refactor, DeePKS

#5898 Perf: modify openmp strategy in module_gint
  source/module_hamilt_lcao/module_gint/gint_force_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_rho_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
Labels: GPU & DCU & HPC, Useful Information

#5896 Doc: Enhance `ocp` and `ocp_set` documentation for clarity and error prevention
  docs/advanced/input_files/input-main.md
Labels: Compile & CICD & Docs & Dependencies, Refactor

#5887 Refactor ucell read_stru part
  .gitignore
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/module_neighbor/test/sltk_atom_arrange_test.cpp
  source/module_cell/module_neighbor/test/sltk_grid_test.cpp
  source/module_cell/print_cell.cpp
  source/module_cell/print_cell.h
  source/module_cell/read_atoms.cpp
  source/module_cell/read_stru.cpp
  source/module_cell/read_stru.h
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_readpp.cpp
  source/module_cell/test_pw/CMakeLists.txt
  source/module_cell/test_pw/unitcell_test_pw.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/cal_wfc.cpp
  source/module_elecstate/read_orb.cpp
  source/module_elecstate/read_orb.h
  source/module_elecstate/read_pseudo.cpp
  source/module_elecstate/read_pseudo.h
  source/module_hamilt_lcao/module_deepks/test/CMakeLists.txt
  source/module_io/test/write_orb_info_test.cpp
  source/module_md/run_md.cpp
  source/module_md/test/CMakeLists.txt
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_new/relax.cpp
  source/module_relax/relax_new/test/CMakeLists.txt
  source/module_relax/relax_new/test/relax_test.cpp
  source/module_relax/relax_new/test/relax_test.h
  source/module_relax/relax_old/ions_move_basic.cpp
  source/module_relax/relax_old/test/CMakeLists.txt
  source/module_relax/relax_old/test/for_test.h
  source/module_relax/relax_old/test/ions_move_cg_test.cpp
Labels: Input&Output, The Absolute Zero

#5900 Add const to `rho_basis` in PW forces
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_scc.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_us.cpp
Labels: Refactor

#5907 Refactor: update assignment logic of ecutwfc and ecutrho
  docs/advanced/input_files/input-main.md
  source/module_io/read_input_item_system.cpp
Labels: Input&Output, Refactor

#5905 Fix: Resolve compilation issue with Libxc 7.0.0 in ABACUS
  source/module_hamilt_general/module_xc/xc_functional_libxc.h
  source/module_hamilt_general/module_xc/xc_functional_wrapper_xc.cpp
Labels: Features Needed, Refactor

#5906 Fix: wrong value of nmaxgr
  source/module_basis/module_pw/pw_basis.cpp
  source/module_basis/module_pw/pw_basis.h
  source/module_basis/module_pw/test_serial/pw_basis_test.cpp
  source/module_io/unk_overlap_pw.cpp
  tests/integrate/tools/catch_properties.sh
Labels: Bugs, Refactor

#5912 Docs: update docs about init_wfc
  docs/advanced/input_files/input-main.md
Labels: Compile & CICD & Docs & Dependencies, Input&Output

#5917 Fix: Update documentation for `td_lcut` parameter in RT-TDDFT
  docs/advanced/input_files/input-main.md
Labels: Compile & CICD & Docs & Dependencies, Input&Output

#5918 Fix: Add the correct RT-TDDFT electric field force acting on ions
  source/module_elecstate/potentials/H_TDDFT_pw.cpp
  source/module_elecstate/potentials/H_TDDFT_pw.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
Labels: Bugs, Refactor

#5925 Solving linear equations to evolve the wave function in RT-TDDFT.
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_base/scalapack_connector.h
  source/module_hamilt_lcao/module_tddft/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/evolve_psi.cpp
  source/module_hamilt_lcao/module_tddft/solve_propagation.cpp
  source/module_hamilt_lcao/module_tddft/solve_propagation.h
Labels: Features Needed

#5922 Update docs related to inputs, scf_thr and ase-abacus
  docs/advanced/input_files/input-main.md
  docs/advanced/interface/ase.md
  docs/quick_start/input.md
Labels: Compile & CICD & Docs & Dependencies, Input&Output, Refactor

#5927 fix a bug about hcontainer in exx nscf
  source/module_ri/RI_2D_Comm.hpp
Labels: Bugs, Refactor

#5928 Fix: useless output
  source/module_io/write_wfc_nao.cpp
Labels: Input&Output

#5930 Performance: Add CUDA Aware MPI
  CMakeLists.txt
  docs/advanced/install.md
  source/module_base/para_gemm.cpp
  source/module_base/parallel_device.cpp
  source/module_base/parallel_device.h
  source/module_hsolver/para_linear_transform.cpp
Labels: Performance, GPU & DCU & HPC

#5933 Perf: optimize deepks functions cal_f_delta and cal_pdm
  source/module_base/intarray.cpp
  source/module_base/intarray.h
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_hcontainer/base_matrix.cpp
  source/module_hamilt_lcao/module_hcontainer/base_matrix.h
Labels: GPU & DCU & HPC, DeePKS

#5934 [Refactor] Remove all ctx in math_kernel_op
  source/module_base/blas_connector.cpp
  source/module_base/kernels/cuda/math_kernel_op.cu
  source/module_base/kernels/math_kernel_op.cpp
  source/module_base/kernels/math_kernel_op.h
  source/module_base/kernels/rocm/math_kernel_op.hip.cu
  source/module_base/kernels/test/math_kernel_test.cpp
  source/module_base/para_gemm.cpp
  source/module_base/test_parallel/test_para_gemm.cpp
  source/module_elecstate/elecstate_pw.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.cpp
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/onsite_proj_tools.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/meta_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/nonlocal_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/onsite_proj_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_che.h
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hsolver/diago_cg.cpp
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/kernels/test/math_dngvd_test.cpp
  source/module_hsolver/kernels/test/perf_math_kernel.cpp
  source/module_hsolver/para_linear_transform.cpp
  source/module_hsolver/test/diago_bpcg_test.cpp
  source/module_hsolver/test/test_para_linear_trans.cpp
  source/module_lr/operator_casida/operator_lr_diag.h
Labels: The Absolute Zero
