Repository deepmodeling/abacus-develop, pull requests merged in 2025-04, with the labels that each got.

#6085 Refactor: replace 3.14 using PI
  source/module_basis/module_ao/ORB_nonlocal_lm.cpp
  source/module_cell/module_neighbor/sltk_util.h
  source/module_cell/module_paw/paw_cell.cpp
  source/module_cell/module_paw/paw_sphbes.cpp
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_hamilt_general/module_xc/xc_funct_exch_gga.cpp
  source/module_hamilt_general/module_xc/xc_funct_exch_lda.cpp
  source/module_hamilt_general/module_xc/xc_funct_hcth.cpp
  source/module_hamilt_pw/hamilt_pwdft/VL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/kernels/stress_op.cpp
  source/module_io/cal_dos.cpp
  source/module_io/write_dos_lcao.cpp
  tests/integrate/204_NO_KP_NC/result.ref
  tests/integrate/218_NO_mixing_tau/result.ref
Labels: The Absolute Zero

#6090 Fix: std::out_of_range of map when out_mat_t with multi-core
  source/module_io/write_HS_sparse.cpp
Labels: Bugs, Refactor

#6094 Refactor: Remove C++17 syntax and optimize DMR calculation in DeePKS.
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.h
  source/module_hamilt_lcao/module_deepks/deepks_fpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.h
  source/module_hamilt_lcao/module_deepks/deepks_iterate.h
  source/module_hamilt_lcao/module_deepks/deepks_orbital.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbital.h
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.h
  source/module_hamilt_lcao/module_deepks/deepks_spre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_spre.h
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.h
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
Labels: The Absolute Zero, DeePKS

#6095 Docs: Correct intro to output in quickstart
  docs/quick_start/output.md
Labels: Input&Output, Refactor

#6093 Rafactor:remove GlobalC::rhopw
  source/module_base/kernels/math_ylm_op.h
  source/module_basis/module_nao/two_center_bundle.h
  source/module_cell/test/klist_test.cpp
  source/module_cell/test/klist_test_para.cpp
  source/module_hamilt_general/module_surchem/test/cal_epsilon_test.cpp
  source/module_hamilt_general/module_surchem/test/cal_pseudo_test.cpp
  source/module_hamilt_general/module_surchem/test/cal_totn_test.cpp
  source/module_hamilt_general/module_surchem/test/cal_vcav_test.cpp
  source/module_hamilt_general/module_surchem/test/cal_vel_test.cpp
  source/module_hamilt_general/module_surchem/test/setcell.h
  source/module_hamilt_pw/hamilt_pwdft/global.cpp
  source/module_hsolver/diago_david.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/test/for_testing_klist.h
  source/module_io/test/print_info_test.cpp
  source/module_relax/relax_new/test/relax_test.h
Labels: The Absolute Zero

#6084 Update Hamiltonian and Operator classes
  source/module_base/global_function.cpp
  source/module_base/global_function.h
  source/module_cell/read_atom_species.cpp
  source/module_cell/read_atoms.cpp
  source/module_cell/read_pp_upf201.cpp
  source/module_cell/read_stru.cpp
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_hamilt_general/operator.cpp
  source/module_hamilt_general/operator.h
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/hs_matrix_k.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.h
  source/module_hamilt_lcao/module_dftu/dftu.h
  source/module_hamilt_lcao/module_dftu/dftu_folding.cpp
  source/module_hamilt_lcao/module_dftu/dftu_force.cpp
  source/module_hamilt_lcao/module_dftu/dftu_occup.cpp
  source/module_io/write_dos_lcao.cpp
Labels: Bugs, Input&Output, The Absolute Zero

#6088 changing test 218
  tests/integrate/218_NO_mixing_tau/INPUT
  tests/integrate/218_NO_mixing_tau/KPT
  tests/integrate/218_NO_mixing_tau/STRU
  tests/integrate/218_NO_mixing_tau/jd
  tests/integrate/218_NO_mixing_tau/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs, Not solved

#6103 fix a typo(missing newline) in cuda.md
  docs/advanced/acceleration/cuda.md
Labels: Compile & CICD & Docs & Dependencies

#6099 [Refactor] Remove uncapsulted scalapack functions in dftu_occup.cpp
  source/module_hamilt_lcao/module_dftu/dftu_occup.cpp
Labels: The Absolute Zero

#6097 Feature: print the expectation value of angular momentum operators Lx/Ly/Lz for ABACUS NAO basis
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_esolver/lcao_after_scf.cpp
  source/module_io/CMakeLists.txt
  source/module_io/cal_pLpR.cpp
  source/module_io/cal_pLpR.h
  source/module_io/read_input_item_output.cpp
  source/module_io/test/CMakeLists.txt
  source/module_io/test/cal_pLpR_test.cpp
  source/module_parameter/input_parameter.h
Labels: Features Needed

#6100 Feature: ldos in pw basis set
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/module_elecstate/elecstate_pw.h
  source/module_elecstate/fp_energy.cpp
  source/module_elecstate/fp_energy.h
  source/module_elecstate/test/elecstate_fp_energy_test.cpp
  source/module_esolver/esolver.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_io/CMakeLists.txt
  source/module_io/cal_ldos.cpp
  source/module_io/cal_ldos.h
  source/module_io/read_input_item_output.cpp
  source/module_io/read_input_item_postprocess.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test/support/INPUT
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_parameter/input_parameter.h
Labels: Features Needed, Refactor

#6102 Refactor: Simplify some functions in DeePKS.
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_iterate.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_spre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
Labels: The Absolute Zero, DeePKS

#6106 Fix: v_delta_precalc error in DeePKS.
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
Labels: Bugs, Refactor

#6109 Test: add test for pw ldos
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_io/cal_ldos.cpp
  source/module_io/cal_ldos.h
  source/module_io/read_input_item_output.cpp
  source/module_io/read_input_item_postprocess.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test/support/INPUT
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_parameter/input_parameter.h
  tests/integrate/101_PW_15_pseudopots/INPUT
  tests/integrate/101_PW_15_pseudopots/LDOS.cube.ref
  tests/integrate/101_PW_15_pseudopots/STRU
  tests/integrate/101_PW_15_pseudopots/result.ref
  tests/integrate/tools/catch_properties.sh
Labels: Features Needed, Refactor

#6113 Update DOS output formats (pw basis).
  source/module_base/test/timer_test.cpp
  source/module_base/test/tool_quit_test.cpp
  source/module_base/timer.cpp
  source/module_base/tool_quit.cpp
  source/module_cell/unitcell.cpp
  source/module_elecstate/fp_energy.h
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hamilt_general/module_vdw/test/vdw_test.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_dos.cpp
  source/module_io/cal_dos.cpp
  source/module_io/cal_dos.h
  source/module_io/cal_ldos.cpp
  source/module_io/cal_pdos_gamma.cpp
  source/module_io/cal_pdos_gamma.h
  source/module_io/dos_nao.cpp
  source/module_io/read_set_globalv.cpp
  source/module_io/restart_exx_csr.hpp
  source/module_io/single_R_io.cpp
  source/module_io/td_current_io.h
  source/module_io/test/cal_dos_test.cpp
  source/module_io/test/dos_test.h
  source/module_io/test/write_dos_pw_test.cpp
  source/module_io/test_serial/rho_io_test.cpp
  source/module_io/to_wannier90_pw.cpp
  source/module_io/unk_overlap_lcao.cpp
  source/module_io/unk_overlap_pw.cpp
  source/module_io/winput.cpp
  source/module_io/write_cube.cpp
  source/module_io/write_dos_lcao.cpp
  source/module_io/write_dos_lcao.h
  source/module_io/write_dos_pw.cpp
  source/module_io/write_dos_pw.h
  source/module_io/write_eband_terms.hpp
  source/module_io/write_istate_info.cpp
  source/module_io/write_orb_info.cpp
  source/module_io/write_proj_band_lcao.cpp
  source/module_parameter/system_parameter.h
  tests/integrate/107_PW_OBOD_MemSaver/result.ref
  tests/integrate/107_PW_OD_outputdos/INPUT
  tests/integrate/107_PW_OD_outputdos/result.ref
  tests/integrate/207_NO_KP_OD/INPUT
  tests/integrate/207_NO_KP_OD/result.ref
  tests/integrate/tools/catch_properties.sh
Labels: The Absolute Zero

#6104 Feature : deepks_out_labels = 2 for label preperation in deepks training
  docs/advanced/input_files/input-main.md
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/deepks_basic.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.h
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.h
  source/module_io/read_input_item_deepks.cpp
  source/module_io/read_set_globalv.cpp
  source/module_parameter/input_parameter.h
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/result.ref
  tests/deepks/602_NO_deepks_d_H2O_scf_lda2pbe/result.ref
  tests/deepks/603_NO_deepks_H2O_bandgap/result.ref
  tests/deepks/603_NO_deepks_H2O_out_labels_2/INPUT
  tests/deepks/603_NO_deepks_H2O_out_labels_2/KPT
  tests/deepks/603_NO_deepks_H2O_out_labels_2/STRU
  tests/deepks/603_NO_deepks_H2O_out_labels_2/get_sum_numpy.py
  tests/deepks/603_NO_deepks_H2O_out_labels_2/result.ref
  tests/deepks/603_NO_deepks_H2O_v_delta_1/result.ref
  tests/deepks/603_NO_deepks_H2O_v_delta_2/result.ref
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/result.ref
  tests/deepks/CASES_CPU.txt
  tests/integrate/tools/catch_deepks_properties.sh
  tests/integrate/tools/catch_properties.sh
Labels: Refactor, DeePKS

#6122 Fix: add exit 1 for shell UTs
  source/module_base/test_parallel/blacs_connector_test.sh
  source/module_base/test_parallel/parallel_2d_test.sh
  source/module_base/test_parallel/parallel_common_test.sh
  source/module_base/test_parallel/parallel_global_test.sh
  source/module_base/test_parallel/parallel_reduce_test.cpp
  source/module_base/test_parallel/parallel_reduce_test.sh
  source/module_basis/module_ao/test/parallel_orbitals_test.sh
  source/module_cell/test/atom_spec_test.cpp
  source/module_cell/test/bcast_atom_pseudo_test.sh
  source/module_cell/test/bcast_atom_spec_test.sh
  source/module_cell/test/klist_test_para.sh
  source/module_cell/test/prepare_unitcell.h
  source/module_cell/test/unitcell_test_parallel.sh
  source/module_cell/test_pw/unitcell_test_pw_para.sh
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/test/parallel_operator_tests.sh
  source/module_hamilt_lcao/module_hcontainer/test/parallel_hcontainer_tests.sh
  source/module_hsolver/test/diago_cg_float_test.cpp
  source/module_hsolver/test/diago_cg_parallel_test.sh
  source/module_hsolver/test/diago_cg_test.cpp
  source/module_hsolver/test/diago_david_parallel_test.sh
  source/module_hsolver/test/parallel_k2d_test.cpp
  source/module_hsolver/test/parallel_k2d_test.sh
  source/module_io/test/write_wfc_nao_para.sh
Labels: Bugs, Refactor

#6123 Feature: ldos in lcao basis sets
  docs/advanced/input_files/input-main.md
  source/module_io/cal_ldos.cpp
  source/module_io/cal_ldos.h
  source/module_io/read_input_item_postprocess.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test_serial/read_input_item_test.cpp
  source/module_parameter/input_parameter.h
Labels: Features Needed, Refactor

#6118 Feature: Add gamma point extrapolation for EXX PW
  source/module_cell/klist.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/module_exx_helper/exx_helper.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/op_exx_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/op_exx_pw.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_exx.cpp
  source/module_io/read_input_item_other.cpp
  source/module_parameter/input_parameter.h
  tests/integrate/190_PW_PBE0/INPUT
Labels: Bugs, EXX and lr-TDDFT, Features Needed, Refactor

#6133 Fix some output information typo
  docs/advanced/input_files/input-main.md
  source/module_base/tool_quit.cpp
  source/module_cell/cell_index.cpp
  source/module_cell/read_atom_species.cpp
  source/module_cell/read_atoms.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/update_cell.cpp
Labels: The Absolute Zero

#6146 Fix: Avoid hexadecimal output during relax process of HSE
  source/module_ri/Exx_LRI_interface.hpp
Labels: Bugs, Input&Output, Refactor

#6144 Fix: update weight in ldos
  source/module_io/cal_ldos.cpp
  tests/integrate/101_PW_15_pseudopots/LDOS.cube.ref
Labels: Features Needed, Refactor

#6148 Refactor: reduce the read-in loop in sts_line
  tools/stm/plot.py
  tools/stm/stm.py
Labels: Features Needed, Refactor

#6154 Update get_wf codes and output formats
  source/module_cell/klist.cpp
  source/module_esolver/lcao_others.cpp
  source/module_io/get_pchg_pw.h
  source/module_io/get_wf_lcao.cpp
  source/module_io/get_wf_lcao.h
  tests/integrate/212_NO_KP_get_wf/INPUT
  tests/integrate/212_NO_KP_get_wf/KPT
  tests/integrate/212_NO_KP_get_wf/STRU
  tests/integrate/212_NO_KP_get_wf/WFC_NAO_K1.txt
  tests/integrate/212_NO_KP_get_wf/WFC_NAO_K2.txt
  tests/integrate/212_NO_KP_get_wf/WFC_NAO_K3.txt
  tests/integrate/212_NO_KP_get_wf/WFC_NAO_K4.txt
  tests/integrate/212_NO_KP_get_wf/WFC_NAO_K5.txt
  tests/integrate/212_NO_KP_get_wf/WFC_NAO_K6.txt
  tests/integrate/212_NO_KP_get_wf/jd
  tests/integrate/212_NO_KP_get_wf/result.ref
  tests/integrate/212_NO_wfc_get_wf/INPUT
  tests/integrate/212_NO_wfc_get_wf/WFC_NAO_K1.txt
  tests/integrate/212_NO_wfc_get_wf/WFC_NAO_K2.txt
  tests/integrate/212_NO_wfc_get_wf/jd
  tests/integrate/212_NO_wfc_get_wf/result.ref
  tests/integrate/312_NO_GO_get_wf/INPUT
  tests/integrate/312_NO_GO_get_wf/KPT
  tests/integrate/312_NO_GO_get_wf/STRU
  tests/integrate/312_NO_GO_get_wf/WFC_NAO_GAMMA1.txt
  tests/integrate/312_NO_GO_get_wf/WFC_NAO_GAMMA2.txt
  tests/integrate/312_NO_GO_get_wf/jd
  tests/integrate/312_NO_GO_get_wf/result.ref
  tests/integrate/312_NO_GO_wfc_get_pchg/jd
  tests/integrate/312_NO_GO_wfc_get_pchg/result.ref
  tests/integrate/312_NO_GO_wfc_get_wf/INPUT
  tests/integrate/312_NO_GO_wfc_get_wf/WFC_NAO_GAMMA1.txt
  tests/integrate/312_NO_GO_wfc_get_wf/jd
  tests/integrate/312_NO_GO_wfc_get_wf/result.ref
  tests/integrate/Autotest.sh
  tests/integrate/CASES_CPU.txt
  tests/integrate/CASES_mylist.txt
  tests/integrate/CMakeLists.txt
  tests/integrate/clean.sh
  tests/integrate/general_info
  tests/integrate/tools/catch_properties.sh
  tests/integrate/tools/run_check.sh
  tests/integrate/tools/sum_BAND_CHG_H2.cpp
  tests/integrate/tools/sum_ENV_H2.cpp
  tests/integrate/tools/sum_ENV_H2_cube.cpp
  tests/integrate/tools/sum_cube.cpp
Labels: Features Needed, The Absolute Zero

#6155 Fix: A bug caused by the incorrect update of DMR for deepks_out_labels>0 but deepks_scf=0
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
Labels: Bugs, Refactor, DeePKS

#6159 Perf: Use phialpha in calculate_HR in DeePKS to avoid duplicate calculations.
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
Labels: Performance, Refactor

#6163 Fix: Fix periodic boundary condition search issue by enforcing `search_pbc=true`
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_lj.cpp
  source/module_esolver/lcao_after_scf.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp
  source/module_io/read_input_item_elec_stru.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/test/support/INPUT
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_parameter/input_parameter.h
  source/module_parameter/system_parameter.h
Labels: Input&Output, The Absolute Zero

#6087 Add Gtest for GPU pw_basis and pw_basis_k
  source/module_base/module_device/memory_op.h
  source/module_basis/module_pw/CMakeLists.txt
  source/module_basis/module_pw/module_fft/fft_cuda.cpp
  source/module_basis/module_pw/pw_basis.cpp
  source/module_basis/module_pw/pw_basis.h
  source/module_basis/module_pw/pw_basis_big.h
  source/module_basis/module_pw/pw_basis_k_big.h
  source/module_basis/module_pw/pw_basis_sup.cpp
  source/module_basis/module_pw/pw_distributeg.cpp
  source/module_basis/module_pw/pw_distributeg_method1.cpp
  source/module_basis/module_pw/pw_distributeg_method2.cpp
  source/module_basis/module_pw/pw_gatherscatter.h
  source/module_basis/module_pw/pw_init.cpp
  source/module_basis/module_pw/pw_transform_gpu.cpp
  source/module_basis/module_pw/test/CMakeLists.txt
  source/module_basis/module_pw/test_gpu/CMakeLists.txt
  source/module_basis/module_pw/test_gpu/pw_basis_C2C.cpp
  source/module_basis/module_pw/test_gpu/pw_basis_C2R.cpp
  source/module_basis/module_pw/test_gpu/pw_basis_k_C2C.cpp
  source/module_basis/module_pw/test_gpu/pw_test.cpp
  source/module_basis/module_pw/test_gpu/pw_test.h
  source/module_basis/module_pw/test_serial/pw_basis_k_test.cpp
  source/module_elecstate/module_charge/charge_mixing_rho.cpp
Labels: Features Needed, Unit Tests/Integreate Tests

#6165 Keep refactoring the integrate tests
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  tests/integrate/101_PW_15_PAW/INPUT
  tests/integrate/101_PW_15_PAW/KPT
  tests/integrate/101_PW_15_PAW/README
  tests/integrate/101_PW_15_PAW/STRU
  tests/integrate/101_PW_15_PAW/Si.xml
  tests/integrate/101_PW_15_PAW/jd
  tests/integrate/101_PW_15_PAW/result.ref
  tests/integrate/101_PW_15_PAW_SPIN2/INPUT
  tests/integrate/101_PW_15_PAW_SPIN2/KPT
  tests/integrate/101_PW_15_PAW_SPIN2/README
  tests/integrate/101_PW_15_PAW_SPIN2/STRU
  tests/integrate/101_PW_15_PAW_SPIN2/Si.xml
  tests/integrate/101_PW_15_PAW_SPIN2/jd
  tests/integrate/101_PW_15_PAW_SPIN2/result.ref
  tests/integrate/104_PW_NC/INPUT
  tests/integrate/104_PW_NC/KPT
  tests/integrate/104_PW_NC/README
  tests/integrate/104_PW_NC/STRU
  tests/integrate/104_PW_NC/jd
  tests/integrate/104_PW_NC/result.ref
  tests/integrate/104_PW_NC_magnetic/INPUT
  tests/integrate/104_PW_NC_magnetic/README
  tests/integrate/104_PW_NC_magnetic/result.ref
  tests/integrate/204_NO_KP_NC/README
  tests/integrate/204_NO_KP_NC/STRU
  tests/integrate/204_NO_KP_NC/jd
  tests/integrate/204_NO_KP_NC/result.ref
  tests/integrate/204_NO_NC/INPUT
  tests/integrate/204_NO_NC/KPT
  tests/integrate/204_NO_NC/README
  tests/integrate/204_NO_NC/STRU
  tests/integrate/204_NO_NC/mulliken.txt.ref
  tests/integrate/204_NO_NC/result.ref
  tests/integrate/204_NO_NC_magnetic/INPUT
  tests/integrate/204_NO_NC_magnetic/jd
  tests/integrate/204_NO_NC_magnetic/mulliken.txt.ref
  tests/integrate/204_NO_NC_magnetic/result.ref
  tests/integrate/Autotest.sh
  tests/integrate/CASES_CPU.txt
Labels: The Absolute Zero

#6170 Fix : fix the segment fault of md/relax of deepks by changing location of ld.init_DMR to before_scf
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_before_scf.cpp
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/result.ref
Labels: Bugs, Refactor

#6178 [Refactor] Separate blas_connector.cpp into three files
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_base/blas_connector.h
  source/module_base/blas_connector_base.cpp
  source/module_base/blas_connector_matrix.cpp
  source/module_base/blas_connector_vector.cpp
  source/module_basis/module_ao/test/CMakeLists.txt
  source/module_basis/module_pw/kernels/test/CMakeLists.txt
  source/module_basis/module_pw/test/CMakeLists.txt
  source/module_hamilt_general/module_xc/test/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt
  source/module_md/test/CMakeLists.txt
  source/module_relax/relax_new/test/CMakeLists.txt
Labels: The Absolute Zero
