Repository deepmodeling/abacus-develop, pull requests merged in 2025-09, with the labels that each got.

#6482 Test: Add test for `out_alllog` to ensure the output log filenames are correct
  tests/10_others/05_Alllog_filename/INPUT
  tests/10_others/05_Alllog_filename/KPT
  tests/10_others/05_Alllog_filename/README
  tests/10_others/05_Alllog_filename/STRU
  tests/10_others/05_Alllog_filename/result.ref
  tests/10_others/CASES_CPU.txt
  tests/integrate/tools/catch_properties.sh
Labels: Refactor, Unit Tests/Integreate Tests

#6484 add output information about device count
  source/CMakeLists.txt
  source/Makefile.Objects
  source/source_base/module_device/device.cpp
  source/source_base/module_device/device.h
  source/source_base/module_device/output_device.cpp
  source/source_esolver/esolver.cpp
  source/source_io/test_serial/CMakeLists.txt
Labels: GPU & DCU & HPC, Refactor

#6483 Feature: Add deepks_out_base to support simultaneous output of numpy files of base and target functionals
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/source_esolver/CMakeLists.txt
  source/source_esolver/esolver.cpp
  source/source_esolver/esolver_double_xc.cpp
  source/source_esolver/esolver_double_xc.h
  source/source_esolver/esolver_ks_lcao.cpp
  source/source_hamilt/module_xc/xc_functional.cpp
  source/source_io/module_parameter/input_parameter.h
  source/source_io/read_input_item_deepks.cpp
  source/source_lcao/FORCE_STRESS.cpp
  source/source_lcao/FORCE_STRESS.h
  source/source_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/source_lcao/module_deepks/LCAO_deepks_interface.h
  source/source_lcao/module_operator_lcao/operator_lcao.cpp
  tests/09_DeePKS/103_NO_GO_deepks_out_freq_elec/INPUT
  tests/09_DeePKS/103_NO_GO_deepks_out_freq_elec/result.ref
  tests/09_DeePKS/103_NO_KP_deepks_out_freq_elec/INPUT
  tests/09_DeePKS/103_NO_KP_deepks_out_freq_elec/result.ref
  tests/integrate/tools/catch_deepks_properties.sh
Labels: Features Needed, Refactor, Machine Learning

#6494 [Refactor] Move hardware initializer out from esolver code
  source/source_esolver/esolver_ks_pw.cpp
  source/source_main/driver.h
  source/source_main/driver_run.cpp
Labels: GPU & DCU & HPC, Refactor, The Absolute Zero

#6493 Perf: Optimize Davidson by fusing operators, offloading CPU computation to GPU, and reducing memory transfers
  source/source_base/kernels/cuda/math_kernel_op.cu
  source/source_base/kernels/math_kernel_op.cpp
  source/source_base/kernels/math_kernel_op.h
  source/source_base/kernels/rocm/math_kernel_op.hip.cu
  source/source_base/module_device/cuda/memory_op.cu
  source/source_base/module_device/memory_op.cpp
  source/source_base/module_device/memory_op.h
  source/source_hsolver/diago_dav_subspace.cpp
  source/source_hsolver/diago_dav_subspace.h
  source/source_hsolver/kernels/bpcg_kernel_op.cpp
  source/source_hsolver/kernels/bpcg_kernel_op.h
  source/source_hsolver/kernels/cuda/bpcg_kernel_op.cu
  source/source_hsolver/kernels/cuda/dngvd_op.cu
  source/source_hsolver/kernels/rocm/bpcg_kernel_op.hip.cu
  source/source_hsolver/kernels/rocm/dngvd_op.hip.cu
Labels: Performance, GPU & DCU & HPC, Refactor

#6497 Fix: resolve compile error with USE_ELPA=OFF + BUILD_TESTING=ON and switch to nvtx3 headers when CUDA_VERSION >= 12090
  source/source_base/timer.cpp
  source/source_hsolver/test/CMakeLists.txt
  source/source_hsolver/test/test_diago_hs_para.cpp
Labels: Compile & CICD & Docs & Dependencies, Refactor

#6499 [Bug] Fix dsp compilation error
  source/source_main/driver_run.cpp
Labels: GPU & DCU & HPC, Refactor

#6498 Fix: Fix crash in Debug build with multi-GPU due to forced cudaSetDevice(0)
  source/source_base/module_device/device.h
  source/source_base/module_device/output_device.cpp
Labels: Bugs, GPU & DCU & HPC, Refactor

#6505 Fix : add overlap output for deepks_out_freq_elec
  source/source_lcao/module_deepks/LCAO_deepks_interface.cpp
  tests/09_DeePKS/103_NO_GO_deepks_out_freq_elec/result.ref
  tests/09_DeePKS/103_NO_KP_deepks_out_freq_elec/result.ref
  tests/integrate/tools/catch_deepks_properties.sh
Labels: Refactor, Machine Learning

#6503 Fix: correct an output in LR hsolver
  source/source_lcao/module_lr/hsolver_lrtd.hpp
Labels: Refactor

#6480 Tests: Update DeePKS UT to make sure it covers some checks.
  source/source_lcao/module_deepks/deepks_basic.cpp
  source/source_lcao/module_deepks/deepks_vdrpre.cpp
  source/source_lcao/module_deepks/test/LCAO_deepks_test.cpp
  tests/09_DeePKS/100_NO_GO_deepks_UT/E_delta_bands_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/E_delta_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/F_delta_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/descriptor_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/dphialpha_x_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/dphialpha_y_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/dphialpha_z_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/gdmepsl_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/gdmx_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/gedm_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/gvepsl_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/gvx_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/jle.orb
  tests/09_DeePKS/100_NO_GO_deepks_UT/model.ptg
  tests/09_DeePKS/100_NO_GO_deepks_UT/o_delta_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/orbpre_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/pdm_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/phialpha_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/stress_delta_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/vdpre_ref.dat
  tests/09_DeePKS/100_NO_GO_deepks_UT/vdrpre_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/E_delta_bands_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/E_delta_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/F_delta_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/STRU
  tests/09_DeePKS/100_NO_KP_deepks_UT/descriptor_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_0
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_1
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_2
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_3
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_4
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_5
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_6
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_7
  tests/09_DeePKS/100_NO_KP_deepks_UT/dm_8
  tests/09_DeePKS/100_NO_KP_deepks_UT/dphialpha_x_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/dphialpha_y_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/dphialpha_z_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/gdmepsl_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/gdmx_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/gedm_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/gvepsl_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/gvx_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/jle.orb
  tests/09_DeePKS/100_NO_KP_deepks_UT/model.ptg
  tests/09_DeePKS/100_NO_KP_deepks_UT/o_delta_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/orbpre_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/pdm_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/phialpha_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/stress_delta_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/vdpre_ref.dat
  tests/09_DeePKS/100_NO_KP_deepks_UT/vdrpre_ref.dat
Labels: Machine Learning, Unit Tests/Integreate Tests

#6509 1. Improve output accuracy of Exx_Opt_Orb
  docs/advanced/input_files/input-main.md
  source/source_hamilt/module_xc/exx_info.h
  source/source_io/module_parameter/input_parameter.h
  source/source_io/test/read_input_ptest.cpp
  source/source_io/test/support/INPUT
  source/source_lcao/module_ri/exx_opt_orb-print.cpp
Labels: EXX and lr-TDDFT, Refactor

#6431 Refactor: EXX PW Code Structure
  source/Makefile.Objects
  source/source_cell/pseudo.cpp
  source/source_esolver/esolver_ks_pw.cpp
  source/source_io/module_parameter/input_parameter.h
  source/source_io/read_input_item_other.cpp
  source/source_pw/module_pwdft/CMakeLists.txt
  source/source_pw/module_pwdft/module_exx_helper/exx_helper.cpp
  source/source_pw/module_pwdft/module_exx_helper/exx_helper.h
  source/source_pw/module_pwdft/operator_pw/CMakeLists.txt
  source/source_pw/module_pwdft/operator_pw/exx_pw_ace.cpp
  source/source_pw/module_pwdft/operator_pw/exx_pw_pot.cpp
  source/source_pw/module_pwdft/operator_pw/op_exx_pw.cpp
  source/source_pw/module_pwdft/operator_pw/op_exx_pw.h
  source/source_pw/module_pwdft/stress_func_exx.cpp
Labels: EXX and lr-TDDFT, Refactor

#6508 [Refactor] Move module_fft to source_base
  source/Makefile.Objects
  source/source_base/kernels/dsp/dsp_connector.cpp
  source/source_base/module_fft/fft_base.h
  source/source_base/module_fft/fft_bundle.cpp
  source/source_base/module_fft/fft_bundle.h
  source/source_base/module_fft/fft_cpu.cpp
  source/source_base/module_fft/fft_cpu.h
  source/source_base/module_fft/fft_cpu_float.cpp
  source/source_base/module_fft/fft_cuda.cpp
  source/source_base/module_fft/fft_cuda.h
  source/source_base/module_fft/fft_dsp.cpp
  source/source_base/module_fft/fft_dsp.h
  source/source_base/module_fft/fft_dsp_float.cpp
  source/source_base/module_fft/fft_rocm.cpp
  source/source_base/module_fft/fft_rocm.h
  source/source_basis/module_pw/CMakeLists.txt
  source/source_basis/module_pw/pw_basis.h
  source/source_basis/module_pw/pw_transform.cpp
  source/source_basis/module_pw/test_serial/CMakeLists.txt
  source/source_estate/test/CMakeLists.txt
  source/source_estate/test/charge_extra_test.cpp
  source/source_estate/test/elecstate_base_test.cpp
  source/source_hamilt/module_xc/test/CMakeLists.txt
  source/source_hsolver/test/CMakeLists.txt
  source/source_hsolver/test/hsolver_pw_sup.h
Labels: Refactor, The Absolute Zero

#6514 Fix a minor bug in `v_xc` timer
  source/source_hamilt/module_xc/xc_functional_vxc.cpp
Labels: Bugs

#6518 Fix: fix output bug
  source/source_estate/elecstate_print.cpp
Labels: Refactor

#6515 Fix: fix memory leak in gint module
  source/source_lcao/module_gint/gint_old.cpp
  source/source_lcao/module_gint/temp_gint/gint_common.cpp
Labels: Bugs, GPU & DCU & HPC, Refactor

#6490 Feature: add DFT-1/2 and shell DFT-1/2, only support PW esolvers_ks_pw.
  source/Makefile.Objects
  source/source_cell/CMakeLists.txt
  source/source_cell/module_symmetry/test/symmetry_test_analysis.cpp
  source/source_cell/module_symmetry/test/symmetry_test_symtrz.cpp
  source/source_cell/sep.cpp
  source/source_cell/sep.h
  source/source_cell/sep_cell.cpp
  source/source_cell/sep_cell.h
  source/source_cell/test/CMakeLists.txt
  source/source_cell/test/bcast_read_sep_test.sh
  source/source_cell/test/bcast_sep_cell_test.sh
  source/source_cell/test/klist_test.cpp
  source/source_cell/test/klist_test_para.cpp
  source/source_cell/test/read_sep_test.cpp
  source/source_cell/test/sepcell_test.cpp
  source/source_cell/test/support/C_ca_50.sep
  source/source_cell/test/support/F_pbe_50.sep
  source/source_cell/test/support/STRU_LiF
  source/source_cell/test/support/STRU_LiF_Warning1
  source/source_cell/test/support/mock_unitcell.cpp
  source/source_cell/test_pw/CMakeLists.txt
  source/source_cell/unitcell.cpp
  source/source_cell/unitcell.h
  source/source_esolver/esolver_ks_pw.cpp
  source/source_esolver/esolver_ks_pw.h
  source/source_esolver/test/for_test.h
  source/source_estate/CMakeLists.txt
  source/source_estate/module_dm/test/tmp_mocks.cpp
  source/source_estate/module_pot/pot_sep.cpp
  source/source_estate/module_pot/pot_sep.h
  source/source_estate/module_pot/potential_new.cpp
  source/source_estate/module_pot/potential_new.h
  source/source_estate/module_pot/potential_types.cpp
  source/source_estate/test/elecstate_base_test.cpp
  source/source_estate/test/elecstate_print_test.cpp
  source/source_estate/test/elecstate_pw_test.cpp
  source/source_estate/test/potential_new_test.cpp
  source/source_hamilt/module_surchem/test/setcell.h
  source/source_hamilt/module_vdw/test/vdw_test.cpp
  source/source_hamilt/module_xc/test/xc3_mock.h
  source/source_io/module_parameter/input_parameter.h
  source/source_io/read_input_item_elec_stru.cpp
  source/source_io/test/bessel_basis_test.cpp
  source/source_io/test/for_testing_klist.h
  source/source_io/test/outputlog_test.cpp
  source/source_io/test/read_wf2rho_pw_test.cpp
  source/source_lcao/module_deepks/test/CMakeLists.txt
  source/source_lcao/module_hcontainer/test/tmp_mocks.cpp
  source/source_lcao/module_lr/ri_benchmark/test/ri_benchmark_test.cpp
  source/source_lcao/module_operator_lcao/test/tmp_mocks.cpp
  source/source_lcao/module_ri/module_exx_symmetry/test/symmetry_rotation_test.cpp
  source/source_md/test/CMakeLists.txt
  source/source_pw/module_pwdft/CMakeLists.txt
  source/source_pw/module_pwdft/VSep_in_pw.cpp
  source/source_pw/module_pwdft/VSep_in_pw.h
  source/source_pw/module_pwdft/hamilt_pw.cpp
  source/source_pw/module_pwdft/test/CMakeLists.txt
  source/source_relax/test/for_test.h
  source/source_relax/test/relax_test.h
Labels: Features Needed

#6521 Fix: replace fflush with flush
  source/source_estate/elecstate_print.cpp
Labels: Bugs, Refactor

#6532 Fix: Plug memory leak in dav_subspace
  source/source_hsolver/diago_dav_subspace.cpp
  source/source_hsolver/diago_dav_subspace.h
Labels: Bugs, Refactor, Diago, Memory

#6527 Move some codes out of esolver_fp
  docs/advanced/input_files/input-main.md
  source/Makefile.Objects
  source/source_esolver/esolver_fp.cpp
  source/source_esolver/esolver_fp.h
  source/source_esolver/esolver_of.cpp
  source/source_estate/elecstate.h
  source/source_io/CMakeLists.txt
  source/source_io/ctrl_output_fp.cpp
  source/source_io/ctrl_output_fp.h
Labels: Refactor, The Absolute Zero

#6548 [Feature] Adapt ABACUS to newest version of mtblas and mtfft
  source/source_base/kernels/dsp/dsp_connector.cpp
  source/source_base/module_fft/fft_dsp.cpp
Labels: GPU & DCU & HPC

#6538 [Feature] TD-OFDFT
  source/Makefile.Objects
  source/source_esolver/CMakeLists.txt
  source/source_esolver/esolver.cpp
  source/source_esolver/esolver_of.h
  source/source_esolver/esolver_of_tddft.cpp
  source/source_esolver/esolver_of_tddft.h
  source/source_io/read_input_item_system.cpp
  source/source_pw/module_ofdft/CMakeLists.txt
  source/source_pw/module_ofdft/evolve_ofdft.cpp
  source/source_pw/module_ofdft/evolve_ofdft.h
Labels: Features Needed, Refactor
