Repository deepmodeling/abacus-develop, pull requests merged in 2025-08, with the labels that each got.

#6424 fix bug in Pseudopot_upf::set_empty_element()
  source/module_cell/read_pp.cpp
Labels: Bugs, Refactor

#6427 Perf: add cuda support for cal_force_loc
  source/source_pw/module_pwdft/forces.cpp
  source/source_pw/module_pwdft/kernels/cuda/force_op.cu
  source/source_pw/module_pwdft/kernels/force_op.h
Labels: GPU & DCU & HPC, Refactor

#6428 Fix: dav_subspace for uspp
  python/pyabacus/src/hsolver/py_diago_dav_subspace.hpp
  source/source_hsolver/diago_dav_subspace.cpp
  source/source_hsolver/diago_dav_subspace.h
  source/source_hsolver/hsolver_pw.cpp
  source/source_lcao/module_lr/hsolver_lrtd.hpp
  tools/stm/stm.py
Labels: Bugs, Refactor

#6438 Fix the misleading annotation of `soc_lambda`
  source/source_io/module_parameter/input_parameter.h
  source/source_io/read_input_item_elec_stru.cpp
  source/source_io/test/support/INPUT
Labels: Compile & CICD & Docs & Dependencies, Input&Output, Refactor

#6446 Fix: Fix regex pattern for extracting version in version_check.yml
  .github/workflows/version_check.yml
Labels: Refactor

#6448 Perf: add cuda version of cal_force_ew
  source/source_pw/module_pwdft/forces.cpp
  source/source_pw/module_pwdft/kernels/cuda/force_op.cu
  source/source_pw/module_pwdft/kernels/force_op.h
Labels: Performance, GPU & DCU & HPC, Refactor

#6451 Toolchain intel update to fix issue #6190
  toolchain/build_abacus_intel.sh
  toolchain/scripts/patches/6190.patch
  toolchain/scripts/stage4/install_cereal.sh
  toolchain/scripts/stage4/install_libri.sh
  toolchain/toolchain_intel.sh
Labels: Compile & CICD & Docs & Dependencies, Refactor

#6460 Perf: Accelerate cal_overlap in get_s calculation.
  source/source_base/vector3.h
  source/source_basis/module_ao/ORB_gaunt_table.cpp
  source/source_basis/module_ao/ORB_gaunt_table.h
  source/source_lcao/center2_orb-orb11.cpp
  source/source_lcao/center2_orb-orb21.cpp
Labels: Performance, Refactor

#6461 Fix a bug caused by libtorch>=2.6.0.
  docs/quick_start/easy_install.md
  source/source_lcao/module_deepks/deepks_basic.cpp
  source/source_lcao/module_deepks/deepks_descriptor.cpp
  toolchain/build_abacus_intel.sh
Labels: Bugs, Refactor, Machine Learning

#6466 Fix: Name conflict in pyabacus.
  python/pyabacus/src/ModuleNAO/py_m_nao.cpp
  python/pyabacus/src/pyabacus/ModuleNAO/_module_nao.py
  python/pyabacus/src/pyabacus/io/stru.py
  python/pyabacus/tests/test_m_nao.py
  source/source_basis/module_nao/two_center_integrator.cpp
Labels: Bugs, pyabacus
