Repository deepmodeling/abacus-develop, pull requests merged in 2025-07, with the labels that each got.

#6349 Refactor: Refactor KEDF management in ESolver_OF
  source/Makefile.Objects
  source/source_esolver/esolver_of.cpp
  source/source_esolver/esolver_of.h
  source/source_esolver/esolver_of_interface.cpp
  source/source_esolver/esolver_of_tool.cpp
  source/source_pw/hamilt_ofdft/CMakeLists.txt
  source/source_pw/hamilt_ofdft/kedf_manager.cpp
  source/source_pw/hamilt_ofdft/kedf_manager.h
  source/source_pw/hamilt_ofdft/kedf_ml.cpp
  source/source_pw/hamilt_ofdft/kedf_ml.h
Labels: Refactor, The Absolute Zero

#6354 Fix: Add MPI synchronization for `ekb` band energy tensor, and now GPU CI/CD test case `07_NO_EDM_TDDFT_GPU` is functional again
  source/source_esolver/esolver_ks_lcao_tddft.cpp
  source/source_estate/module_dm/cal_edm_tddft.cpp
  source/source_lcao/module_rt/evolve_elec.cpp
  tests/15_rtTDDFT_GPU/CASES_GPU.txt
Labels: Bugs, Refactor

#6351 Feature: long-range corrected hybrid functionals implementation with Spencer-Alavi truncation Coulomb potential
  docs/advanced/input_files/input-main.md
  source/module_parameter/input_parameter.h
  source/source_hamilt/module_vdw/vdwd3_autoset_xcname.cpp
  source/source_hamilt/module_xc/exx_info.h
  source/source_hamilt/module_xc/xc_functional.cpp
  source/source_hamilt/module_xc/xc_functional_libxc.cpp
  source/source_io/input_conv.cpp
  source/source_io/read_input_item_exx_dftu.cpp
  source/source_io/test/read_input_ptest.cpp
  source/source_io/test/support/INPUT
  source/source_io/test_serial/read_input_item_test.cpp
  source/source_lcao/module_ri/Exx_LRI.h
  source/source_lcao/module_ri/Exx_LRI.hpp
  source/source_lcao/module_ri/RI_Util.h
  source/source_lcao/module_ri/RI_Util.hpp
  source/source_lcao/module_ri/conv_coulomb_pot_k.cpp
  source/source_lcao/module_ri/conv_coulomb_pot_k.h
  source/source_lcao/module_ri/conv_coulomb_pot_k.hpp
  tests/08_EXX/13_NO_KP_CAMPBEH/INPUT
  tests/08_EXX/13_NO_KP_CAMPBEH/KPT
  tests/08_EXX/13_NO_KP_CAMPBEH/README
  tests/08_EXX/13_NO_KP_CAMPBEH/STRU
  tests/08_EXX/13_NO_KP_CAMPBEH/result.ref
  tests/08_EXX/CASES_CPU.txt
Labels: EXX and lr-TDDFT, Features Needed, Refactor

#6363 Refactor: the initialization scheme in LRI_CV
  source/source_lcao/module_ri/ABFs_Construct-PCA.cpp
  source/source_lcao/module_ri/Exx_LRI.h
  source/source_lcao/module_ri/Exx_LRI.hpp
  source/source_lcao/module_ri/LRI_CV.h
  source/source_lcao/module_ri/LRI_CV.hpp
  source/source_lcao/module_ri/Matrix_Orbs11.cpp
  source/source_lcao/module_ri/Matrix_Orbs11.h
  source/source_lcao/module_ri/Matrix_Orbs21.cpp
  source/source_lcao/module_ri/Matrix_Orbs21.h
  source/source_lcao/module_ri/Matrix_Orbs22.cpp
  source/source_lcao/module_ri/Matrix_Orbs22.h
  source/source_lcao/module_ri/RI_Util.hpp
  source/source_lcao/module_ri/exx_abfs-construct_orbs.cpp
  source/source_lcao/module_ri/exx_abfs-construct_orbs.h
  source/source_lcao/module_ri/exx_opt_orb.cpp
Labels: EXX and lr-TDDFT, Features Needed, Refactor

#6371 Feature: Support linear combination of coulomb_param for EXX PW
  source/source_io/input_conv.cpp
  source/source_pw/module_pwdft/operator_pw/op_exx_pw.cpp
  source/source_pw/module_pwdft/operator_pw/op_exx_pw.h
Labels: EXX and lr-TDDFT, Features Needed, Refactor

#6370 Refactor: Remove redundant Input_para from ESolver Class
  source/source_esolver/esolver_fp.cpp
  source/source_esolver/esolver_ks.cpp
  source/source_esolver/esolver_ks_lcao.cpp
  source/source_esolver/esolver_ks_lcaopw.cpp
  source/source_esolver/esolver_ks_pw.cpp
  source/source_esolver/esolver_of.cpp
  source/source_esolver/esolver_sdft_pw.cpp
Labels: Refactor, The Absolute Zero

#6375 Fix: Fix memory leak introduced by new gint module
  source/source_lcao/module_hcontainer/hcontainer.cpp
  source/source_lcao/module_hcontainer/hcontainer.h
Labels: Bugs, Refactor

#6378 refactor Exx_Opt_Orb
  docs/advanced/input_files/input-main.md
  source/source_esolver/esolver_ks_lcao.cpp
  source/source_esolver/lcao_others.cpp
  source/source_hamilt/module_xc/exx_info.h
  source/source_io/input_conv.cpp
  source/source_io/read_input_item_system.cpp
  source/source_lcao/module_ri/Exx_LRI_interface.hpp
  source/source_lcao/module_ri/Matrix_Orbs22.cpp
  source/source_lcao/module_ri/exx_abfs-construct_orbs.cpp
  source/source_lcao/module_ri/exx_abfs-construct_orbs.h
  source/source_lcao/module_ri/exx_abfs-jle.cpp
  source/source_lcao/module_ri/exx_abfs-jle.h
  source/source_lcao/module_ri/exx_opt_orb-print.cpp
  source/source_lcao/module_ri/exx_opt_orb.cpp
  source/source_lcao/module_ri/exx_opt_orb.h
  source/source_main/driver_run.cpp
Labels: EXX and lr-TDDFT, Features Needed, Refactor

#6372 Add use sw and fix Floating point exception
  CMakeLists.txt
  source/source_base/global_function.cpp
  source/source_basis/module_pw/pw_basis.cpp
  source/source_basis/module_pw/pw_gatherscatter.h
  source/source_cell/module_symmetry/symm_rho.cpp
  source/source_cell/pseudo.cpp
  source/source_cell/pseudo.h
  source/source_cell/read_pp_upf100.cpp
  source/source_cell/read_pp_upf201.cpp
  source/source_estate/module_charge/charge.cpp
  source/source_estate/module_charge/charge_mixing_residual.cpp
  source/source_estate/module_pot/H_Hartree_pw.cpp
  source/source_hamilt/module_ewald/H_Ewald_pw.cpp
  source/source_hamilt/module_surchem/cal_pseudo.cpp
  source/source_hamilt/module_surchem/cal_totn.cpp
  source/source_hamilt/module_surchem/sol_force.cpp
  source/source_io/read_input.cpp
  source/source_pw/module_ofdft/kedf_wt.cpp
  source/source_pw/module_pwdft/VNL_in_pw.cpp
  source/source_pw/module_pwdft/forces.cpp
  source/source_pw/module_pwdft/stress_func_cc.cpp
  source/source_pw/module_pwdft/stress_func_ewa.cpp
  source/source_pw/module_pwdft/stress_func_har.cpp
Labels: Bugs, GPU & DCU & HPC, Refactor

#6381 Update the output formats of rt-TDDFT
  source/source_esolver/esolver_ks_lcao_tddft.cpp
  source/source_estate/elecstate_print.cpp
  source/source_estate/test/elecstate_print_test.cpp
  source/source_io/output_log.cpp
  source/source_md/md_base.cpp
  source/source_md/md_func.cpp
Labels: Input&Output, Refactor, The Absolute Zero

#6391 Feature: Output real space wavefunction and partial charge density when `device=gpu`
  source/source_esolver/esolver_ks_pw.cpp
  source/source_io/get_pchg_pw.h
  source/source_io/get_wf_pw.h
  tests/11_PW_GPU/006_PW_get_wf_GPU/INPUT
  tests/11_PW_GPU/006_PW_get_wf_GPU/KPT
  tests/11_PW_GPU/006_PW_get_wf_GPU/README
  tests/11_PW_GPU/006_PW_get_wf_GPU/STRU
  tests/11_PW_GPU/006_PW_get_wf_GPU/result.ref
  tests/11_PW_GPU/BUG_PW_outwfcr_GPU/INPUT
  tests/11_PW_GPU/BUG_PW_outwfcr_GPU/README
  tests/11_PW_GPU/BUG_PW_outwfcr_GPU/result.ref
  tests/11_PW_GPU/CASES_GPU.txt
Labels: GPU & DCU & HPC, Features Needed, Refactor

#6396 Clean dependency: remove headers scalapack_connector that are not actually referenced
  source/source_hsolver/diago_elpa.cpp
  source/source_hsolver/diago_elpa_native.cpp
  source/source_hsolver/test/diago_elpa_utils.h
  source/source_hsolver/test/diago_lcao_cusolver_test.cpp
  source/source_hsolver/test/diago_lcao_test.cpp
  source/source_io/write_vxc_r.hpp
  source/source_lcao/module_deltaspin/cal_mw.cpp
  source/source_lcao/module_dftu/dftu.cpp
  source/source_lcao/module_rt/evolve_psi.cpp
  source/source_lcao/module_rt/propagator.cpp
Labels: The Absolute Zero

#6399 Fix CUDA warning by including internal header file device_functions.h that is not allowed
  source/source_lcao/module_gint/test/test_sph.cu
Labels: The Absolute Zero

#6403 Fix control flow of occNum_func in rdmft_tools to include default value control flow
  source/source_lcao/module_rdmft/rdmft_tools.cpp
Labels: Refactor

#6404 Fix: fix exx_gamma_extrapolation error in MPI
  source/source_pw/module_pwdft/operator_pw/op_exx_pw.cpp
Labels: Bugs, EXX and lr-TDDFT, Refactor

#6400 Remove lapack_connector.h that are not referenced
  source/source_esolver/esolver_ks_lcao_tddft.cpp
  source/source_hsolver/diago_dav_subspace.cpp
  source/source_hsolver/diago_elpa.cpp
  source/source_hsolver/diago_elpa_native.cpp
  source/source_hsolver/diago_iter_assist.cpp
  source/source_io/berryphase.cpp
  source/source_io/numerical_descriptor.cpp
  source/source_io/to_wannier90.h
  source/source_io/to_wannier90_lcao.h
  source/source_io/to_wannier90_lcao_in_pw.h
  source/source_io/to_wannier90_pw.h
  source/source_io/unk_overlap_pw.h
  source/source_lcao/module_rt/band_energy.cpp
  source/source_lcao/module_rt/evolve_psi.cpp
  source/source_lcao/module_rt/middle_hamilt.cpp
  source/source_lcao/module_rt/norm_psi.cpp
  source/source_lcao/module_rt/propagator.cpp
  source/source_lcao/module_rt/propagator_cn2.cpp
  source/source_lcao/module_rt/propagator_etrs.cpp
  source/source_lcao/module_rt/propagator_taylor.cpp
  source/source_lcao/module_rt/solve_propagation.cpp
  source/source_lcao/module_rt/upsi.cpp
  source/source_pw/module_pwdft/operator_pw/op_exx_pw.cpp
  source/source_relax/bfgs.cpp
  source/source_relax/bfgs.h
  source/source_relax/lbfgs.h
Labels: The Absolute Zero

#6414 Fix: Numerical error in pyabacus.
  python/pyabacus/src/ModuleNAO/py_m_nao.cpp
  python/pyabacus/tests/test_m_nao.py
  source/source_basis/module_nao/numerical_radial.cpp
Labels: Bugs, Refactor

#6411 Fix: wrong name in cuda "lapack" interface
  source/source_base/module_container/ATen/kernels/cuda/lapack.cu
  tests/16_SDFT_GPU/187_PW_SDFT_MALL_BPCG_GPU/result.ref
Labels: Bugs, Refactor
