Repository deepmodeling/abacus-develop, pull requests merged in 2025-03, with the labels that each got.

#5942 [Test] Remove pre-commit bot
  .github/workflows/test.yml
Labels: Compile & CICD & Docs & Dependencies

#5941 Delete conv_esolver in esolver, and add 'conv_esolver' as a parameter in iter_finish, after_scf, and update_pot functions
  source/Makefile.Objects
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_lcaopw.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of.h
  source/module_esolver/esolver_of_tool.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/esolver_sdft_pw.h
  source/module_esolver/lcao_after_scf.cpp
  source/module_hamilt_lcao/module_gint/temp_gint/gint_atom.h
  source/module_hamilt_lcao/module_gint/temp_gint/localcell_info.h
  source/module_io/output_log.cpp
  source/module_io/output_log.h
Labels: The Absolute Zero

#5943 Refactor: before_scf of esolver_fp
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/lcao_before_scf.cpp
Labels: The Absolute Zero

#5945 Refactor: remove useless head files
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_sdft_pw.cpp
Labels: The Absolute Zero

#5946 Feature: add nbands_mul for setting multiply for default nbands and fix initial mag for SOC
  docs/advanced/input_files/input-main.md
  source/module_cell/read_atoms.cpp
  source/module_elecstate/cal_nelec_nband.cpp
  source/module_io/read_input_item_elec_stru.cpp
  source/module_parameter/input_parameter.h
  tests/integrate/104_PW_NC_magnetic/result.ref
  tests/integrate/140_PW_15_SO/README
  tests/integrate/140_PW_15_SO/result.ref
  tests/integrate/140_PW_15_SO_wfcinit/STRU
  tests/integrate/204_NO_KP_NC/INPUT
  tests/integrate/204_NO_KP_NC/result.ref
  tests/integrate/240_NO_KP_15_SO/result.ref
  tests/integrate/240_NO_KP_15_SO_average/result.ref
Labels: Input&Output, Refactor

#5954 Refactor:Modify the output functions in elecstate.
  source/module_elecstate/elecstate.h
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/elecstate_print.h
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_hsolver/test/hsolver_supplementary_mock.h
Labels: The Absolute Zero

#5949 Feature: support the `default` as the value of `dft_functional` when initialize vdw
  source/module_hamilt_general/module_vdw/test/vdw_test.cpp
  source/module_hamilt_general/module_vdw/vdw.cpp
  source/module_hamilt_general/module_vdw/vdw.h
  source/module_hamilt_general/module_vdw/vdwd3_autoset_xcparam.cpp
  source/module_hamilt_general/module_vdw/vdwd3_parameters.cpp
  source/module_hamilt_general/module_vdw/vdwd3_parameters.h
Labels: Input&Output, Refactor

#5956 Perf: openmp for cal_force_stress
  source/module_elecstate/module_charge/charge_mixing.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/dftu_force_stress.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/dspin_force_stress.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_new.h
Labels: GPU & DCU & HPC, Refactor

#5957 Update after_scf in ESolver
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/lcao_after_scf.cpp
Labels: The Absolute Zero

#5952 Refactor: Remove GlobalV in DeePKS and simplify some functions.
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/lcao_after_scf.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/operator_lcao.cpp
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.h
  source/module_hamilt_lcao/module_deepks/deepks_basic.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.h
  source/module_hamilt_lcao/module_deepks/deepks_descriptor.cpp
  source/module_hamilt_lcao/module_deepks/deepks_descriptor.h
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.h
  source/module_hamilt_lcao/module_deepks/deepks_iterate.cpp
  source/module_hamilt_lcao/module_deepks/deepks_iterate.h
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.h
  source/module_hamilt_lcao/module_deepks/deepks_phialpha.cpp
  source/module_hamilt_lcao/module_deepks/deepks_phialpha.h
  source/module_hamilt_lcao/module_deepks/deepks_spre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_spre.h
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.h
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp
  source/module_hamilt_lcao/module_hcontainer/hcontainer.h
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.cpp
  tests/integrate/201_NO_15_f_pseudopots/refdata-DMR-sparse_SPIN0.csr
Labels: The Absolute Zero, DeePKS

#5963 Update ESolver, delete pelec->charge, instead using chr defined in ESolver_fp directly
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of_interface.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/pw_others.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
Labels: The Absolute Zero

#5965 Doc: add OpenMPI usage recommendations and fix doc error
  docs/community/faq.md
  docs/quick_start/easy_install.md
Labels: Compile & CICD & Docs & Dependencies, Refactor

#5967 Performance: Optimize para_gemm and para_linear_transform
  source/module_base/kernels/cuda/math_kernel_op.cu
  source/module_base/kernels/math_kernel_op.cpp
  source/module_base/kernels/math_kernel_op.h
  source/module_base/kernels/rocm/math_kernel_op.hip.cu
  source/module_base/kernels/test/math_kernel_test.cpp
  source/module_base/para_gemm.cpp
  source/module_base/para_gemm.h
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/para_linear_transform.cpp
  source/module_hsolver/para_linear_transform.h
  tests/integrate/102_PW_BPCG_BP/result.ref
Labels: GPU & DCU & HPC, Refactor

#5968 Feature: Add HR output label for DeePKS.
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_after_scf.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/deepks_basic.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.h
  source/module_hamilt_lcao/module_deepks/deepks_descriptor.cpp
  source/module_hamilt_lcao/module_deepks/deepks_descriptor.h
  source/module_hamilt_lcao/module_deepks/deepks_fpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.h
  source/module_hamilt_lcao/module_deepks/deepks_hmat.cpp
  source/module_hamilt_lcao/module_deepks/deepks_hmat.h
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.h
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.h
  source/module_hamilt_lcao/module_deepks/deepks_spre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_spre.h
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.h
  source/module_hamilt_lcao/module_deepks/test/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.cpp
Labels: Refactor, DeePKS

#5962 perf the compute of check_atom_stru and add openmp
  source/module_cell/check_atomic_stru.cpp
  source/module_cell/test/unitcell_test_readpp.cpp
Labels: Performance, Refactor

#5971 Fix: Fix a LaTeX rendering issue related to RT-TDDFT parameters in online documentation
  docs/advanced/input_files/input-main.md
Labels: Compile & CICD & Docs & Dependencies

#5973 Refactor: in ESolver_KS_PW, calculate deband in iter_finish, not in hamilt2density
  source/module_esolver/esolver_ks_pw.cpp
Labels: Refactor

#5972 Some small updates for the format
  source/module_elecstate/cal_ux.cpp
  source/module_elecstate/magnetism.cpp
  source/module_elecstate/magnetism.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_others.cpp
  source/module_esolver/pw_others.cpp
Labels: The Absolute Zero

#5974 Fix wavefunction output logic of ks pw
  source/module_esolver/esolver_ks_pw.cpp
Labels: Bugs, Refactor

#5976 Fix: BPCG results not stable when using CUDA AWare MPI
  source/module_base/para_gemm.cpp
  source/module_hsolver/para_linear_transform.cpp
Labels: GPU & DCU & HPC

#5979 Refactor: decrease memory cost of get_s
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
Labels: Bugs, Refactor

#5984 Update timer, only print out those timers that consume more than 1% of total time
  source/driver_run.cpp
  source/module_base/mathzone_add1.cpp
  source/module_base/module_mixing/broyden_mixing.cpp
  source/module_base/timer.cpp
  source/module_cell/check_atomic_stru.cpp
  source/module_cell/check_atomic_stru.h
  source/module_cell/module_neighbor/sltk_grid.cpp
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_cell/test/unitcell_test_readpp.cpp
  source/module_elecstate/module_charge/charge.cpp
  source/module_elecstate/module_charge/charge.h
  source/module_elecstate/module_charge/charge_mixing_residual.cpp
  source/module_elecstate/module_charge/charge_mixing_rho.cpp
  source/module_elecstate/potentials/pot_local.cpp
  source/module_elecstate/potentials/potential_new.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/pulay_force_stress_center2.cpp
  source/module_hamilt_lcao/module_tddft/evolve_psi.cpp
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_ewa.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_gga.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_har.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_kin.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_loc.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_mgga.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_nl.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_onsite.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_func_us.cpp
  source/module_hsolver/diago_bpcg.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_psi/psi_initializer.cpp
  source/module_psi/psi_initializer_atomic.cpp
  source/module_psi/psi_initializer_file.cpp
  source/module_psi/psi_initializer_nao.cpp
  source/module_psi/psi_initializer_random.cpp
Labels: The Absolute Zero

#5985 Refactor:Modify Weights and Ebands Functions in the elecstate Module
  source/Makefile.Objects
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/elecstate.cpp
  source/module_elecstate/elecstate.h
  source/module_elecstate/elecstate_tools.cpp
  source/module_elecstate/elecstate_tools.h
  source/module_elecstate/test/CMakeLists.txt
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_elecstate/test/elecstate_energy_test.cpp
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/hsolver_lcaopw.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_io/test/read_wfc_nao_test.cpp
  source/module_rdmft/update_state_rdmft.cpp
Labels: The Absolute Zero

#5940 Feature: Hybrid functionals for planewave basis
  examples/hse/pw_Si2/INPUT
  examples/hse/pw_Si2/KPT
  examples/hse/pw_Si2/STRU
  source/Makefile.Objects
  source/module_elecstate/elecstate.h
  source/module_elecstate/elecstate_exx.cpp
  source/module_elecstate/potentials/potential_new.h
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_ks_pw.h
  source/module_hamilt_general/module_xc/xc_functional.cpp
  source/module_hamilt_general/operator.h
  source/module_hamilt_lcao/module_tddft/propagator.h
  source/module_hamilt_pw/hamilt_pwdft/CMakeLists.txt
  source/module_hamilt_pw/hamilt_pwdft/global.h
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.h
  source/module_hamilt_pw/hamilt_pwdft/module_exx_helper/exx_helper.cpp
  source/module_hamilt_pw/hamilt_pwdft/module_exx_helper/exx_helper.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/op_exx_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/op_exx_pw.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_exx.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_pw.h
  source/module_io/input_conv.cpp
  source/module_io/read_input_item_exx_dftu.cpp
  source/module_io/read_input_item_other.cpp
  source/module_parameter/input_parameter.h
  source/module_psi/psi.cpp
  source/module_psi/psi.h
Labels: Features Needed

#5992 Refactor: move psi init to before_all_runners
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_before_scf.cpp
Labels: The Absolute Zero

#5993 Fix: One segmentation fault related to EXX PW
  source/module_hamilt_pw/hamilt_pwdft/module_exx_helper/exx_helper.h
Labels: Bugs, Refactor

#6007 v3.9.0.2
  source/version.h
Labels: Features Needed

#5989 Tests: Add GPU tests for out_wfc_pw & out_wfc_r
  tests/integrate/107_PW_outWfcPw_GPU/INPUT
  tests/integrate/107_PW_outWfcPw_GPU/KPT
  tests/integrate/107_PW_outWfcPw_GPU/STRU
  tests/integrate/107_PW_outWfcPw_GPU/jd
  tests/integrate/107_PW_outWfcPw_GPU/result.ref
  tests/integrate/107_PW_outWfcR_GPU/INPUT
  tests/integrate/107_PW_outWfcR_GPU/KPT
  tests/integrate/107_PW_outWfcR_GPU/STRU
  tests/integrate/107_PW_outWfcR_GPU/jd
  tests/integrate/107_PW_outWfcR_GPU/result.ref
  tests/integrate/CASES_GPU.txt
Labels: GPU & DCU & HPC, Compile & CICD & Docs & Dependencies, Input&Output

#6008 Doc: fix the format
  docs/index.rst
Labels: Compile & CICD & Docs & Dependencies

#6018 Fix : out_mat_dh will lead to different result with MPI-1core with MPI-4core
  source/module_hamilt_lcao/hamilt_lcaodft/spar_dh.cpp
Labels: Bugs, Refactor

#6017 [Fix] Fix DCU port compilation error
  source/module_base/module_device/rocm/memory_op.hip.cu
Labels: GPU & DCU & HPC, Compile & CICD & Docs & Dependencies

#6013 Feature: Make KG-KSDFT support GPU
  source/module_base/kernels/cuda/math_kernel_op.cu
  source/module_base/kernels/math_kernel_op.cpp
  source/module_base/kernels/math_kernel_op.h
  source/module_base/kernels/rocm/math_kernel_op.hip.cu
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/elecond.cpp
  source/module_hamilt_pw/hamilt_pwdft/elecond.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/velocity_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/velocity_pw.h
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.h
  tests/integrate/186_PW_KG_100_GPU/INPUT
  tests/integrate/186_PW_KG_100_GPU/KPT
  tests/integrate/186_PW_KG_100_GPU/README
  tests/integrate/186_PW_KG_100_GPU/STRU
  tests/integrate/186_PW_KG_100_GPU/refOnsager.txt
  tests/integrate/186_PW_KG_100_GPU/result.ref
  tests/integrate/CASES_GPU.txt
Labels: GPU & DCU & HPC, Features Needed, Refactor

#6022 Add genelpa warning if matrix is not positive definite
  source/module_hsolver/genelpa/blas.h
  source/module_hsolver/genelpa/elpa_new_complex.cpp
  source/module_hsolver/genelpa/elpa_new_real.cpp
Labels: Bugs, Refactor

#6035 Update latest Intel oneAPI default compiler for cxx
  docs/quick_start/easy_install.md
Labels: Compile & CICD & Docs & Dependencies, Refactor

#6014 Add two LCAO base group GPU version compilation options in toolchain
  CMakeLists.txt
  toolchain/README.md
  toolchain/build_abacus_gnu-aocl.sh
  toolchain/build_abacus_gnu.sh
  toolchain/build_abacus_intel.sh
  toolchain/install_abacus_toolchain.sh
  toolchain/scripts/stage3/install_elpa.sh
  toolchain/scripts/tool_kit.sh
  toolchain/toolchain_amd.sh
  toolchain/toolchain_gnu.sh
  toolchain/toolchain_intel-mpich.sh
  toolchain/toolchain_intel.sh
Labels: GPU & DCU & HPC, Compile & CICD & Docs & Dependencies

#6027 Fix: Angular momentum quantum number check in reading SOC pseudopot file
  source/module_cell/read_pp_upf100.cpp
  source/module_cell/test/read_pp_test.cpp
  source/module_cell/test/support/Si.rel-pbe-rrkj.UPF
Labels: Bugs, non-collinear/SOC

#6033 exclude toolchain/install/ in `.gitignore` after toolchain run
  .gitignore
Labels: Compile & CICD & Docs & Dependencies

#6005 add LBFGS method
  source/Makefile.Objects
  source/module_io/read_input_item_relax.cpp
  source/module_relax/CMakeLists.txt
  source/module_relax/relax_driver.cpp
  source/module_relax/relax_old/bfgs.cpp
  source/module_relax/relax_old/bfgs.h
  source/module_relax/relax_old/ions_move_methods.cpp
  source/module_relax/relax_old/ions_move_methods.h
  source/module_relax/relax_old/lbfgs.cpp
  source/module_relax/relax_old/lbfgs.h
  source/module_relax/relax_old/matrix_methods.cpp
  source/module_relax/relax_old/matrix_methods.h
  source/module_relax/relax_old/relax_old.cpp
  source/module_relax/relax_old/relax_old.h
  source/module_relax/relax_old/test/CMakeLists.txt
  source/module_relax/relax_old/test/bfgs_test.cpp
Labels: Features Needed

#6046 Feature: Make sKG support GPU
  source/CMakeLists.txt
  source/module_base/blas_connector.cpp
  source/module_base/kernels/cuda/math_kernel_op_vec.cu
  source/module_base/kernels/math_kernel_op.h
  source/module_base/kernels/math_kernel_op_vec.cpp
  source/module_base/kernels/rocm/math_kernel_op_vec.hip.cu
  source/module_base/kernels/test/math_kernel_test.cpp
  source/module_base/math_chebyshev.cpp
  source/module_base/para_gemm.cpp
  source/module_base/parallel_device.h
  source/module_basis/module_pw/module_fft/fft_bundle.cpp
  source/module_basis/module_pw/module_fft/fft_bundle.h
  source/module_basis/module_pw/pw_basis.cpp
  source/module_basis/module_pw/pw_basis.h
  source/module_basis/module_pw/pw_basis_k.cpp
  source/module_basis/module_pw/pw_basis_k.h
  source/module_basis/module_pw/test_serial/pw_basis_k_test.cpp
  source/module_elecstate/potentials/potential_new.cpp
  source/module_elecstate/potentials/potential_new.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.h
  source/module_hamilt_pw/hamilt_pwdft/elecond.cpp
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/op_exx_pw.h
  source/module_hamilt_pw/hamilt_pwdft/structure_factor.cpp
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/hamilt_sdft_pw.h
  source/module_hamilt_pw/hamilt_stodft/kernels/hpsi_norm_op.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_dos.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_dos.h
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.h
  source/module_hamilt_pw/hamilt_stodft/sto_tool.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_tool.h
  source/module_hamilt_pw/hamilt_stodft/test/test_sto_tool.cpp
  source/module_hsolver/diago_cg.cpp
  source/module_hsolver/kernels/test/perf_math_kernel.cpp
  source/module_hsolver/para_linear_transform.cpp
  source/module_io/read_set_globalv.cpp
  source/module_parameter/system_parameter.h
  tests/integrate/186_PW_SKG_MALL_GPU/INPUT
  tests/integrate/186_PW_SKG_MALL_GPU/KPT
  tests/integrate/186_PW_SKG_MALL_GPU/README
  tests/integrate/186_PW_SKG_MALL_GPU/STRU
  tests/integrate/186_PW_SKG_MALL_GPU/refOnsager.txt
  tests/integrate/186_PW_SKG_MALL_GPU/result.ref
  tests/integrate/CASES_GPU.txt
Labels: GPU & DCU & HPC, Features Needed

#6043 Fix: Enable EXX PW ACE only when separate_loop is on
  source/module_hamilt_pw/hamilt_pwdft/module_exx_helper/exx_helper.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/op_exx_pw.cpp
  source/module_io/read_input_item_other.cpp
Labels: Features Needed, Refactor

#6019 Fix: directly enter exx loop when init_wfc=="file"
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.hpp
  source/module_ri/Exx_LRI_interface.hpp
Labels: EXX and lr-TDDFT, Refactor

#6049 Fix: DFT+U force&stress with `orbital_corr` of some elements are -1
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/dftu_force_stress.hpp
Labels: Bugs, Refactor

#6038 Fix: add the print header for `cusolvermp` in scf info
  source/module_elecstate/elecstate_print.cpp
Labels: Input&Output, Refactor

#6023 Add templates for recip_to_real in the pw_basis
  source/module_basis/module_pw/CMakeLists.txt
  source/module_basis/module_pw/kernels/cuda/pw_op.cu
  source/module_basis/module_pw/kernels/pw_op.cpp
  source/module_basis/module_pw/kernels/pw_op.h
  source/module_basis/module_pw/kernels/rocm/pw_op.hip.cu
  source/module_basis/module_pw/kernels/test/pw_op_test.cpp
  source/module_basis/module_pw/module_fft/fft_bundle.cpp
  source/module_basis/module_pw/module_fft/fft_bundle.h
  source/module_basis/module_pw/pw_basis.h
  source/module_basis/module_pw/pw_basis_k.h
  source/module_basis/module_pw/pw_transform.cpp
  source/module_basis/module_pw/pw_transform_gpu.cpp
  source/module_basis/module_pw/pw_transform_k.cpp
  source/module_basis/module_pw/pw_transform_k_dsp.cpp
  source/module_elecstate/elecstate_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/veff_pw.cpp
Labels: Refactor

#6039 Reopen unit test for DeePKS multi-k case.
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.h
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.cpp
  source/module_hamilt_lcao/module_hcontainer/output_hcontainer.h
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/result.ref
  tests/deepks/603_NO_deepks_H2O_bandgap/result.ref
  tests/deepks/603_NO_deepks_H2O_multik/result.ref
  tests/deepks/604_NO_deepks_ut_H2O_multik/E_delta_bands_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/E_delta_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/F_delta_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/STRU
  tests/deepks/604_NO_deepks_ut_H2O_multik/descriptor_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/dphialpha_x_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/dphialpha_y_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/dphialpha_z_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmepsl_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmepsl_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmepsl_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmepsl_3_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmepsl_4_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmepsl_5_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmx_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmx_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmx_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmy_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmy_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmy_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmz_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmz_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gdmz_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gedm_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvepsl_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvepsl_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvepsl_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvepsl_3_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvepsl_4_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvepsl_5_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvx_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvx_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvx_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvy_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvy_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvy_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvz_0_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvz_1_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/gvz_2_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/pdm_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/phialpha_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/stress_delta_ref.dat
  tests/deepks/CASES1
Labels: Bugs, Refactor, DeePKS

#6052 Refactor symmetr.cpp, update some output formats in surfchem, etc.
  docs/quick_start/output.md
  source/Makefile.Objects
  source/module_cell/klist.cpp
  source/module_cell/module_symmetry/CMakeLists.txt
  source/module_cell/module_symmetry/symm_analysis.cpp
  source/module_cell/module_symmetry/symm_check.cpp
  source/module_cell/module_symmetry/symm_getgroup.cpp
  source/module_cell/module_symmetry/symm_hermite.cpp
  source/module_cell/module_symmetry/symm_lattice.cpp
  source/module_cell/module_symmetry/symm_magnetic.cpp
  source/module_cell/module_symmetry/symm_other.h
  source/module_cell/module_symmetry/symm_pricell.cpp
  source/module_cell/module_symmetry/symm_rho.cpp
  source/module_cell/module_symmetry/symmetry.cpp
  source/module_cell/module_symmetry/symmetry.h
  source/module_cell/module_symmetry/symmetry_basic.cpp
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_hamilt_general/module_surchem/H_correction_pw.cpp
  source/module_hamilt_general/module_surchem/cal_vcav.cpp
  source/module_hamilt_general/module_surchem/minimize_cg.cpp
  tests/integrate/107_PW_CHG_mismatch/INPUT
  tests/integrate/107_PW_OBOD_MemSaver/INPUT
  tests/integrate/107_PW_OB_outputbands/INPUT
  tests/integrate/801_PW_LT_sc/INPUT
Labels: Input&Output, The Absolute Zero

#6059 Refactor: set dm_to_rho as a new esolver
  source/Makefile.Objects
  source/module_elecstate/elecstate_lcao.cpp
  source/module_esolver/CMakeLists.txt
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver_dm2rho.cpp
  source/module_esolver/esolver_dm2rho.h
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_hsolver/hsolver_lcao.cpp
Labels: The Absolute Zero

#6060 Fix: `nan` values in LCAO band-decomposed charge density (`get_pchg`)
  source/module_io/get_pchg_lcao.cpp
Labels: Bugs

#6061 Feature: write Vxc(R)
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.hpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.h
  source/module_io/read_input_item_output.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_io/write_vxc.hpp
  source/module_io/write_vxc_r.hpp
  source/module_parameter/input_parameter.h
  tests/integrate/307_NO_GO_OXC/INPUT
  tests/integrate/307_NO_GO_OXC/Vxc_R_spin0.ref
  tests/integrate/307_NO_GO_OXC/result.ref
  tests/integrate/tools/catch_properties.sh
Labels: EXX and lr-TDDFT, Refactor

#6055 Feature&Docs: support the indent control on FmtTable
  source/module_base/formatter.h
  source/module_base/test/formatter_test.cpp
  source/module_base/timer.cpp
  source/module_elecstate/elecstate_print.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_hamilt_general/module_vdw/vdwd3_autoset_xcparam.cpp
  source/module_hamilt_lcao/module_deltaspin/spin_constrain.cpp
  source/module_hamilt_pw/hamilt_pwdft/onsite_projector.cpp
  source/module_io/output_log.cpp
  source/module_io/output_mulliken.cpp
Labels: Refactor

#6065 Refactor: Remove some files in DeePKS and add some features.
  source/Makefile.Objects
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/deepks_hmat.cpp
  source/module_hamilt_lcao/module_deepks/deepks_hmat.h
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.h
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdrpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdrpre.h
  source/module_hamilt_lcao/module_deepks/doxygen/conf_dpks
  source/module_hamilt_lcao/module_deepks/sphinx/requirements.txt
  source/module_hamilt_lcao/module_deepks/sphinx/source/conf.py
  source/module_hamilt_lcao/module_deepks/sphinx/source/index.rst
Labels: Bugs, Features Needed, Refactor, DeePKS

#6066 Fix an output for debug
  source/module_ri/Exx_LRI_interface.hpp
Labels: Refactor

#6068 Perf: optimize cal_DMR and folding_HR
  source/module_basis/module_ao/parallel_orbitals.cpp
  source/module_basis/module_ao/parallel_orbitals.h
  source/module_elecstate/module_dm/density_matrix.cpp
  source/module_hamilt_lcao/module_hcontainer/atom_pair.h
  source/module_hamilt_lcao/module_hcontainer/func_folding.cpp
  source/module_hamilt_lcao/module_hcontainer/hcontainer_funcs.h
Labels: Features Needed, Refactor

#6070 Refactor:Change potentials to module_pot
  source/Makefile.Objects
  source/module_elecstate/CMakeLists.txt
  source/module_elecstate/elecstate.h
  source/module_elecstate/elecstate_energy_terms.cpp
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/module_pot/H_Hartree_pw.cpp
  source/module_elecstate/module_pot/H_Hartree_pw.h
  source/module_elecstate/module_pot/H_TDDFT_pw.cpp
  source/module_elecstate/module_pot/H_TDDFT_pw.h
  source/module_elecstate/module_pot/efield.cpp
  source/module_elecstate/module_pot/efield.h
  source/module_elecstate/module_pot/gatefield.cpp
  source/module_elecstate/module_pot/gatefield.h
  source/module_elecstate/module_pot/pot_base.h
  source/module_elecstate/module_pot/pot_local.cpp
  source/module_elecstate/module_pot/pot_local.h
  source/module_elecstate/module_pot/pot_local_paw.cpp
  source/module_elecstate/module_pot/pot_local_paw.h
  source/module_elecstate/module_pot/pot_surchem.hpp
  source/module_elecstate/module_pot/pot_xc.cpp
  source/module_elecstate/module_pot/pot_xc.h
  source/module_elecstate/module_pot/potential_new.cpp
  source/module_elecstate/module_pot/potential_new.h
  source/module_elecstate/module_pot/potential_types.cpp
  source/module_elecstate/test/CMakeLists.txt
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_elecstate/test/potential_new_test.cpp
  source/module_elecstate/test/potentials_base_test.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_nonlocal_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/veff_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/pulay_force_stress.h
  source/module_hamilt_lcao/module_tddft/td_velocity.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_cc.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces_scc.cpp
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func_har.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_forces.cpp
  source/module_io/input_conv.cpp
  source/module_io/td_current_io.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/write_elecstat_pot.cpp
  source/module_io/write_vxc_lip.hpp
  source/module_lr/potentials/pot_hxc_lrtd.cpp
  source/module_lr/potentials/pot_hxc_lrtd.h
  source/module_rdmft/rdmft_tools.cpp
  source/module_rdmft/rdmft_tools.h
Labels: The Absolute Zero

#6071 Fixing problem for running meta functionals with kinetic energy density mixed
  source/module_esolver/esolver_ks.cpp
  tests/integrate/218_NO_mixing_tau/INPUT
  tests/integrate/218_NO_mixing_tau/KPT
  tests/integrate/218_NO_mixing_tau/STRU
  tests/integrate/218_NO_mixing_tau/jd
  tests/integrate/218_NO_mixing_tau/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs, Refactor

#6069 Refactor: reduce the memory consumption of cal_gint_vlocal
  source/module_hamilt_lcao/module_gint/gint.h
  source/module_hamilt_lcao/module_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/gint_vl_cpu_interface.cpp
  source/module_hamilt_lcao/module_gint/temp_gint/gint_vl.cpp
  source/module_hamilt_lcao/module_gint/temp_gint/gint_vl_metagga.cpp
  source/module_hamilt_lcao/module_gint/temp_gint/gint_vl_metagga_nspin4.cpp
  source/module_hamilt_lcao/module_gint/temp_gint/gint_vl_nspin4.cpp
  source/module_hamilt_lcao/module_gint/temp_gint/phi_operator.cpp
  source/module_hamilt_lcao/module_gint/temp_gint/phi_operator.h
  source/module_hamilt_lcao/module_hcontainer/base_matrix.h
Labels: Refactor

#6073 Tests: remove mock of print func in md/esolver tests
  source/module_esolver/test/CMakeLists.txt
  source/module_esolver/test/esolver_dp_test.cpp
  source/module_md/test/CMakeLists.txt
  source/module_md/test/setcell.h
Labels: Refactor

#6074 Fix: modify warning output
  source/module_io/read_input_item_elec_stru.cpp
Labels: Refactor

#6076 Update ABACUS output formats, accept it after 3.10 version
  source/driver.cpp
  source/driver_run.cpp
  source/module_base/memory.cpp
  source/module_cell/module_neighbor/sltk_atom_arrange.cpp
  source/module_cell/module_neighbor/sltk_grid.cpp
  source/module_cell/print_cell.cpp
  source/module_cell/print_cell.h
  source/module_cell/read_atoms.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/elecstate_print.h
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_esolver/esolver_dp.cpp
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_lj.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/module_gint/cal_psir_ylm.cpp
  source/module_hamilt_pw/hamilt_ofdft/of_stress_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/stress_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_stress_pw.cpp
  source/module_io/berryphase.cpp
  source/module_io/output_log.cpp
  source/module_io/output_log.h
  source/module_io/print_info.cpp
  source/module_io/test/outputlog_test.cpp
  source/module_io/write_wfc_pw.cpp
  source/module_md/fire.cpp
  source/module_md/md_base.cpp
  source/module_md/md_func.cpp
  source/module_md/test/fire_test.cpp
  source/module_md/test/langevin_test.cpp
  source/module_md/test/md_func_test.cpp
  source/module_md/test/msst_test.cpp
  source/module_md/test/nhchain_test.cpp
  source/module_md/test/setcell.h
  source/module_md/test/verlet_test.cpp
  source/module_relax/relax_new/relax.cpp
  source/module_relax/relax_old/ions_move_basic.cpp
  tests/integrate/README.md
  tests/integrate/Single_job.sh
  tests/integrate/general_info
  tests/integrate/tools/catch_properties.sh
  tests/integrate/tools/run_check.sh
Labels: The Absolute Zero

#6082 Fix: Sign problem in DeePKS cal_pdm().
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_spre.cpp
  source/module_hamilt_lcao/module_hcontainer/atom_pair.cpp
  tests/deepks/603_NO_deepks_H2O_multik/result.ref
Labels: Bugs, Refactor
