Repository deepmodeling/abacus-develop, pull requests merged in 2025-01, with the labels that each got.

#5782 Feature: binary format of backup charge density
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_fp.cpp
  source/module_esolver/esolver_fp.h
  source/module_esolver/esolver_ks.cpp
  source/module_esolver/esolver_ks.h
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_of.cpp
  source/module_io/read_input_item_output.cpp
  source/module_io/test/read_input_ptest.cpp
  source/module_parameter/input_parameter.h
Labels: Refactor

#5791 Refactor: Remove some redundant variables and global dependence in DeePKS.
  source/Makefile.Objects
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/cal_descriptor.cpp
  source/module_hamilt_lcao/module_deepks/cal_gedm.cpp
  source/module_hamilt_lcao/module_deepks/cal_gvx.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/v_delta_precalc.cpp
Labels: The Absolute Zero, DeePKS

#5790 [Feature] Add col-major encapsulation for blas kernels and add some lacking kernels from blas
  source/module_base/blas_connector.cpp
  source/module_base/blas_connector.h
  source/module_hamilt_lcao/module_gint/mult_psi_dmr.cpp
Labels: Features Needed, Refactor

#5792 Feature: enable init_chg=file for metagga
  source/module_elecstate/module_charge/charge.h
  source/module_elecstate/module_charge/charge_init.cpp
  tests/integrate/101_PW_15_f_pseudopots/INPUT
  tests/integrate/101_PW_15_f_pseudopots/README
  tests/integrate/101_PW_15_f_pseudopots/STRU
  tests/integrate/101_PW_15_f_pseudopots/autotest-CHARGE-DENSITY.restart
  tests/integrate/101_PW_15_f_pseudopots/autotest-TAU-DENSITY.restart
  tests/integrate/101_PW_15_f_pseudopots/jd
  tests/integrate/101_PW_15_f_pseudopots/result.ref
Labels: Bugs, Features Needed, Refactor

#5783 Refactor:Remove update_tau_pos in ucell
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/bcast_cell.cpp
  source/module_cell/bcast_cell.h
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_para.cpp
  source/module_cell/test_pw/CMakeLists.txt
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_cell/update_cell.cpp
  source/module_cell/update_cell.h
  source/module_md/test/CMakeLists.txt
  source/module_relax/relax_new/test/CMakeLists.txt
  source/module_relax/relax_old/bfgs.cpp
  source/module_relax/relax_old/ions_move_basic.cpp
  source/module_relax/relax_old/ions_move_sd.cpp
  source/module_relax/relax_old/test/CMakeLists.txt
  source/module_relax/relax_old/test/for_test.h
  source/module_relax/relax_old/test/ions_move_basic_test.cpp
  source/module_relax/relax_old/test/ions_move_bfgs_test.cpp
  source/module_relax/relax_old/test/ions_move_cg_test.cpp
  source/module_relax/relax_old/test/ions_move_sd_test.cpp
Labels: The Absolute Zero

#5793 Refactor: Enable the support of odd number of electrions in DeepKS orbital
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
Labels: Bugs, DeePKS

#5798 Fix: instable nonlocal pp in uspp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.h
Labels: Bugs, Features Needed, Refactor

#5785 Restore deepks unit test in gamma-only case and make H_V_delta have full size of Hamiltonian in multi-k case
  source/module_basis/module_ao/ORB_read.cpp
  source/module_basis/module_nao/two_center_bundle.cpp
  source/module_cell/unitcell.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/test/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp
  source/module_hamilt_lcao/module_deepks/test/klist_1.cpp
  source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp
  source/module_hamilt_lcao/module_deepks/test/nnr.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
  tests/deepks/603_NO_deepks_H2O_multik/INPUT
  tests/deepks/603_NO_deepks_H2O_multik/STRU
  tests/deepks/603_NO_deepks_H2O_multik/result.ref
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/INPUT
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/KPT
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/STRU
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/result.ref
  tests/deepks/604_NO_deepks_ut_CH4_gamma/dphialpha_x_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/dphialpha_y_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/dphialpha_z_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/pdm_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/phialpha_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/dphialpha_x_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/dphialpha_y_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/dphialpha_z_ref.dat
  tests/deepks/604_NO_deepks_ut_H2O_multik/phialpha_ref.dat
  tests/deepks/CASES1
  tests/deepks/CMakeLists.txt
Labels: Compile & CICD & Docs & Dependencies, Refactor, DeePKS

#5801 Refactor: update logic of init_chg
  source/module_elecstate/module_charge/charge_init.cpp
Labels: Refactor

#5807 Fix some compile warnings about esolver
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_ks.h
Labels: Refactor

#5802 Refactor:remove cal_tau from ElecStateLCAO
  source/module_elecstate/elecstate_lcao.cpp
  source/module_elecstate/elecstate_lcao.h
  source/module_elecstate/elecstate_lcao_cal_tau.cpp
  source/module_elecstate/elecstate_lcao_cal_tau.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_rdmft/update_state_rdmft.cpp
Labels: The Absolute Zero

#5799 [Feature] Add some GPU kernels to blas_connector
  source/module_base/blas_connector.cpp
  source/module_base/test/CMakeLists.txt
  source/module_base/test/clebsch_gordan_coeff_test.cpp
  source/module_base/test/complexmatrix_test.cpp
  source/module_base/test/global_function_test.cpp
  source/module_base/test/inverse_matrix_test.cpp
  source/module_base/test/math_chebyshev_test.cpp
  source/module_base/test/math_ylmreal_test.cpp
  source/module_base/test/opt_CG_test.cpp
  source/module_base/test/opt_TN_test.cpp
  source/module_base/test/opt_test_tools.cpp
Labels: GPU & DCU & HPC

#5794 Refactor:Remove Ucell::update_pos_taud
  source/module_cell/atom_spec.h
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_para.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_cell/update_cell.cpp
  source/module_cell/update_cell.h
  source/module_md/md_base.cpp
  source/module_md/run_md.cpp
  source/module_relax/relax_new/relax.cpp
  source/module_relax/relax_new/test/relax_test.cpp
  source/module_relax/relax_new/test/relax_test.h
  source/module_relax/relax_new/test/support/result_ref.txt
Labels: The Absolute Zero

#5761 Refactor: refactor the constructors of Psi class
  source/module_elecstate/cal_dm.h
  source/module_elecstate/elecstate_pw.cpp
  source/module_elecstate/elecstate_pw_cal_tau.cpp
  source/module_elecstate/module_dm/cal_dm_psi.cpp
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_of.cpp
  source/module_esolver/esolver_of_tool.cpp
  source/module_hamilt_general/operator.cpp
  source/module_hamilt_general/operator.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/velocity_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/test/test_sto_tool.cpp
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_cg_float_test.cpp
  source/module_hsolver/test/diago_cg_real_test.cpp
  source/module_hsolver/test/diago_cg_test.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
  source/module_io/get_pchg_lcao.cpp
  source/module_io/test/write_wfc_nao_test.cpp
  source/module_io/unk_overlap_pw.cpp
  source/module_io/write_dos_lcao.cpp
  source/module_io/write_proj_band_lcao.cpp
  source/module_io/write_vxc_lip.hpp
  source/module_lr/AX/test/AX_test.cpp
  source/module_lr/dm_trans/test/dm_trans_test.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_lr/hamilt_casida.cpp
  source/module_lr/ri_benchmark/test/ri_benchmark_test.cpp
  source/module_lr/utils/lr_util.hpp
  source/module_lr/utils/test/lr_util_algorithms_test.cpp
  source/module_psi/psi.cpp
  source/module_psi/psi.h
  source/module_psi/test/psi_test.cpp
  source/module_ri/exx_lip.hpp
Labels: Refactor, The Absolute Zero

#5812 Refactor: Remove global dependence of descriptor, orbital_precalc, v_delta_precalc in DeePKS.
  source/Makefile.Objects
  source/module_esolver/esolver_ks.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_mpi.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/cal_descriptor.cpp
  source/module_hamilt_lcao/module_deepks/cal_gdmepsl.cpp
  source/module_hamilt_lcao/module_deepks/cal_gedm.cpp
  source/module_hamilt_lcao/module_deepks/cal_gvx.cpp
  source/module_hamilt_lcao/module_deepks/deepks_descriptor.cpp
  source/module_hamilt_lcao/module_deepks/deepks_descriptor.h
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
  source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp
  source/module_hamilt_lcao/module_deepks/v_delta_precalc.cpp
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmepsl_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmepsl_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmepsl_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmepsl_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmepsl_4_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmepsl_5_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmx_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmx_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmx_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmx_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmx_4_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmy_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmy_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmy_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmy_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmy_4_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmz_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmz_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmz_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmz_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gdmz_4_ref.dat
Labels: Refactor, The Absolute Zero, DeePKS

#5821 Fix: Fix the Segmentation fault caused by zero atom case with LCAO basis.
  source/module_cell/module_neighbor/sltk_grid.cpp
  tests/integrate/223_NO_zero_atom/INPUT
  tests/integrate/223_NO_zero_atom/KPT
  tests/integrate/223_NO_zero_atom/STRU
  tests/integrate/223_NO_zero_atom/jd
  tests/integrate/223_NO_zero_atom/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs, Input&Output, Refactor

#5820 Refactor: modify decimal digit of wfc to 8
  examples/hefei-namd/README
  examples/wfc/README
  source/module_io/write_wfc_nao.cpp
Labels: Input&Output, Refactor

#5817 Fix: add const in module_lr
  source/module_lr/AX/AX.h
  source/module_lr/AX/AX_parallel.cpp
  source/module_lr/AX/AX_serial.cpp
  source/module_lr/dm_trans/dm_trans.h
  source/module_lr/dm_trans/dm_trans_parallel.cpp
  source/module_lr/dm_trans/dm_trans_serial.cpp
  source/module_lr/hamilt_casida.h
  source/module_lr/hamilt_ulr.hpp
Labels: EXX and lr-TDDFT

#5549 feature: parallel solve subspace diagonalization in dav_subspace
  docs/advanced/input_files/input-main.md
  python/pyabacus/src/hsolver/CMakeLists.txt
  python/pyabacus/src/hsolver/py_diago_dav_subspace.hpp
  python/pyabacus/src/hsolver/py_hsolver.cpp
  python/pyabacus/src/pyabacus/hsolver/_hsolver.py
  source/Makefile.Objects
  source/module_base/blacs_connector.h
  source/module_base/scalapack_connector.h
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diag_hs_para.cpp
  source/module_hsolver/diag_hs_para.h
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_dav_subspace.h
  source/module_hsolver/diago_pxxxgvx.cpp
  source/module_hsolver/diago_pxxxgvx.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/test_diago_hs_para.cpp
  source/module_hsolver/test/test_hsolver_pw.cpp
  source/module_hsolver/test/test_hsolver_sdft.cpp
  source/module_io/read_input_item_system.cpp
  source/module_lr/hsolver_lrtd.hpp
  source/module_parameter/input_parameter.h
  tests/integrate/102_PW_DS_davsubspace_sca/INPUT
  tests/integrate/102_PW_DS_davsubspace_sca/KPT
  tests/integrate/102_PW_DS_davsubspace_sca/STRU
  tests/integrate/102_PW_DS_davsubspace_sca/jd
  tests/integrate/102_PW_DS_davsubspace_sca/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Refactor, Diago

#5825 [Fix] Fix the issue that single precision caculation is not runable on CUDA version
  source/module_basis/module_pw/module_fft/fft_bundle.cpp
Labels: GPU & DCU & HPC, Refactor

#5823 Tests: add checks for opening data files by hsolver tests
  source/module_hsolver/test/diago_bpcg_test.cpp
  source/module_hsolver/test/diago_cg_float_test.cpp
  source/module_hsolver/test/diago_cg_real_test.cpp
  source/module_hsolver/test/diago_cg_test.cpp
  source/module_hsolver/test/diago_david_float_test.cpp
  source/module_hsolver/test/diago_david_real_test.cpp
  source/module_hsolver/test/diago_david_test.cpp
Labels: Refactor

#5826 Fix: support negative value in parse_expression
  source/module_io/input_conv.h
Labels: Bugs, Input&Output, Refactor

#5824 Refactor: Remove global dependence in force/stress calculation in DeePKS.
  source/Makefile.Objects
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/cal_gvx.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_fpre.h
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.h
  source/module_hamilt_lcao/module_deepks/deepks_spre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_spre.h
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdpre.h
  source/module_hamilt_lcao/module_deepks/test/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
  source/module_hamilt_lcao/module_deepks/test/main_deepks.cpp
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvepsl_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvepsl_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvepsl_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvepsl_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvepsl_4_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvepsl_5_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvx_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvx_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvx_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvx_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvx_4_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvy_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvy_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvy_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvy_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvy_4_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvz_0_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvz_1_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvz_2_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvz_3_ref.dat
  tests/deepks/604_NO_deepks_ut_CH4_gamma/gvz_4_ref.dat
Labels: Refactor, The Absolute Zero, DeePKS

#5831 Refactor: output true external_stress in dp/lj
  source/module_esolver/esolver_dp.cpp
  source/module_esolver/esolver_gets.cpp
  source/module_esolver/esolver_lj.cpp
Labels: Input&Output, Features Needed, Refactor

#5810 Refactor:remove MPI part funcs of ucell
  source/driver_run.cpp
  source/module_basis/module_ao/test/ORB_unittest.cpp
  source/module_basis/module_ao/test/ORB_unittest.h
  source/module_cell/bcast_cell.cpp
  source/module_cell/bcast_cell.h
  source/module_cell/module_neighbor/test/prepare_unitcell.h
  source/module_cell/read_atoms.cpp
  source/module_cell/test/prepare_unitcell.h
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_para.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_cell/update_cell.cpp
  source/module_elecstate/module_dm/test/prepare_unitcell.h
  source/module_elecstate/read_pseudo.cpp
  source/module_elecstate/test/prepare_unitcell.h
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_init_basis.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test_prep.cpp
  source/module_hamilt_lcao/module_deltaspin/test/prepare_unitcell.h
  source/module_hamilt_lcao/module_hcontainer/test/prepare_unitcell.h
  source/module_io/json_output/init_info.cpp
  source/module_io/json_output/test/para_json_test.cpp
  source/module_io/test/prepare_unitcell.h
  source/module_io/test/to_qo_test.cpp
  source/module_io/test_serial/prepare_unitcell.h
  source/module_io/to_qo_kernel.cpp
  source/module_lr/esolver_lrtd_lcao.cpp
  source/module_psi/psi_initializer_nao.cpp
  source/module_psi/test/psi_initializer_unit_test.cpp
  source/module_relax/relax_old/test/for_test.h
Labels: The Absolute Zero

#5797 Remove TensorMap after cg call in HSolverPW
  source/module_hsolver/hsolver_pw.cpp
Labels: Diago

#5829 Fix: dmin is replaced by dmax
  source/module_hsolver/diago_iter_assist.cpp
Labels: Refactor, Diago

#5828 Refactor:Remove the read_atom_species and add read_lattice_constant
  source/Makefile.Objects
  source/module_cell/CMakeLists.txt
  source/module_cell/module_neighbor/test/prepare_unitcell.h
  source/module_cell/read_atom_species.cpp
  source/module_cell/read_atoms.cpp
  source/module_cell/read_stru.cpp
  source/module_cell/read_stru.h
  source/module_cell/test/CMakeLists.txt
  source/module_cell/test/prepare_unitcell.h
  source/module_cell/test/support/mock_unitcell.cpp
  source/module_cell/test/unitcell_test.cpp
  source/module_cell/test/unitcell_test_setupcell.cpp
  source/module_cell/test_pw/CMakeLists.txt
  source/module_cell/test_pw/unitcell_test_pw.cpp
  source/module_cell/unitcell.cpp
  source/module_cell/unitcell.h
  source/module_cell/update_cell.cpp
  source/module_elecstate/module_dm/test/prepare_unitcell.h
  source/module_elecstate/test/prepare_unitcell.h
  source/module_esolver/test/esolver_dp_test.cpp
  source/module_esolver/test/for_test.h
  source/module_hamilt_lcao/module_deepks/test/CMakeLists.txt
  source/module_hamilt_lcao/module_deltaspin/test/prepare_unitcell.h
  source/module_hamilt_lcao/module_hcontainer/test/prepare_unitcell.h
  source/module_io/json_output/init_info.cpp
  source/module_io/json_output/test/para_json_test.cpp
  source/module_io/test/prepare_unitcell.h
  source/module_io/test/to_qo_test.cpp
  source/module_io/test_serial/prepare_unitcell.h
  source/module_io/to_qo_kernel.cpp
  source/module_md/test/CMakeLists.txt
  source/module_md/test/setcell.h
  source/module_psi/test/psi_initializer_unit_test.cpp
  source/module_relax/relax_old/test/for_test.h
Labels: The Absolute Zero

#5839 fix: memory leak when precision=single
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp
  source/module_io/read_input_item_system.cpp
  source/module_psi/psi_init.cpp
  source/module_psi/psi_init.h
Labels: Bugs, Refactor

#5835 Refactor: Remove the global dependence of all remained functions in DeePKS.
  source/Makefile.Objects
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/module_deepks/CMakeLists.txt
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_torch.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/cal_gedm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.h
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbpre.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.cpp
  source/module_hamilt_lcao/module_deepks/deepks_pdm.h
  source/module_hamilt_lcao/module_deepks/deepks_phialpha.cpp
  source/module_hamilt_lcao/module_deepks/deepks_phialpha.h
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.cpp
  source/module_hamilt_lcao/module_deepks/deepks_vdelta.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/Makefile.Objects
Labels: The Absolute Zero, DeePKS

#5827 Fix: use gemm instead of einsum in BPCG
  source/module_hsolver/diago_bpcg.cpp
  source/module_hsolver/diago_bpcg.h
  source/module_hsolver/hsolver_pw.cpp
  source/module_hsolver/test/diago_bpcg_test.cpp
  tests/integrate/102_PW_BPCG/result.ref
Labels: Refactor, Diago

#5844 Refactor: Remove LCAO_Deepks from GlobalC.
  source/module_elecstate/elecstate.h
  source/module_elecstate/elecstate_energy.cpp
  source/module_elecstate/elecstate_energy_terms.cpp
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/fp_energy.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_lcao.h
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.h
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_allocate.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/LCAO_domain.h
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_io.h
  source/module_hamilt_lcao/module_deepks/deepks_force.cpp
  source/module_hamilt_lcao/module_deepks/deepks_force.h
  source/module_hamilt_lcao/module_deepks/deepks_orbital.cpp
  source/module_hamilt_lcao/module_deepks/deepks_orbital.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.h
Labels: Refactor, The Absolute Zero, DeePKS

#5845 Perf: optimize the stream strategy in module_gint
  source/module_hamilt_lcao/module_gint/gint_force_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_rho_gpu.cu
  source/module_hamilt_lcao/module_gint/gint_vl_gpu.cu
Labels: GPU & DCU & HPC, Refactor

#5846 Refactor: remove GlobalC::Pkpoint
  source/module_cell/klist.cpp
  source/module_cell/klist.h
  source/module_cell/parallel_kpoints.cpp
  source/module_cell/parallel_kpoints.h
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/global.h
  source/module_io/dos_nao.cpp
  source/module_io/dos_nao.h
  source/module_io/nscf_band.cpp
  source/module_io/nscf_band.h
  source/module_io/nscf_fermi_surf.cpp
  source/module_io/nscf_fermi_surf.h
  source/module_io/numerical_basis.cpp
  source/module_io/test/write_istate_info_test.cpp
  source/module_io/test_serial/nscf_band_test.cpp
  source/module_io/to_wannier90_lcao_in_pw.cpp
  source/module_io/write_istate_info.cpp
  source/module_io/write_istate_info.h
  source/module_io/write_wfc_pw.cpp
  source/module_io/write_wfc_r.cpp
Labels: The Absolute Zero

#5848 Fix a bug and a magic number in module_exx_symmetry
  source/module_ri/module_exx_symmetry/irreducible_sector.h
  source/module_ri/module_exx_symmetry/irreducible_sector_bvk.cpp
  source/module_ri/module_exx_symmetry/symmetry_rotation.cpp
Labels: Bugs, Symmetry, Refactor

#5847 Fix: wrong band output when kpar > 1
  source/module_cell/klist.cpp
  source/module_cell/klist.h
  source/module_cell/parallel_kpoints.h
  source/module_elecstate/elecstate_print.cpp
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_elecstate/module_dm/test/test_cal_dm_R.cpp
  source/module_elecstate/module_dm/test/test_dm_R_init.cpp
  source/module_elecstate/module_dm/test/test_dm_constructor.cpp
  source/module_elecstate/module_dm/test/test_dm_io.cpp
  source/module_elecstate/test/elecstate_base_test.cpp
  source/module_elecstate/test/elecstate_energy_test.cpp
  source/module_elecstate/test/elecstate_print_test.cpp
  source/module_elecstate/test/elecstate_pw_test.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hamilt_lcao/module_deltaspin/test/lambda_loop_helper_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/spin_constrain_test.cpp
  source/module_hamilt_lcao/module_deltaspin/test/template_helpers_test.cpp
  source/module_hamilt_pw/hamilt_pwdft/elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_wf.cpp
  source/module_hamilt_pw/hamilt_stodft/test/test_hamilt_sto.cpp
  source/module_hsolver/test/hsolver_supplementary_mock.h
  source/module_io/read_wfc_pw.cpp
  source/module_io/read_wfc_pw.h
  source/module_io/read_wfc_to_rho.cpp
  source/module_io/read_wfc_to_rho.h
  source/module_io/test/read_wfc_pw_test.cpp
  source/module_io/test/read_wfc_to_rho_test.cpp
  source/module_io/test_serial/nscf_band_test.cpp
  source/module_io/to_wannier90_lcao_in_pw.cpp
  source/module_io/write_wfc_pw.cpp
  source/module_psi/psi_init.cpp
  source/module_psi/psi_init.h
  source/module_psi/psi_initializer.cpp
  source/module_psi/psi_initializer.h
  source/module_psi/psi_initializer_atomic.cpp
  source/module_psi/psi_initializer_atomic.h
  source/module_psi/psi_initializer_atomic_random.cpp
  source/module_psi/psi_initializer_atomic_random.h
  source/module_psi/psi_initializer_file.cpp
  source/module_psi/psi_initializer_file.h
  source/module_psi/psi_initializer_nao.cpp
  source/module_psi/psi_initializer_nao.h
  source/module_psi/psi_initializer_nao_random.cpp
  source/module_psi/psi_initializer_nao_random.h
  source/module_psi/psi_initializer_random.cpp
  source/module_psi/psi_initializer_random.h
  source/module_psi/test/psi_initializer_unit_test.cpp
  tests/integrate/101_PW_upf201_uspp_Fe/result.ref
  tests/integrate/127_PW_15_PK_AF_wfcinit/INPUT
  tests/integrate/127_PW_15_PK_AF_wfcinit/KPT
  tests/integrate/127_PW_15_PK_AF_wfcinit/OUT.autotest/WAVEFUNC1.dat
  tests/integrate/127_PW_15_PK_AF_wfcinit/OUT.autotest/WAVEFUNC2.dat
  tests/integrate/127_PW_15_PK_AF_wfcinit/OUT.autotest/WAVEFUNC3.dat
  tests/integrate/127_PW_15_PK_AF_wfcinit/OUT.autotest/WAVEFUNC4.dat
  tests/integrate/127_PW_15_PK_AF_wfcinit/OUT.autotest/istate.info
  tests/integrate/127_PW_15_PK_AF_wfcinit/README
  tests/integrate/127_PW_15_PK_AF_wfcinit/STRU
  tests/integrate/127_PW_15_PK_AF_wfcinit/result.ref
  tests/integrate/CASES_CPU.txt
Labels: Bugs, Refactor, The Absolute Zero

#5849 Feature: Add planewave parallization support for BPCG method
  docs/advanced/scf/hsolver.md
  source/module_hsolver/diago_bpcg.cpp
  source/module_hsolver/diago_bpcg.h
  source/module_hsolver/kernels/math_kernel_op.cpp
  tests/integrate/102_PW_BPCG/result.ref
  tests/integrate/Autotest.sh
Labels: Refactor, Diago

#5853 Fix: modify orb info manually
  source/module_basis/module_nao/atomic_radials.cpp
  tests/PP_ORB/Ti_gga_8au_100Ry_4s2p2d1f.orb
  tests/integrate/284_NO_KP_symmetry/result.ref
Labels: Bugs, Refactor

#5852 Refactor: generalize the transition density matrix in module_lr
  source/module_lr/ao_to_mo_transformer/ao_to_mo.h
  source/module_lr/ao_to_mo_transformer/ao_to_mo_parallel.cpp
  source/module_lr/ao_to_mo_transformer/ao_to_mo_serial.cpp
  source/module_lr/dm_trans/dm_trans.h
  source/module_lr/dm_trans/dm_trans_parallel.cpp
  source/module_lr/dm_trans/dm_trans_serial.cpp
  source/module_lr/dm_trans/test/dm_trans_test.cpp
  source/module_lr/hamilt_casida.h
  source/module_lr/hamilt_ulr.hpp
  source/module_lr/lr_spectrum.cpp
Labels: EXX and lr-TDDFT, Refactor

#5857 Update pdm before outputting DeePKS labels
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_gamma.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/FORCE_k.cpp
  source/module_hamilt_lcao/hamilt_lcaodft/hamilt_lcao.h
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/deepks_lcao.cpp
  source/module_hamilt_lcao/module_deepks/LCAO_deepks.h
  source/module_hamilt_lcao/module_deepks/LCAO_deepks_interface.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.cpp
  source/module_hamilt_lcao/module_deepks/deepks_basic.h
  source/module_hamilt_lcao/module_deepks/test/LCAO_deepks_test.cpp
  tests/deepks/602_NO_deepks_d_H2O_md_lda2pbe/result.ref
  tests/deepks/603_NO_deepks_SiO2_bandgap_multik/result.ref
Labels: Refactor, DeePKS

#5866 Fix the precision loss in `Tensor` output stream operator `<<`
  source/module_base/module_container/ATen/core/tensor.cpp
Labels: Refactor

#5864 Fix:modify cheaktau type and add unittest
  source/module_cell/read_stru.cpp
  source/module_cell/read_stru.h
  source/module_cell/test/unitcell_test.cpp
Labels: Bugs, Input&Output, Refactor

#5863 Refactor: refactor `npol`, constructors and `int *ngk` of Psi class
  source/module_elecstate/cal_dm.h
  source/module_elecstate/elecstate_pw.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/esolver_sdft_pw.cpp
  source/module_esolver/lcao_before_scf.cpp
  source/module_esolver/lcao_others.cpp
  source/module_hamilt_general/operator.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hamilt_lcao/module_dftu/dftu_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/onsite_projector.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/velocity_pw.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_wf.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_wf.h
  source/module_hsolver/hsolver_lcao.cpp
  source/module_hsolver/test/diago_mock.h
  source/module_io/test/read_wfc_to_rho_test.cpp
  source/module_io/to_wannier90_lcao_in_pw.cpp
  source/module_io/write_vxc_lip.hpp
  source/module_lr/ao_to_mo_transformer/test/ao_to_mo_test.cpp
  source/module_lr/dm_trans/test/dm_trans_test.cpp
  source/module_psi/psi.cpp
  source/module_psi/psi.h
  source/module_psi/psi_init.cpp
  source/module_psi/psi_init.h
  source/module_psi/psi_initializer_atomic_random.cpp
  source/module_psi/psi_initializer_nao_random.cpp
  source/module_psi/test/psi_initializer_unit_test.cpp
  source/module_psi/test/psi_test.cpp
  source/module_ri/exx_lip.hpp
Labels: Refactor, The Absolute Zero

#5870 Feature: add para_gemm to do parallel matrix multiply
  python/pyabacus/CONTRIBUTING.md
  python/pyabacus/src/ModuleBase/CMakeLists.txt
  python/pyabacus/src/ModuleNAO/CMakeLists.txt
  python/pyabacus/src/hsolver/CMakeLists.txt
  python/pyabacus/src/hsolver/py_hsolver.cpp
  source/CMakeLists.txt
  source/Makefile.Objects
  source/module_base/CMakeLists.txt
  source/module_base/blas_connector.cpp
  source/module_base/kernels/cuda/math_kernel_op.cu
  source/module_base/kernels/math_kernel_op.cpp
  source/module_base/kernels/math_kernel_op.h
  source/module_base/kernels/rocm/math_kernel_op.hip.cu
  source/module_base/kernels/test/CMakeLists.txt
  source/module_base/kernels/test/math_kernel_test.cpp
  source/module_base/para_gemm.cpp
  source/module_base/para_gemm.h
  source/module_base/parallel_device.cpp
  source/module_base/parallel_device.h
  source/module_base/test_parallel/CMakeLists.txt
  source/module_base/test_parallel/test_para_gemm.cpp
  source/module_elecstate/elecstate_pw.h
  source/module_esolver/esolver_ks_lcaopw.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_esolver/pw_others.cpp
  source/module_hamilt_lcao/module_deltaspin/cal_mw_from_lambda.cpp
  source/module_hamilt_pw/hamilt_pwdft/forces.h
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.cpp
  source/module_hamilt_pw/hamilt_pwdft/fs_nonlocal_tools.h
  source/module_hamilt_pw/hamilt_pwdft/hamilt_pw.h
  source/module_hamilt_pw/hamilt_pwdft/nonlocal_maths.hpp
  source/module_hamilt_pw/hamilt_pwdft/onsite_proj_tools.h
  source/module_hamilt_pw/hamilt_pwdft/onsite_projector.cpp
  source/module_hamilt_pw/hamilt_pwdft/onsite_projector.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/meta_pw.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/nonlocal_pw.h
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/onsite_proj_pw.h
  source/module_hamilt_pw/hamilt_pwdft/stress_func.h
  source/module_hamilt_pw/hamilt_stodft/sto_che.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_che.h
  source/module_hamilt_pw/hamilt_stodft/sto_iter.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_iter.h
  source/module_hsolver/CMakeLists.txt
  source/module_hsolver/diago_bpcg.cpp
  source/module_hsolver/diago_bpcg.h
  source/module_hsolver/diago_cg.cpp
  source/module_hsolver/diago_cg.h
  source/module_hsolver/diago_dav_subspace.cpp
  source/module_hsolver/diago_david.cpp
  source/module_hsolver/diago_iter_assist.cpp
  source/module_hsolver/hsolver_pw_sdft.cpp
  source/module_hsolver/kernels/test/CMakeLists.txt
  source/module_hsolver/kernels/test/math_dngvd_test.cpp
  source/module_hsolver/kernels/test/perf_math_kernel.cpp
  source/module_hsolver/test/CMakeLists.txt
  source/module_hsolver/test/diago_bpcg_test.cpp
  source/module_lr/operator_casida/operator_lr_diag.h
Labels: Refactor, The Absolute Zero, Diago

#5773 RT-TDDFT GPU Acceleration: RT-TD now fully support GPU computation
  source/Makefile.Objects
  source/module_base/lapack_connector.h
  source/module_base/module_container/ATen/kernels/cuda/lapack.cu
  source/module_base/module_container/ATen/kernels/lapack.cpp
  source/module_base/module_container/ATen/kernels/lapack.h
  source/module_base/module_container/base/third_party/cusolver.h
  source/module_base/module_container/base/third_party/lapack.h
  source/module_elecstate/potentials/H_TDDFT_pw.cpp
  source/module_esolver/esolver.cpp
  source/module_esolver/esolver_ks_lcao_tddft.cpp
  source/module_esolver/esolver_ks_lcao_tddft.h
  source/module_hamilt_lcao/module_tddft/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/band_energy.cpp
  source/module_hamilt_lcao/module_tddft/band_energy.h
  source/module_hamilt_lcao/module_tddft/bandenergy.cpp
  source/module_hamilt_lcao/module_tddft/bandenergy.h
  source/module_hamilt_lcao/module_tddft/evolve_elec.cpp
  source/module_hamilt_lcao/module_tddft/evolve_elec.h
  source/module_hamilt_lcao/module_tddft/evolve_psi.cpp
  source/module_hamilt_lcao/module_tddft/evolve_psi.h
  source/module_hamilt_lcao/module_tddft/middle_hamilt.cpp
  source/module_hamilt_lcao/module_tddft/middle_hamilt.h
  source/module_hamilt_lcao/module_tddft/norm_psi.cpp
  source/module_hamilt_lcao/module_tddft/norm_psi.h
  source/module_hamilt_lcao/module_tddft/propagator.cpp
  source/module_hamilt_lcao/module_tddft/propagator.h
  source/module_hamilt_lcao/module_tddft/propagator_cn2.cpp
  source/module_hamilt_lcao/module_tddft/propagator_etrs.cpp
  source/module_hamilt_lcao/module_tddft/propagator_taylor.cpp
  source/module_hamilt_lcao/module_tddft/test/CMakeLists.txt
  source/module_hamilt_lcao/module_tddft/test/band_energy_test.cpp
  source/module_hamilt_lcao/module_tddft/test/middle_hamilt_test.cpp
  source/module_hamilt_lcao/module_tddft/test/norm_psi_test.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test1.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test2.cpp
  source/module_hamilt_lcao/module_tddft/test/propagator_test3.cpp
  source/module_hamilt_lcao/module_tddft/test/upsi_test1.cpp
  source/module_hamilt_lcao/module_tddft/test/upsi_test2.cpp
  source/module_hamilt_lcao/module_tddft/test/upsi_test3.cpp
  source/module_hamilt_lcao/module_tddft/upsi.cpp
  source/module_hamilt_lcao/module_tddft/upsi.h
  source/module_hsolver/diago_cusolver.cpp
  source/module_io/input_conv.cpp
  source/module_io/read_input_item_tddft.cpp
  source/module_io/test/for_testing_input_conv.h
  source/module_io/test/read_input_ptest.cpp
  source/module_parameter/input_parameter.h
Labels: GPU & DCU & HPC, Features Needed

#5877 Fix: Fixed a bug in RT-TDDFT where the electric field was not applied starting from the restart step
  source/module_elecstate/potentials/H_TDDFT_pw.cpp
  source/module_elecstate/potentials/H_TDDFT_pw.h
  source/module_io/read_set_globalv.cpp
Labels: Features Needed, Refactor
