Repository deepmodeling/abacus-develop, pull requests merged in 2025-05, with the labels that each got.

#6179 Update integrate tests to reduce running time, change improper output style and files
  source/module_hamilt_general/module_surchem/surchem.cpp
  source/module_hamilt_pw/hamilt_pwdft/elecond.cpp
  source/module_hamilt_pw/hamilt_stodft/sto_elecond.cpp
  source/module_hsolver/diago_elpa.cpp
  tests/PP_ORB/C.LDA.UPF
  tests/PP_ORB/C_SG15_PBE.orb
  tests/PP_ORB/C_lda_8.0au_100Ry_2s2p1d.orb
  tests/PP_ORB/Cs_gga_10au_100Ry_4s2p1d.orb
  tests/PP_ORB/Fe_gga_6au_100Ry_2s1p1d.orb
  tests/PP_ORB/H.LDA.UPF
  tests/PP_ORB/H_SG15_PBE.orb
  tests/PP_ORB/H_gga_8au_100Ry_1s.orb
  tests/PP_ORB/H_lda_8.0au_100Ry_2s1p.orb
  tests/PP_ORB/I_gga_7au_100Ry_2s2p2d1f.orb
  tests/PP_ORB/O.LDA.UPF
  tests/PP_ORB/O_lda_8.0au_100Ry_2s2p1d.orb
  tests/PP_ORB/Pb_gga_7au_100Ry_2s2p2d1f.orb
  tests/integrate/184_PW_BNDKPAR_SDFT_ALL/INPUT
  tests/integrate/184_PW_BNDKPAR_SDFT_ALL/result.ref
  tests/integrate/184_PW_BNDKPAR_SDFT_MALL/INPUT
  tests/integrate/184_PW_BNDKPAR_SDFT_MALL/KPT
  tests/integrate/184_PW_BNDKPAR_SDFT_MALL/result.ref
  tests/integrate/186_PW_SDOS_MALL/INPUT
  tests/integrate/186_PW_SDOS_MALL/KPT
  tests/integrate/186_PW_SDOS_MALL/result.ref
  tests/integrate/186_PW_SKG_ALL/INPUT
  tests/integrate/186_PW_SKG_ALL/refOnsager.txt
  tests/integrate/186_PW_SKG_ALL/result.ref
  tests/integrate/204_NO_KP_AFM/INPUT
  tests/integrate/204_NO_KP_AFM/KPT
  tests/integrate/204_NO_KP_AFM/STRU
  tests/integrate/204_NO_KP_AFM/mulliken.txt.ref
  tests/integrate/204_NO_KP_AFM/result.ref
  tests/integrate/204_NO_KP_FM/INPUT
  tests/integrate/204_NO_KP_FM/KPT
  tests/integrate/204_NO_KP_FM/STRU
  tests/integrate/204_NO_KP_FM/result.ref
  tests/integrate/260_NO_DJ_PK_PU_AFM_URAMPING/INPUT
  tests/integrate/260_NO_DJ_PK_PU_AFM_URAMPING/STRU
  tests/integrate/260_NO_DJ_PK_PU_AFM_URAMPING/result.ref
  tests/integrate/260_NO_DJ_PK_PU_S1/INPUT
  tests/integrate/260_NO_DJ_PK_PU_S1/STRU
  tests/integrate/260_NO_DJ_PK_PU_S1/result.ref
  tests/integrate/315_NO_sol_H2O/INPUT
  tests/integrate/315_NO_sol_H2O/STRU
  tests/integrate/315_NO_sol_H2O/result.ref
  tests/integrate/tools/CompareFile.py
  tests/integrate/tools/catch_properties.sh
Labels: The Absolute Zero

#6181 Feature: multi-k case support for out_dm=1
  docs/advanced/input_files/input-main.md
  source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/op_exx_lcao.hpp
  source/module_io/io_dmk.cpp
  source/module_io/read_input_item_output.cpp
  source/module_io/test/io_dmk_test.cpp
  source/module_io/test/support/SPIN1_K1_DM
  source/module_io/test_serial/read_input_item_test.cpp
Labels: Input&Output, The Absolute Zero, DeePKS, Unit Tests/Integreate Tests

#6183 [Test] Now integrated test will run after other tests
  .github/workflows/test.yml
  CMakeLists.txt
Labels: Refactor, Unit Tests/Integreate Tests

#6187 Perf: add ccache support to cuda compiler
  CMakeLists.txt
Labels: Compile & CICD & Docs & Dependencies

#6197 [Test] Separate unit test for module_base as an example
  .github/workflows/test.yml
  source/module_base/test/CMakeLists.txt
Labels: The Absolute Zero, Unit Tests/Integreate Tests

#6209 Update version.h (v3.9.0.5)
  source/version.h
Labels: Refactor

#6208 Fix: correct the names of ut generated temp files in std::remove func
  source/module_io/test/to_qo_test.cpp
Labels: Refactor, Unit Tests/Integreate Tests

#6215 Fix: Fix minor `INPUT` parameter abuse in `get_wf` CI/CD test
  tests/02_NAO_Gamma/013_NO_GO_get_wf/INPUT
  tests/02_NAO_Gamma/013_NO_GO_get_wf/result.ref
Labels: Refactor, Unit Tests/Integreate Tests

#6232 [Test] Make tests in Module_Psi, Module_MD and Module_RI indenpendent
  .github/workflows/test.yml
  source/module_md/test/CMakeLists.txt
  source/module_psi/test/CMakeLists.txt
  source/module_ri/module_exx_symmetry/test/CMakeLists.txt
  source/module_ri/test/CMakeLists.txt
Labels: The Absolute Zero, Unit Tests/Integreate Tests

#6231 [Test] Add tests in subdirectories to its module
  source/module_base/grid/test/CMakeLists.txt
  source/module_base/kernels/test/CMakeLists.txt
  source/module_base/libm/test/CMakeLists.txt
  source/module_base/module_container/test/CMakeLists.txt
  source/module_base/module_device/test/CMakeLists.txt
  source/module_base/module_mixing/test/CMakeLists.txt
  source/module_cell/module_neighbor/test/CMakeLists.txt
  source/module_cell/module_symmetry/test/CMakeLists.txt
  source/module_hsolver/kernels/test/CMakeLists.txt
  source/module_io/json_output/test/CMakeLists.txt
  source/module_io/test_serial/CMakeLists.txt
Labels: The Absolute Zero, Unit Tests/Integreate Tests

#6235 fix a bug, when out_chg becomes 2, the read in function fails
  source/module_io/read_input_item_output.cpp
  tests/03_NAO_multik/05_NO_KP_DJ_OC2/INPUT
  tests/03_NAO_multik/05_NO_KP_DJ_OC2/KPT
  tests/03_NAO_multik/05_NO_KP_DJ_OC2/README
  tests/03_NAO_multik/05_NO_KP_DJ_OC2/STRU
  tests/03_NAO_multik/05_NO_KP_DJ_OC2/result.ref
  tests/03_NAO_multik/CASES_CPU.txt
Labels: Input&Output, Refactor

#6156 Reactor FFT format and add RAII for resource handler
  CMakeLists.txt
  source/module_basis/module_pw/module_fft/fft_base.h
  source/module_basis/module_pw/module_fft/fft_bundle.cpp
  source/module_basis/module_pw/module_fft/fft_bundle.h
  source/module_basis/module_pw/module_fft/fft_dsp.cpp
  source/module_basis/module_pw/module_fft/fft_dsp.h
  source/module_basis/module_pw/pw_basis_k.h
  source/module_basis/module_pw/pw_transform_k_dsp.cpp
  source/module_hamilt_pw/hamilt_pwdft/operator_pw/veff_pw.cpp
Labels: Refactor

#6237 Update out_dm and out_dm1 parameters and related documents
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_ks_lcao.cpp
  source/module_io/io_dmk.cpp
  source/module_io/io_dmk.h
  source/module_io/test/io_dmk_test.cpp
  source/module_io/test/support/dms1_nao.txt
  source/module_io/test/support/dms1k1_nao.txt
  source/module_io/write_dmr.cpp
  tests/02_NAO_Gamma/018_NO_GO_ODM/INPUT
  tests/02_NAO_Gamma/018_NO_GO_ODM/KPT
  tests/02_NAO_Gamma/018_NO_GO_ODM/README
  tests/02_NAO_Gamma/018_NO_GO_ODM/STRU
  tests/02_NAO_Gamma/018_NO_GO_ODM/dms1_nao.txt.ref
  tests/02_NAO_Gamma/018_NO_GO_ODM/result.ref
  tests/02_NAO_Gamma/CASES_CPU.txt
  tests/03_NAO_multik/01_NO_KP_15f_ODM/INPUT
  tests/03_NAO_multik/01_NO_KP_15f_ODM/KPT
  tests/03_NAO_multik/01_NO_KP_15f_ODM/README
  tests/03_NAO_multik/01_NO_KP_15f_ODM/STRU
  tests/03_NAO_multik/01_NO_KP_15f_ODM/dmrs1_nao.csr.ref
  tests/03_NAO_multik/01_NO_KP_15f_ODM/refElecStaticPot.cube
  tests/03_NAO_multik/01_NO_KP_15f_ODM/result.ref
  tests/03_NAO_multik/04_NO_KP_GTH/INPUT
  tests/03_NAO_multik/04_NO_KP_GTH/result.ref
  tests/03_NAO_multik/44_NO_KP_MD_OW/INPUT
  tests/03_NAO_multik/CASES_CPU.txt
  tests/integrate/tools/catch_properties.sh
Labels: Input&Output, The Absolute Zero, Unit Tests/Integreate Tests

#6240 Update the file names controlled by the out_pot command
  docs/advanced/input_files/input-main.md
  source/module_esolver/esolver_fp.cpp
  tests/01_PW/087_PW_OP/pots1.cube.ref
  tests/01_PW/088_PW_OP_nscf/pots1.cube.ref
  tests/03_NAO_multik/01_NO_KP_15f_ODM/pot_es.cube.ref
  tests/03_NAO_multik/38_NO_OP3/INPUT
  tests/03_NAO_multik/38_NO_OP3/KPT
  tests/03_NAO_multik/38_NO_OP3/README
  tests/03_NAO_multik/38_NO_OP3/STRU
  tests/03_NAO_multik/38_NO_OP3/pots1.cube.ref
  tests/03_NAO_multik/38_NO_OP3/result.ref
  tests/03_NAO_multik/39_NO_OP_nscf/pots1.cube.ref
  tests/03_NAO_multik/CASES_CPU.txt
  tests/integrate/tools/catch_properties.sh
Labels: Input&Output, Refactor, The Absolute Zero

#6242 Feature: Support outputting partial charge and wave functions under PW basis when `kpar > 1`
  docs/advanced/input_files/input-main.md
  source/module_elecstate/module_charge/symmetry_rho.cpp
  source/module_esolver/esolver_ks_pw.cpp
  source/module_hamilt_pw/hamilt_pwdft/parallel_grid.cpp
  source/module_hamilt_pw/hamilt_pwdft/parallel_grid.h
  source/module_io/cal_ldos.cpp
  source/module_io/cube_io.h
  source/module_io/get_pchg_pw.h
  source/module_io/get_wf_pw.h
  source/module_io/write_cube.cpp
  tests/01_PW/113_PW_get_pchg_kpar/INPUT
  tests/01_PW/113_PW_get_pchg_kpar/KPT
  tests/01_PW/113_PW_get_pchg_kpar/README
  tests/01_PW/113_PW_get_pchg_kpar/STRU
  tests/01_PW/113_PW_get_pchg_kpar/result.ref
  tests/01_PW/114_PW_get_pchg_sepk/INPUT
  tests/01_PW/114_PW_get_pchg_sepk/KPT
  tests/01_PW/114_PW_get_pchg_sepk/README
  tests/01_PW/114_PW_get_pchg_sepk/STRU
  tests/01_PW/114_PW_get_pchg_sepk/result.ref
  tests/01_PW/115_PW_get_wf_kpar/INPUT
  tests/01_PW/115_PW_get_wf_kpar/KPT
  tests/01_PW/115_PW_get_wf_kpar/README
  tests/01_PW/115_PW_get_wf_kpar/STRU
  tests/01_PW/115_PW_get_wf_kpar/result.ref
  tests/01_PW/CASES_CPU.txt
Labels: Features Needed, Refactor, The Absolute Zero

#6254 Change the file names of output charge densities and kinetic energy densities
  docs/advanced/input_files/input-main.md
  source/module_elecstate/module_charge/charge_init.cpp
  source/module_elecstate/test/support/chgs1.cube
  source/module_esolver/esolver_fp.cpp
  source/module_io/test_serial/rho_io_test.cpp
  source/module_io/test_serial/support/chgs1.cube
  tests/01_PW/050_PW_CHG_mismatch/chgs1.cube
  tests/01_PW/050_PW_CHG_mismatch/chgs2.cube
  tests/01_PW/051_PW_OBOD_MemSaver/chgs1.cube
  tests/01_PW/052_PW_OB/chgs1.cube
  tests/01_PW/053_PW_OD/chgs1.cube
  tests/01_PW/056_PW_IW/chgs1.cube
  tests/01_PW/088_PW_OP_nscf/chgs1.cube
  tests/01_PW/105_PW_W90/chgs1.cube
  tests/01_PW/203_PW_OK/chgs1.cube.ref
  tests/01_PW/203_PW_OK/result.ref
  tests/01_PW/203_PW_OK/taus1.cube.ref
  tests/03_NAO_multik/15_NO_KP_OB/chgs1.cube
  tests/03_NAO_multik/16_NO_KP_OD/chgs1.cube
  tests/03_NAO_multik/19_NO_KP_OH_nscf/chgs1.cube
  tests/03_NAO_multik/23_NO_KP_OK/chgs1.cube.ref
  tests/03_NAO_multik/23_NO_KP_OK/result.ref
  tests/03_NAO_multik/23_NO_KP_OK/taus1.cube.ref
  tests/03_NAO_multik/35_NO_KP_MU_nscf/chgs1.cube
  tests/03_NAO_multik/39_NO_OP_nscf/chgs1.cube
  tests/06_SDFT/18_PW_NSCF_KG_100/chgs1.cube
  tests/06_SDFT/20_PW_SDOS_MALL/chgs1.cube
  tests/06_SDFT/21_PW_SKG_10D10S/chgs1.cube
  tests/09_DeePKS/102_NO_GO_deepks_nscf/chgs1.cube
  tests/09_DeePKS/102_NO_KP_deepks_nscf/chgs1.cube
  tests/integrate/tools/catch_properties.sh
Labels: Input&Output, Refactor, The Absolute Zero
